<?php // phpcs:ignore - @generation-checksum DE-HB-4
/**
 * State City List for HB - DE.
 *
 * City count: 4
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HB - DE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bremen', 'wp-ultimo-locations'),
	__('Bremerhaven', 'wp-ultimo-locations'),
	__('Burglesum', 'wp-ultimo-locations'),
	__('Vegesack', 'wp-ultimo-locations'),
);
