<?php // phpcs:ignore - @generation-checksum DE-SL-60
/**
 * State City List for SL - DE.
 *
 * City count: 60
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SL - DE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Beckingen', 'wp-ultimo-locations'),
	__('Bexbach', 'wp-ultimo-locations'),
	__('Blieskastel', 'wp-ultimo-locations'),
	__('Bous', 'wp-ultimo-locations'),
	__('Britten', 'wp-ultimo-locations'),
	__('Dillingen', 'wp-ultimo-locations'),
	__('Ensdorf', 'wp-ultimo-locations'),
	__('Eppelborn', 'wp-ultimo-locations'),
	__('Freisen', 'wp-ultimo-locations'),
	__('Friedrichsthal', 'wp-ultimo-locations'),
	__('Fürstenhausen', 'wp-ultimo-locations'),
	__('Gersheim', 'wp-ultimo-locations'),
	__('Großrosseln', 'wp-ultimo-locations'),
	__('Hangard', 'wp-ultimo-locations'),
	__('Heidstock', 'wp-ultimo-locations'),
	__('Heusweiler', 'wp-ultimo-locations'),
	__('Homburg', 'wp-ultimo-locations'),
	__('Illingen', 'wp-ultimo-locations'),
	__('Kirkel', 'wp-ultimo-locations'),
	__('Kleinblittersdorf', 'wp-ultimo-locations'),
	__('Lebach', 'wp-ultimo-locations'),
	__('Losheim', 'wp-ultimo-locations'),
	__('Ludweiler-Warndt', 'wp-ultimo-locations'),
	__('Luisenthal', 'wp-ultimo-locations'),
	__('Mainzweiler', 'wp-ultimo-locations'),
	__('Marpingen', 'wp-ultimo-locations'),
	__('Merchweiler', 'wp-ultimo-locations'),
	__('Merzig', 'wp-ultimo-locations'),
	__('Mettlach', 'wp-ultimo-locations'),
	__('Nalbach', 'wp-ultimo-locations'),
	__('Namborn', 'wp-ultimo-locations'),
	__('Neunkirchen', 'wp-ultimo-locations'),
	__('Nohfelden', 'wp-ultimo-locations'),
	__('Nonnweiler', 'wp-ultimo-locations'),
	__('Oberthal', 'wp-ultimo-locations'),
	__('Orscholz', 'wp-ultimo-locations'),
	__('Ottweiler', 'wp-ultimo-locations'),
	__('Püttlingen', 'wp-ultimo-locations'),
	__('Quierschied', 'wp-ultimo-locations'),
	__('Riegelsberg', 'wp-ultimo-locations'),
	__('Röchling-Höhe', 'wp-ultimo-locations'),
	__('Saarbrücken', 'wp-ultimo-locations'),
	__('Saarhölzbach', 'wp-ultimo-locations'),
	__('Saarlouis', 'wp-ultimo-locations'),
	__('Saarwellingen', 'wp-ultimo-locations'),
	__('Sankt Ingbert', 'wp-ultimo-locations'),
	__('Sankt Wendel', 'wp-ultimo-locations'),
	__('Schiffweiler', 'wp-ultimo-locations'),
	__('Schmelz', 'wp-ultimo-locations'),
	__('Schwalbach', 'wp-ultimo-locations'),
	__('Spiesen-Elversberg', 'wp-ultimo-locations'),
	__('Sulzbach', 'wp-ultimo-locations'),
	__('Tholey', 'wp-ultimo-locations'),
	__('Völklingen', 'wp-ultimo-locations'),
	__('Wadern', 'wp-ultimo-locations'),
	__('Wadgassen', 'wp-ultimo-locations'),
	__('Wallerfangen', 'wp-ultimo-locations'),
	__('Weiskirchen', 'wp-ultimo-locations'),
	__('Weiten', 'wp-ultimo-locations'),
	__('Überherrn', 'wp-ultimo-locations'),
);
