<?php // phpcs:ignore - @generation-checksum IN-AS-87
/**
 * State City List for AS - IN.
 *
 * City count: 87
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AS - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abhayapuri', 'wp-ultimo-locations'),
	__('Amguri', 'wp-ultimo-locations'),
	__('Badarpur', 'wp-ultimo-locations'),
	__('Baksa', 'wp-ultimo-locations'),
	__('Barpathar', 'wp-ultimo-locations'),
	__('Barpeta', 'wp-ultimo-locations'),
	__('Barpeta Road', 'wp-ultimo-locations'),
	__('Basugaon', 'wp-ultimo-locations'),
	__('Bihpuriagaon', 'wp-ultimo-locations'),
	__('Bijni', 'wp-ultimo-locations'),
	__('Bilasipara', 'wp-ultimo-locations'),
	__('Bokajan', 'wp-ultimo-locations'),
	__('Bokakhat', 'wp-ultimo-locations'),
	__('Bongaigaon', 'wp-ultimo-locations'),
	__('Cachar', 'wp-ultimo-locations'),
	__('Chabua', 'wp-ultimo-locations'),
	__('Chapar', 'wp-ultimo-locations'),
	__('Chirang', 'wp-ultimo-locations'),
	__('Darrang', 'wp-ultimo-locations'),
	__('Dergaon', 'wp-ultimo-locations'),
	__('Dhekiajuli', 'wp-ultimo-locations'),
	__('Dhemaji', 'wp-ultimo-locations'),
	__('Dhing', 'wp-ultimo-locations'),
	__('Dhubri', 'wp-ultimo-locations'),
	__('Dibrugarh', 'wp-ultimo-locations'),
	__('Digboi', 'wp-ultimo-locations'),
	__('Dima Hasao District', 'wp-ultimo-locations'),
	__('Diphu', 'wp-ultimo-locations'),
	__('Dispur', 'wp-ultimo-locations'),
	__('Duliagaon', 'wp-ultimo-locations'),
	__('Dum Duma', 'wp-ultimo-locations'),
	__('Gauripur', 'wp-ultimo-locations'),
	__('Goalpara', 'wp-ultimo-locations'),
	__('Gohpur', 'wp-ultimo-locations'),
	__('Golaghat', 'wp-ultimo-locations'),
	__('Golakganj', 'wp-ultimo-locations'),
	__('Goshaingaon', 'wp-ultimo-locations'),
	__('Guwahati', 'wp-ultimo-locations'),
	__('Haflong', 'wp-ultimo-locations'),
	__('Hailakandi', 'wp-ultimo-locations'),
	__('Hajo', 'wp-ultimo-locations'),
	__('Hojai', 'wp-ultimo-locations'),
	__('Howli', 'wp-ultimo-locations'),
	__('Jogighopa', 'wp-ultimo-locations'),
	__('Jorhat', 'wp-ultimo-locations'),
	__('Kamrup', 'wp-ultimo-locations'),
	__('Kamrup Metropolitan', 'wp-ultimo-locations'),
	__('Karbi Anglong', 'wp-ultimo-locations'),
	__('Karimganj', 'wp-ultimo-locations'),
	__('Kharupatia', 'wp-ultimo-locations'),
	__('Kokrajhar', 'wp-ultimo-locations'),
	__('Lakhimpur', 'wp-ultimo-locations'),
	__('Lakhipur', 'wp-ultimo-locations'),
	__('Lala', 'wp-ultimo-locations'),
	__('Lumding Railway Colony', 'wp-ultimo-locations'),
	__('Mahur', 'wp-ultimo-locations'),
	__('Maibong', 'wp-ultimo-locations'),
	__('Makum', 'wp-ultimo-locations'),
	__('Mangaldai', 'wp-ultimo-locations'),
	__('Mariani', 'wp-ultimo-locations'),
	__('Moranha', 'wp-ultimo-locations'),
	__('Morigaon', 'wp-ultimo-locations'),
	__('Nagaon', 'wp-ultimo-locations'),
	__('Nahorkatiya', 'wp-ultimo-locations'),
	__('Nalbari', 'wp-ultimo-locations'),
	__('Namrup', 'wp-ultimo-locations'),
	__('Nazira', 'wp-ultimo-locations'),
	__('North Guwahati', 'wp-ultimo-locations'),
	__('North Lakhimpur', 'wp-ultimo-locations'),
	__('Numaligarh', 'wp-ultimo-locations'),
	__('Palasbari', 'wp-ultimo-locations'),
	__('Raha', 'wp-ultimo-locations'),
	__('Rangapara', 'wp-ultimo-locations'),
	__('Rangia', 'wp-ultimo-locations'),
	__('Sapatgram', 'wp-ultimo-locations'),
	__('Sarupathar', 'wp-ultimo-locations'),
	__('Sibsagar', 'wp-ultimo-locations'),
	__('Silapathar', 'wp-ultimo-locations'),
	__('Silchar', 'wp-ultimo-locations'),
	__('Soalkuchi', 'wp-ultimo-locations'),
	__('Sonari', 'wp-ultimo-locations'),
	__('Sonitpur', 'wp-ultimo-locations'),
	__('Sorbhog', 'wp-ultimo-locations'),
	__('Tezpur', 'wp-ultimo-locations'),
	__('Tinsukia', 'wp-ultimo-locations'),
	__('Titabar', 'wp-ultimo-locations'),
	__('Udalguri', 'wp-ultimo-locations'),
);
