<?php // phpcs:ignore - @generation-checksum IN-CT-78
/**
 * State City List for CT - IN.
 *
 * City count: 78
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CT - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akaltara', 'wp-ultimo-locations'),
	__('Ambagarh Chauki', 'wp-ultimo-locations'),
	__('Ambikapur', 'wp-ultimo-locations'),
	__('Arang', 'wp-ultimo-locations'),
	__('Baikunthpur', 'wp-ultimo-locations'),
	__('Balod', 'wp-ultimo-locations'),
	__('Baloda', 'wp-ultimo-locations'),
	__('Baloda Bazar', 'wp-ultimo-locations'),
	__('Basna', 'wp-ultimo-locations'),
	__('Bastar', 'wp-ultimo-locations'),
	__('Bemetara', 'wp-ultimo-locations'),
	__('Bhanpuri', 'wp-ultimo-locations'),
	__('Bhatapara', 'wp-ultimo-locations'),
	__('Bhatgaon', 'wp-ultimo-locations'),
	__('Bhilai', 'wp-ultimo-locations'),
	__('Bijapur', 'wp-ultimo-locations'),
	__('Bilaspur', 'wp-ultimo-locations'),
	__('Champa', 'wp-ultimo-locations'),
	__('Chhuikhadan', 'wp-ultimo-locations'),
	__('Deori', 'wp-ultimo-locations'),
	__('Dhamtari', 'wp-ultimo-locations'),
	__('Dongargaon', 'wp-ultimo-locations'),
	__('Dongargarh', 'wp-ultimo-locations'),
	__('Durg', 'wp-ultimo-locations'),
	__('Gandai', 'wp-ultimo-locations'),
	__('Gariaband', 'wp-ultimo-locations'),
	__('Gaurela', 'wp-ultimo-locations'),
	__('Gharghoda', 'wp-ultimo-locations'),
	__('Gidam', 'wp-ultimo-locations'),
	__('Jagdalpur', 'wp-ultimo-locations'),
	__('Janjgir', 'wp-ultimo-locations'),
	__('Janjgir-Champa', 'wp-ultimo-locations'),
	__('Jashpur', 'wp-ultimo-locations'),
	__('Jashpurnagar', 'wp-ultimo-locations'),
	__('Junagarh', 'wp-ultimo-locations'),
	__('Kabeerdham', 'wp-ultimo-locations'),
	__('Kanker', 'wp-ultimo-locations'),
	__('Katghora', 'wp-ultimo-locations'),
	__('Kawardha', 'wp-ultimo-locations'),
	__('Khairagarh', 'wp-ultimo-locations'),
	__('Khamharia', 'wp-ultimo-locations'),
	__('Kharod', 'wp-ultimo-locations'),
	__('Kharsia', 'wp-ultimo-locations'),
	__('Kirandul', 'wp-ultimo-locations'),
	__('Kondagaon', 'wp-ultimo-locations'),
	__('Korba', 'wp-ultimo-locations'),
	__('Koriya', 'wp-ultimo-locations'),
	__('Kota', 'wp-ultimo-locations'),
	__('Kotaparh', 'wp-ultimo-locations'),
	__('Kumhari', 'wp-ultimo-locations'),
	__('Kurud', 'wp-ultimo-locations'),
	__('Lormi', 'wp-ultimo-locations'),
	__('Mahasamund', 'wp-ultimo-locations'),
	__('Mungeli', 'wp-ultimo-locations'),
	__('Narayanpur', 'wp-ultimo-locations'),
	__('Narharpur', 'wp-ultimo-locations'),
	__('Pandaria', 'wp-ultimo-locations'),
	__('Pandatarai', 'wp-ultimo-locations'),
	__('Pasan', 'wp-ultimo-locations'),
	__('Patan', 'wp-ultimo-locations'),
	__('Pathalgaon', 'wp-ultimo-locations'),
	__('Pendra', 'wp-ultimo-locations'),
	__('Pithora', 'wp-ultimo-locations'),
	__('Raigarh', 'wp-ultimo-locations'),
	__('Raipur', 'wp-ultimo-locations'),
	__('Raj Nandgaon', 'wp-ultimo-locations'),
	__('Raj-Nandgaon', 'wp-ultimo-locations'),
	__('Ramanuj Ganj', 'wp-ultimo-locations'),
	__('Ratanpur', 'wp-ultimo-locations'),
	__('Sakti', 'wp-ultimo-locations'),
	__('Saraipali', 'wp-ultimo-locations'),
	__('Sarangarh', 'wp-ultimo-locations'),
	__('Seorinarayan', 'wp-ultimo-locations'),
	__('Simga', 'wp-ultimo-locations'),
	__('Surguja', 'wp-ultimo-locations'),
	__('Takhatpur', 'wp-ultimo-locations'),
	__('Umarkot', 'wp-ultimo-locations'),
	__('Uttar Bastar Kanker', 'wp-ultimo-locations'),
);
