<?php // phpcs:ignore - @generation-checksum IN-DL-19
/**
 * State City List for DL - IN.
 *
 * City count: 19
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for DL - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alipur', 'wp-ultimo-locations'),
	__('Bawana', 'wp-ultimo-locations'),
	__('Central Delhi', 'wp-ultimo-locations'),
	__('Delhi', 'wp-ultimo-locations'),
	__('Deoli', 'wp-ultimo-locations'),
	__('East Delhi', 'wp-ultimo-locations'),
	__('Karol Bagh', 'wp-ultimo-locations'),
	__('Najafgarh', 'wp-ultimo-locations'),
	__('Nangloi Jat', 'wp-ultimo-locations'),
	__('Narela', 'wp-ultimo-locations'),
	__('New Delhi', 'wp-ultimo-locations'),
	__('North Delhi', 'wp-ultimo-locations'),
	__('North East Delhi', 'wp-ultimo-locations'),
	__('North West Delhi', 'wp-ultimo-locations'),
	__('Pitampura', 'wp-ultimo-locations'),
	__('Rohini', 'wp-ultimo-locations'),
	__('South Delhi', 'wp-ultimo-locations'),
	__('South West Delhi', 'wp-ultimo-locations'),
	__('West Delhi', 'wp-ultimo-locations'),
);
