<?php // phpcs:ignore - @generation-checksum IN-JH-77
/**
 * State City List for JH - IN.
 *
 * City count: 77
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for JH - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bagra', 'wp-ultimo-locations'),
	__('Barka Kana', 'wp-ultimo-locations'),
	__('Barki Saria', 'wp-ultimo-locations'),
	__('Barwadih', 'wp-ultimo-locations'),
	__('Bhojudih', 'wp-ultimo-locations'),
	__('Bokaro', 'wp-ultimo-locations'),
	__('Bundu', 'wp-ultimo-locations'),
	__('Chaibasa', 'wp-ultimo-locations'),
	__('Chakradharpur', 'wp-ultimo-locations'),
	__('Chakulia', 'wp-ultimo-locations'),
	__('Chandil', 'wp-ultimo-locations'),
	__('Chas', 'wp-ultimo-locations'),
	__('Chatra', 'wp-ultimo-locations'),
	__('Chiria', 'wp-ultimo-locations'),
	__('Daltonganj', 'wp-ultimo-locations'),
	__('Deogarh', 'wp-ultimo-locations'),
	__('Dhanbad', 'wp-ultimo-locations'),
	__('Dhanwar', 'wp-ultimo-locations'),
	__('Dugda', 'wp-ultimo-locations'),
	__('Dumka', 'wp-ultimo-locations'),
	__('Garhwa', 'wp-ultimo-locations'),
	__('Ghatsila', 'wp-ultimo-locations'),
	__('Giridih', 'wp-ultimo-locations'),
	__('Gobindpur', 'wp-ultimo-locations'),
	__('Godda', 'wp-ultimo-locations'),
	__('Gomoh', 'wp-ultimo-locations'),
	__('Gopinathpur', 'wp-ultimo-locations'),
	__('Gua', 'wp-ultimo-locations'),
	__('Gumia', 'wp-ultimo-locations'),
	__('Gumla', 'wp-ultimo-locations'),
	__('Hazaribag', 'wp-ultimo-locations'),
	__('Hazaribagh', 'wp-ultimo-locations'),
	__('Hesla', 'wp-ultimo-locations'),
	__('Husainabad', 'wp-ultimo-locations'),
	__('Jagannathpur', 'wp-ultimo-locations'),
	__('Jamadoba', 'wp-ultimo-locations'),
	__('Jamshedpur', 'wp-ultimo-locations'),
	__('Jamtara', 'wp-ultimo-locations'),
	__('Jasidih', 'wp-ultimo-locations'),
	__('Jharia', 'wp-ultimo-locations'),
	__('Jugsalai', 'wp-ultimo-locations'),
	__('Jumri Tilaiya', 'wp-ultimo-locations'),
	__('Kalikapur', 'wp-ultimo-locations'),
	__('Kandra', 'wp-ultimo-locations'),
	__('Kanke', 'wp-ultimo-locations'),
	__('Katras', 'wp-ultimo-locations'),
	__('Kenduadih', 'wp-ultimo-locations'),
	__('Kharsawan', 'wp-ultimo-locations'),
	__('Khunti', 'wp-ultimo-locations'),
	__('Kodarma', 'wp-ultimo-locations'),
	__('Kuju', 'wp-ultimo-locations'),
	__('Latehar', 'wp-ultimo-locations'),
	__('Lohardaga', 'wp-ultimo-locations'),
	__('Madhupur', 'wp-ultimo-locations'),
	__('Malkera', 'wp-ultimo-locations'),
	__('Manoharpur', 'wp-ultimo-locations'),
	__('Mugma', 'wp-ultimo-locations'),
	__('Mushabani', 'wp-ultimo-locations'),
	__('Neturhat', 'wp-ultimo-locations'),
	__('Nirsa', 'wp-ultimo-locations'),
	__('Noamundi', 'wp-ultimo-locations'),
	__('Pakur', 'wp-ultimo-locations'),
	__('Palamu', 'wp-ultimo-locations'),
	__('Pashchim Singhbhum', 'wp-ultimo-locations'),
	__('Pathardih', 'wp-ultimo-locations'),
	__('Purba Singhbhum', 'wp-ultimo-locations'),
	__('Ramgarh', 'wp-ultimo-locations'),
	__('Ranchi', 'wp-ultimo-locations'),
	__('Ray', 'wp-ultimo-locations'),
	__('Sahibganj', 'wp-ultimo-locations'),
	__('Saraikela', 'wp-ultimo-locations'),
	__('Sarubera', 'wp-ultimo-locations'),
	__('Sijua', 'wp-ultimo-locations'),
	__('Simdega', 'wp-ultimo-locations'),
	__('Sini', 'wp-ultimo-locations'),
	__('Topchanchi', 'wp-ultimo-locations'),
	__('patamda', 'wp-ultimo-locations'),
);
