<?php // phpcs:ignore - @generation-checksum IN-TG-89
/**
 * State City List for TG - IN.
 *
 * City count: 89
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TG - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Adilabad', 'wp-ultimo-locations'),
	__('Alampur', 'wp-ultimo-locations'),
	__('Andol', 'wp-ultimo-locations'),
	__('Asifabad', 'wp-ultimo-locations'),
	__('Balapur', 'wp-ultimo-locations'),
	__('Banswada', 'wp-ultimo-locations'),
	__('Bellampalli', 'wp-ultimo-locations'),
	__('Bhadrachalam', 'wp-ultimo-locations'),
	__('Bhadradri Kothagudem', 'wp-ultimo-locations'),
	__('Bhaisa', 'wp-ultimo-locations'),
	__('Bhongir', 'wp-ultimo-locations'),
	__('Bodhan', 'wp-ultimo-locations'),
	__('Chandur', 'wp-ultimo-locations'),
	__('Chatakonda', 'wp-ultimo-locations'),
	__('Dasnapur', 'wp-ultimo-locations'),
	__('Devarkonda', 'wp-ultimo-locations'),
	__('Dornakal', 'wp-ultimo-locations'),
	__('Farrukhnagar', 'wp-ultimo-locations'),
	__('Gaddi Annaram', 'wp-ultimo-locations'),
	__('Gadwal', 'wp-ultimo-locations'),
	__('Ghatkesar', 'wp-ultimo-locations'),
	__('Gopalur', 'wp-ultimo-locations'),
	__('Gudur', 'wp-ultimo-locations'),
	__('Hyderabad', 'wp-ultimo-locations'),
	__('Jagtial', 'wp-ultimo-locations'),
	__('Jangaon', 'wp-ultimo-locations'),
	__('Jangoan', 'wp-ultimo-locations'),
	__('Jayashankar Bhupalapally', 'wp-ultimo-locations'),
	__('Jogulamba Gadwal', 'wp-ultimo-locations'),
	__('Kagaznagar', 'wp-ultimo-locations'),
	__('Kamareddi', 'wp-ultimo-locations'),
	__('Kamareddy', 'wp-ultimo-locations'),
	__('Karimnagar', 'wp-ultimo-locations'),
	__('Khammam', 'wp-ultimo-locations'),
	__('Kodar', 'wp-ultimo-locations'),
	__('Koratla', 'wp-ultimo-locations'),
	__('Kothapet', 'wp-ultimo-locations'),
	__('Kottagudem', 'wp-ultimo-locations'),
	__('Kottapalli', 'wp-ultimo-locations'),
	__('Kukatpalli', 'wp-ultimo-locations'),
	__('Kyathampalle', 'wp-ultimo-locations'),
	__('Lakshettipet', 'wp-ultimo-locations'),
	__('Lal Bahadur Nagar', 'wp-ultimo-locations'),
	__('Mahabubabad', 'wp-ultimo-locations'),
	__('Mahbubnagar', 'wp-ultimo-locations'),
	__('Malkajgiri', 'wp-ultimo-locations'),
	__('Mancheral', 'wp-ultimo-locations'),
	__('Mandamarri', 'wp-ultimo-locations'),
	__('Manthani', 'wp-ultimo-locations'),
	__('Manuguru', 'wp-ultimo-locations'),
	__('Medak', 'wp-ultimo-locations'),
	__('Medchal', 'wp-ultimo-locations'),
	__('Medchal Malkajgiri', 'wp-ultimo-locations'),
	__('Mirialguda', 'wp-ultimo-locations'),
	__('Nagar Karnul', 'wp-ultimo-locations'),
	__('Nalgonda', 'wp-ultimo-locations'),
	__('Narayanpet', 'wp-ultimo-locations'),
	__('Narsingi', 'wp-ultimo-locations'),
	__('Naspur', 'wp-ultimo-locations'),
	__('Nirmal', 'wp-ultimo-locations'),
	__('Nizamabad', 'wp-ultimo-locations'),
	__('Paloncha', 'wp-ultimo-locations'),
	__('Palwancha', 'wp-ultimo-locations'),
	__('Patancheru', 'wp-ultimo-locations'),
	__('Peddapalli', 'wp-ultimo-locations'),
	__('Quthbullapur', 'wp-ultimo-locations'),
	__('Rajanna Sircilla', 'wp-ultimo-locations'),
	__('Ramagundam', 'wp-ultimo-locations'),
	__('Ramgundam', 'wp-ultimo-locations'),
	__('Rangareddi', 'wp-ultimo-locations'),
	__('Sadaseopet', 'wp-ultimo-locations'),
	__('Sangareddi', 'wp-ultimo-locations'),
	__('Sathupalli', 'wp-ultimo-locations'),
	__('Secunderabad', 'wp-ultimo-locations'),
	__('Serilingampalle', 'wp-ultimo-locations'),
	__('Siddipet', 'wp-ultimo-locations'),
	__('Singapur', 'wp-ultimo-locations'),
	__('Sirpur', 'wp-ultimo-locations'),
	__('Sirsilla', 'wp-ultimo-locations'),
	__('Sriramnagar', 'wp-ultimo-locations'),
	__('Suriapet', 'wp-ultimo-locations'),
	__('Tandur', 'wp-ultimo-locations'),
	__('Uppal Kalan', 'wp-ultimo-locations'),
	__('Vemalwada', 'wp-ultimo-locations'),
	__('Vikarabad', 'wp-ultimo-locations'),
	__('Wanparti', 'wp-ultimo-locations'),
	__('Warangal', 'wp-ultimo-locations'),
	__('Yellandu', 'wp-ultimo-locations'),
	__('Zahirabad', 'wp-ultimo-locations'),
);
