<?php // phpcs:ignore - @generation-checksum IN-TR-19
/**
 * State City List for TR - IN.
 *
 * City count: 19
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TR - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Agartala', 'wp-ultimo-locations'),
	__('Amarpur', 'wp-ultimo-locations'),
	__('Ambasa', 'wp-ultimo-locations'),
	__('Barjala', 'wp-ultimo-locations'),
	__('Belonia', 'wp-ultimo-locations'),
	__('Dhalai', 'wp-ultimo-locations'),
	__('Dharmanagar', 'wp-ultimo-locations'),
	__('Gomati', 'wp-ultimo-locations'),
	__('Kailashahar', 'wp-ultimo-locations'),
	__('Kamalpur', 'wp-ultimo-locations'),
	__('Khowai', 'wp-ultimo-locations'),
	__('North Tripura', 'wp-ultimo-locations'),
	__('Ranir Bazar', 'wp-ultimo-locations'),
	__('Sabrum', 'wp-ultimo-locations'),
	__('Sonamura', 'wp-ultimo-locations'),
	__('South Tripura', 'wp-ultimo-locations'),
	__('Udaipur', 'wp-ultimo-locations'),
	__('Unakoti', 'wp-ultimo-locations'),
	__('West Tripura', 'wp-ultimo-locations'),
);
