<?php // phpcs:ignore - @generation-checksum IN-UT-55
/**
 * State City List for UT - IN.
 *
 * City count: 55
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for UT - IN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Almora', 'wp-ultimo-locations'),
	__('Bageshwar', 'wp-ultimo-locations'),
	__('Barkot', 'wp-ultimo-locations'),
	__('Bazpur', 'wp-ultimo-locations'),
	__('Bhim Tal', 'wp-ultimo-locations'),
	__('Bhowali', 'wp-ultimo-locations'),
	__('Birbhaddar', 'wp-ultimo-locations'),
	__('Chakrata', 'wp-ultimo-locations'),
	__('Chamoli', 'wp-ultimo-locations'),
	__('Champawat', 'wp-ultimo-locations'),
	__('Clement Town', 'wp-ultimo-locations'),
	__('Dehradun', 'wp-ultimo-locations'),
	__('Devaprayag', 'wp-ultimo-locations'),
	__('Dharchula', 'wp-ultimo-locations'),
	__('Doiwala', 'wp-ultimo-locations'),
	__('Dugadda', 'wp-ultimo-locations'),
	__('Dwarahat', 'wp-ultimo-locations'),
	__('Garhwal', 'wp-ultimo-locations'),
	__('Haldwani', 'wp-ultimo-locations'),
	__('Harbatpur', 'wp-ultimo-locations'),
	__('Haridwar', 'wp-ultimo-locations'),
	__('Jaspur', 'wp-ultimo-locations'),
	__('Joshimath', 'wp-ultimo-locations'),
	__('Kaladhungi', 'wp-ultimo-locations'),
	__('Kalagarh Project Colony', 'wp-ultimo-locations'),
	__('Kashipur', 'wp-ultimo-locations'),
	__('Khatima', 'wp-ultimo-locations'),
	__('Kichha', 'wp-ultimo-locations'),
	__('Kotdwara', 'wp-ultimo-locations'),
	__('Laksar', 'wp-ultimo-locations'),
	__('Lansdowne', 'wp-ultimo-locations'),
	__('Lohaghat', 'wp-ultimo-locations'),
	__('Manglaur', 'wp-ultimo-locations'),
	__('Mussoorie', 'wp-ultimo-locations'),
	__('Naini Tal', 'wp-ultimo-locations'),
	__('Narendranagar', 'wp-ultimo-locations'),
	__('Pauri', 'wp-ultimo-locations'),
	__('Pipalkoti', 'wp-ultimo-locations'),
	__('Pithoragarh', 'wp-ultimo-locations'),
	__('Raipur', 'wp-ultimo-locations'),
	__('Raiwala Bara', 'wp-ultimo-locations'),
	__('Ramnagar', 'wp-ultimo-locations'),
	__('Ranikhet', 'wp-ultimo-locations'),
	__('Rishikesh', 'wp-ultimo-locations'),
	__('Roorkee', 'wp-ultimo-locations'),
	__('Rudraprayag', 'wp-ultimo-locations'),
	__('Sitarganj', 'wp-ultimo-locations'),
	__('Srinagar', 'wp-ultimo-locations'),
	__('Sultanpur', 'wp-ultimo-locations'),
	__('Tanakpur', 'wp-ultimo-locations'),
	__('Tehri', 'wp-ultimo-locations'),
	__('Tehri-Garhwal', 'wp-ultimo-locations'),
	__('Udham Singh Nagar', 'wp-ultimo-locations'),
	__('Uttarkashi', 'wp-ultimo-locations'),
	__('Vikasnagar', 'wp-ultimo-locations'),
);
