<?php // phpcs:ignore - @generation-checksum BR-AM-62
/**
 * State City List for AM - BR.
 *
 * City count: 62
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AM - BR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alvarães', 'wp-ultimo-locations'),
	__('Amaturá', 'wp-ultimo-locations'),
	__('Anamã', 'wp-ultimo-locations'),
	__('Anori', 'wp-ultimo-locations'),
	__('Apuí', 'wp-ultimo-locations'),
	__('Atalaia do Norte', 'wp-ultimo-locations'),
	__('Autazes', 'wp-ultimo-locations'),
	__('Barcelos', 'wp-ultimo-locations'),
	__('Barreirinha', 'wp-ultimo-locations'),
	__('Benjamin Constant', 'wp-ultimo-locations'),
	__('Beruri', 'wp-ultimo-locations'),
	__('Boa Vista do Ramos', 'wp-ultimo-locations'),
	__('Boca do Acre', 'wp-ultimo-locations'),
	__('Borba', 'wp-ultimo-locations'),
	__('Caapiranga', 'wp-ultimo-locations'),
	__('Canutama', 'wp-ultimo-locations'),
	__('Carauari', 'wp-ultimo-locations'),
	__('Careiro', 'wp-ultimo-locations'),
	__('Careiro da Várzea', 'wp-ultimo-locations'),
	__('Coari', 'wp-ultimo-locations'),
	__('Codajás', 'wp-ultimo-locations'),
	__('Eirunepé', 'wp-ultimo-locations'),
	__('Envira', 'wp-ultimo-locations'),
	__('Fonte Boa', 'wp-ultimo-locations'),
	__('Guajará', 'wp-ultimo-locations'),
	__('Humaitá', 'wp-ultimo-locations'),
	__('Ipixuna', 'wp-ultimo-locations'),
	__('Iranduba', 'wp-ultimo-locations'),
	__('Itacoatiara', 'wp-ultimo-locations'),
	__('Itamarati', 'wp-ultimo-locations'),
	__('Itapiranga', 'wp-ultimo-locations'),
	__('Japurá', 'wp-ultimo-locations'),
	__('Juruá', 'wp-ultimo-locations'),
	__('Jutaí', 'wp-ultimo-locations'),
	__('Lábrea', 'wp-ultimo-locations'),
	__('Manacapuru', 'wp-ultimo-locations'),
	__('Manaquiri', 'wp-ultimo-locations'),
	__('Manaus', 'wp-ultimo-locations'),
	__('Manicoré', 'wp-ultimo-locations'),
	__('Maraã', 'wp-ultimo-locations'),
	__('Maués', 'wp-ultimo-locations'),
	__('Nhamundá', 'wp-ultimo-locations'),
	__('Nova Olinda do Norte', 'wp-ultimo-locations'),
	__('Novo Airão', 'wp-ultimo-locations'),
	__('Novo Aripuanã', 'wp-ultimo-locations'),
	__('Parintins', 'wp-ultimo-locations'),
	__('Pauini', 'wp-ultimo-locations'),
	__('Presidente Figueiredo', 'wp-ultimo-locations'),
	__('Rio Preto da Eva', 'wp-ultimo-locations'),
	__('Santa Isabel do Rio Negro', 'wp-ultimo-locations'),
	__('Santo Antônio do Içá', 'wp-ultimo-locations'),
	__('Silves', 'wp-ultimo-locations'),
	__('São Gabriel da Cachoeira', 'wp-ultimo-locations'),
	__('São Paulo de Olivença', 'wp-ultimo-locations'),
	__('São Sebastião do Uatumã', 'wp-ultimo-locations'),
	__('Tabatinga', 'wp-ultimo-locations'),
	__('Tapauá', 'wp-ultimo-locations'),
	__('Tefé', 'wp-ultimo-locations'),
	__('Tonantins', 'wp-ultimo-locations'),
	__('Uarini', 'wp-ultimo-locations'),
	__('Urucará', 'wp-ultimo-locations'),
	__('Urucurituba', 'wp-ultimo-locations'),
);
