<?php // phpcs:ignore - @generation-checksum BR-AP-16
/**
 * State City List for AP - BR.
 *
 * City count: 16
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AP - BR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Amapá', 'wp-ultimo-locations'),
	__('Calçoene', 'wp-ultimo-locations'),
	__('Cutias', 'wp-ultimo-locations'),
	__('Ferreira Gomes', 'wp-ultimo-locations'),
	__('Itaubal', 'wp-ultimo-locations'),
	__('Laranjal do Jari', 'wp-ultimo-locations'),
	__('Macapá', 'wp-ultimo-locations'),
	__('Mazagão', 'wp-ultimo-locations'),
	__('Oiapoque', 'wp-ultimo-locations'),
	__('Pedra Branca do Amapari', 'wp-ultimo-locations'),
	__('Porto Grande', 'wp-ultimo-locations'),
	__('Pracuúba', 'wp-ultimo-locations'),
	__('Santana', 'wp-ultimo-locations'),
	__('Serra do Navio', 'wp-ultimo-locations'),
	__('Tartarugalzinho', 'wp-ultimo-locations'),
	__('Vitória do Jari', 'wp-ultimo-locations'),
);
