<?php
/**
 * Schema for checkout@form-update.
 *
 * @package WP_Ultimo\API\Schemas
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Schema for checkout@form-update.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-12
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.11
 */
return [
	'slug'                => [
		'description' => __('The checkout form slug. It needs to be unique and preferably make it clear what it is about. E.g. my_checkout_form.', 'wp-multisite-waas'),
		'type'        => 'string',
		'required'    => false,
	],
	'name'                => [
		'description' => __('Your checkout form name, which is used as checkout form title as well.', 'wp-multisite-waas'),
		'type'        => 'string',
		'required'    => false,
	],
	'active'              => [
		'description' => __('Set this checkout form as active (true), which means available to be used, or inactive (false).', 'wp-multisite-waas'),
		'type'        => 'boolean',
		'required'    => false,
	],
	'custom_css'          => [
		'description' => __('Custom CSS code for the checkout form.', 'wp-multisite-waas'),
		'type'        => 'string',
		'required'    => false,
	],
	'settings'            => [
		'description' => __('The checkout form settings and configurations.', 'wp-multisite-waas'),
		'type'        => 'array',
		'required'    => false,
	],
	'allowed_countries'   => [
		'description' => __('The allowed countries that can access this checkout.', 'wp-multisite-waas'),
		'type'        => 'string',
		'required'    => false,
	],
	'thank_you_page_id'   => [
		'description' => __('The thank you page ID. This page is shown after a successful purchase.', 'wp-multisite-waas'),
		'type'        => 'integer',
		'required'    => false,
	],
	'conversion_snippets' => [
		'description' => __('Snippets to run on thank you page.', 'wp-multisite-waas'),
		'type'        => 'string',
		'required'    => false,
	],
	'template'            => [
		'description' => __("Template mode. Can be either 'blank', 'single-step' or 'multi-step'.", 'wp-multisite-waas'),
		'type'        => 'string',
		'required'    => false,
		'enum'        => [
			'blank',
			'single-step',
			'multi-step',
		],
	],
	'date_created'        => [
		'description' => __('Model creation date.', 'wp-multisite-waas'),
		'type'        => 'string',
		'required'    => false,
	],
	'date_modified'       => [
		'description' => __('Model last modification date.', 'wp-multisite-waas'),
		'type'        => 'string',
		'required'    => false,
	],
	'migrated_from_id'    => [
		'description' => __('The ID of the original 1.X model that was used to generate this item on migration.', 'wp-multisite-waas'),
		'type'        => 'integer',
		'required'    => false,
	],
	'skip_validation'     => [
		'description' => __('Set true to have field information validation bypassed when saving this event.', 'wp-multisite-waas'),
		'type'        => 'boolean',
		'required'    => false,
	],
];
