<?php
/**
 * Schema for site@update.
 *
 * @package WP_Ultimo\API\Schemas
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Schema for site@update.
 *
 * @since 2.0.11
 * @internal last-generated in 2022-12
 * @generated class generated by our build scripts, do not change!
 *
 * @since 2.0.11
 */
return [
	'categories'        => [
		'description' => __('The categories this site belongs to.', 'multisite-ultimate'),
		'type'        => 'array',
		'required'    => false,
	],
	'featured_image_id' => [
		'description' => __('The ID of the feature image of the site.', 'multisite-ultimate'),
		'type'        => 'integer',
		'required'    => false,
	],
	'site_id'           => [
		'description' => __('The network ID for this site.', 'multisite-ultimate'),
		'type'        => 'integer',
		'required'    => false,
	],
	'title'             => [
		'description' => __('The site title.', 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
	],
	'name'              => [
		'description' => __('The site name.', 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
	],
	'description'       => [
		'description' => __('A description for the site, usually a short text.', 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
	],
	'domain'            => [
		'description' => __("The site domain. You don't need to put http or https in front of your domain in this field. e.g: example.com.", 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
	],
	'path'              => [
		'description' => __('Path of the site. Used when in sub-directory mode.', 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
	],
	'registered'        => [
		'description' => __('Date when the site was registered.', 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
	],
	'last_updated'      => [
		'description' => __('Date of the last update on this site.', 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
	],
	'active'            => [
		'description' => __('Holds the ID of the customer that owns this site.', 'multisite-ultimate'),
		'type'        => 'integer',
		'required'    => false,
	],
	'public'            => [
		'description' => __('Set true if this site is a public one, false if not.', 'multisite-ultimate'),
		'type'        => 'boolean',
		'required'    => false,
	],
	'archived'          => [
		'description' => __('Is this an archived site.', 'multisite-ultimate'),
		'type'        => 'boolean',
		'required'    => false,
	],
	'mature'            => [
		'description' => __('Is this a site with mature content.', 'multisite-ultimate'),
		'type'        => 'boolean',
		'required'    => false,
	],
	'spam'              => [
		'description' => __('Is this an spam site.', 'multisite-ultimate'),
		'type'        => 'boolean',
		'required'    => false,
	],
	'deleted'           => [
		'description' => __('Is this site deleted.', 'multisite-ultimate'),
		'type'        => 'boolean',
		'required'    => false,
	],
	'lang_id'           => [
		'description' => __('The ID of the language being used on this site.', 'multisite-ultimate'),
		'type'        => 'integer',
		'required'    => false,
	],
	'customer_id'       => [
		'description' => __('The ID of the customer that owns this site.', 'multisite-ultimate'),
		'type'        => 'integer',
		'required'    => false,
	],
	'membership_id'     => [
		'description' => __('The ID of the membership associated with this site, if any.', 'multisite-ultimate'),
		'type'        => 'integer',
		'required'    => false,
	],
	'template_id'       => [
		'description' => __('The ID of the templated used to create this site.', 'multisite-ultimate'),
		'type'        => 'integer',
		'required'    => false,
	],
	'type'              => [
		'description' => __('The type of this particular site. Can be default, site_template, customer_owned, pending, external, main or other values added by third-party add-ons.', 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
		'enum'        => [
			'default',
			'site_template',
			'customer_owned',
			'pending',
			'external',
			'main',
		],
	],
	'signup_options'    => [
		'description' => __('Keeps signup options for the site.', 'multisite-ultimate'),
		'type'        => 'array',
		'required'    => false,
	],
	'signup_meta'       => [
		'description' => __('Keeps signup meta for the site.', 'multisite-ultimate'),
		'type'        => 'array',
		'required'    => false,
	],
	'date_created'      => [
		'description' => __('Model creation date.', 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
	],
	'date_modified'     => [
		'description' => __('Model last modification date.', 'multisite-ultimate'),
		'type'        => 'string',
		'required'    => false,
	],
	'migrated_from_id'  => [
		'description' => __('The ID of the original 1.X model that was used to generate this item on migration.', 'multisite-ultimate'),
		'type'        => 'integer',
		'required'    => false,
	],
	'skip_validation'   => [
		'description' => __('Set true to have field information validation bypassed when saving this event.', 'multisite-ultimate'),
		'type'        => 'boolean',
		'required'    => false,
	],
];
