<?php // phpcs:ignore - @generation-checksum ES-CE-2
/**
 * State City List for CE - ES.
 *
 * City count: 2
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CE - ES.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Benzú', 'wp-ultimo-locations'),
	__('Ceuta', 'wp-ultimo-locations'),
);
