<?php // phpcs:ignore - @generation-checksum MY-15-1
/**
 * State City List for 15 - MY.
 *
 * City count: 1
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 15 - MY.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Labuan', 'wp-ultimo-locations'),
);
