<?php // phpcs:ignore - @generation-checksum ZA-EC-38
/**
 * State City List for EC - ZA.
 *
 * City count: 38
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for EC - ZA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Adelaide', 'wp-ultimo-locations'),
	__('Alfred Nzo District Municipality', 'wp-ultimo-locations'),
	__('Alice', 'wp-ultimo-locations'),
	__('Aliwal North', 'wp-ultimo-locations'),
	__('Amathole District Municipality', 'wp-ultimo-locations'),
	__('Bhisho', 'wp-ultimo-locations'),
	__('Buffalo City Metropolitan Municipality', 'wp-ultimo-locations'),
	__('Burgersdorp', 'wp-ultimo-locations'),
	__('Butterworth', 'wp-ultimo-locations'),
	__('Cacadu District Municipality', 'wp-ultimo-locations'),
	__('Chris Hani District Municipality', 'wp-ultimo-locations'),
	__('Cradock', 'wp-ultimo-locations'),
	__('Dordrecht', 'wp-ultimo-locations'),
	__('East London', 'wp-ultimo-locations'),
	__('Elliot', 'wp-ultimo-locations'),
	__('Fort Beaufort', 'wp-ultimo-locations'),
	__('Graaff-Reinet', 'wp-ultimo-locations'),
	__('Grahamstown', 'wp-ultimo-locations'),
	__('Ilinge', 'wp-ultimo-locations'),
	__('Joe Gqabi District Municipality', 'wp-ultimo-locations'),
	__('Kirkwood', 'wp-ultimo-locations'),
	__('Kruisfontein', 'wp-ultimo-locations'),
	__('Lady Frere', 'wp-ultimo-locations'),
	__('Middelburg', 'wp-ultimo-locations'),
	__('Molteno', 'wp-ultimo-locations'),
	__('Mthatha', 'wp-ultimo-locations'),
	__('Nelson Mandela Bay Metropolitan Municipality', 'wp-ultimo-locations'),
	__('OR Tambo District Municipality', 'wp-ultimo-locations'),
	__('Port Alfred', 'wp-ultimo-locations'),
	__('Port Elizabeth', 'wp-ultimo-locations'),
	__('Port Saint John’s', 'wp-ultimo-locations'),
	__('Queensdale', 'wp-ultimo-locations'),
	__('Queenstown', 'wp-ultimo-locations'),
	__('Somerset East', 'wp-ultimo-locations'),
	__('Stutterheim', 'wp-ultimo-locations'),
	__('Uitenhage', 'wp-ultimo-locations'),
	__('Whittlesea', 'wp-ultimo-locations'),
	__('Willowmore', 'wp-ultimo-locations'),
);
