<?php // phpcs:ignore - @generation-checksum ZA-KZN-43
/**
 * State City List for KZN - ZA.
 *
 * City count: 43
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KZN - ZA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Amajuba District Municipality', 'wp-ultimo-locations'),
	__('Ballito', 'wp-ultimo-locations'),
	__('Berea', 'wp-ultimo-locations'),
	__('Dundee', 'wp-ultimo-locations'),
	__('Durban', 'wp-ultimo-locations'),
	__('Ekuvukeni', 'wp-ultimo-locations'),
	__('Empangeni', 'wp-ultimo-locations'),
	__('Eshowe', 'wp-ultimo-locations'),
	__('Glencoe', 'wp-ultimo-locations'),
	__('Greytown', 'wp-ultimo-locations'),
	__('Hluhluwe', 'wp-ultimo-locations'),
	__('Howick', 'wp-ultimo-locations'),
	__('Kokstad', 'wp-ultimo-locations'),
	__('KwaDukuza', 'wp-ultimo-locations'),
	__('Margate', 'wp-ultimo-locations'),
	__('Mondlo', 'wp-ultimo-locations'),
	__('Mooirivier', 'wp-ultimo-locations'),
	__('Mpophomeni', 'wp-ultimo-locations'),
	__('Mpumalanga', 'wp-ultimo-locations'),
	__('Mtubatuba', 'wp-ultimo-locations'),
	__('Ndwedwe', 'wp-ultimo-locations'),
	__('Newcastle', 'wp-ultimo-locations'),
	__('Pietermaritzburg', 'wp-ultimo-locations'),
	__('Port Shepstone', 'wp-ultimo-locations'),
	__('Richards Bay', 'wp-ultimo-locations'),
	__('Richmond', 'wp-ultimo-locations'),
	__('Scottburgh', 'wp-ultimo-locations'),
	__('Sisonke District Municipality', 'wp-ultimo-locations'),
	__('Sundumbili', 'wp-ultimo-locations'),
	__('Ugu District Municipality', 'wp-ultimo-locations'),
	__('Ulundi', 'wp-ultimo-locations'),
	__('Utrecht', 'wp-ultimo-locations'),
	__('Vryheid', 'wp-ultimo-locations'),
	__('Zululand District Municipality', 'wp-ultimo-locations'),
	__('eMkhomazi', 'wp-ultimo-locations'),
	__('eSikhaleni', 'wp-ultimo-locations'),
	__('eThekwini Metropolitan Municipality', 'wp-ultimo-locations'),
	__('iLembe District Municipality', 'wp-ultimo-locations'),
	__('uMgungundlovu District Municipality', 'wp-ultimo-locations'),
	__('uMkhanyakude District Municipality', 'wp-ultimo-locations'),
	__('uMzinyathi District Municipality', 'wp-ultimo-locations'),
	__('uThukela District Municipality', 'wp-ultimo-locations'),
	__('uThungulu District Municipality', 'wp-ultimo-locations'),
);
