<?php // phpcs:ignore - @generation-checksum ZA-LP-23
/**
 * State City List for LP - ZA.
 *
 * City count: 23
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for LP - ZA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bochum', 'wp-ultimo-locations'),
	__('Capricorn District Municipality', 'wp-ultimo-locations'),
	__('Duiwelskloof', 'wp-ultimo-locations'),
	__('Ga-Kgapane', 'wp-ultimo-locations'),
	__('Giyani', 'wp-ultimo-locations'),
	__('Lebowakgomo', 'wp-ultimo-locations'),
	__('Louis Trichardt', 'wp-ultimo-locations'),
	__('Mankoeng', 'wp-ultimo-locations'),
	__('Modimolle', 'wp-ultimo-locations'),
	__('Mokopane', 'wp-ultimo-locations'),
	__('Mopani District Municipality', 'wp-ultimo-locations'),
	__('Musina', 'wp-ultimo-locations'),
	__('Nkowakowa', 'wp-ultimo-locations'),
	__('Phalaborwa', 'wp-ultimo-locations'),
	__('Polokwane', 'wp-ultimo-locations'),
	__('Sekhukhune District Municipality', 'wp-ultimo-locations'),
	__('Thabazimbi', 'wp-ultimo-locations'),
	__('Thohoyandou', 'wp-ultimo-locations'),
	__('Thulamahashi', 'wp-ultimo-locations'),
	__('Tzaneen', 'wp-ultimo-locations'),
	__('Vhembe District Municipality', 'wp-ultimo-locations'),
	__('Warmbaths', 'wp-ultimo-locations'),
	__('Waterberg District Municipality', 'wp-ultimo-locations'),
);
