<?php // phpcs:ignore - @generation-checksum ZA-MP-26
/**
 * State City List for MP - ZA.
 *
 * City count: 26
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MP - ZA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Balfour', 'wp-ultimo-locations'),
	__('Barberton', 'wp-ultimo-locations'),
	__('Belfast', 'wp-ultimo-locations'),
	__('Bethal', 'wp-ultimo-locations'),
	__('Breyten', 'wp-ultimo-locations'),
	__('Carolina', 'wp-ultimo-locations'),
	__('Delmas', 'wp-ultimo-locations'),
	__('Driefontein', 'wp-ultimo-locations'),
	__('Ehlanzeni District', 'wp-ultimo-locations'),
	__('Ermelo', 'wp-ultimo-locations'),
	__('Gert Sibande District Municipality', 'wp-ultimo-locations'),
	__('Hendrina', 'wp-ultimo-locations'),
	__('Komatipoort', 'wp-ultimo-locations'),
	__('Kriel', 'wp-ultimo-locations'),
	__('Lydenburg', 'wp-ultimo-locations'),
	__('Middelburg', 'wp-ultimo-locations'),
	__('Nelspruit', 'wp-ultimo-locations'),
	__('Nkangala District Municipality', 'wp-ultimo-locations'),
	__('Piet Retief', 'wp-ultimo-locations'),
	__('Secunda', 'wp-ultimo-locations'),
	__('Siyabuswa', 'wp-ultimo-locations'),
	__('Standerton', 'wp-ultimo-locations'),
	__('Volksrust', 'wp-ultimo-locations'),
	__('White River', 'wp-ultimo-locations'),
	__('Witbank', 'wp-ultimo-locations'),
	__('eMbalenhle', 'wp-ultimo-locations'),
);
