<?php // phpcs:ignore - @generation-checksum JP-04-33
/**
 * State City List for 04 - JP.
 *
 * City count: 33
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 04 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Furukawa', 'wp-ultimo-locations'),
	__('Higashimatshushima Shi', 'wp-ultimo-locations'),
	__('Higashimatsushima', 'wp-ultimo-locations'),
	__('Ishinomaki', 'wp-ultimo-locations'),
	__('Ishinomaki Shi', 'wp-ultimo-locations'),
	__('Iwanuma', 'wp-ultimo-locations'),
	__('Iwanuma-shi', 'wp-ultimo-locations'),
	__('Kakuda', 'wp-ultimo-locations'),
	__('Kakuda Shi', 'wp-ultimo-locations'),
	__('Kesennuma', 'wp-ultimo-locations'),
	__('Kesennuma Shi', 'wp-ultimo-locations'),
	__('Kogota', 'wp-ultimo-locations'),
	__('Kurihara', 'wp-ultimo-locations'),
	__('Kurihara Shi', 'wp-ultimo-locations'),
	__('Marumori', 'wp-ultimo-locations'),
	__('Matsushima', 'wp-ultimo-locations'),
	__('Natori Shi', 'wp-ultimo-locations'),
	__('Onagawa Chō', 'wp-ultimo-locations'),
	__('Rifu', 'wp-ultimo-locations'),
	__('Sendai', 'wp-ultimo-locations'),
	__('Shiogama', 'wp-ultimo-locations'),
	__('Shiroishi', 'wp-ultimo-locations'),
	__('Shiroishi Shi', 'wp-ultimo-locations'),
	__('Tagajō Shi', 'wp-ultimo-locations'),
	__('Tome Shi', 'wp-ultimo-locations'),
	__('Tomiya', 'wp-ultimo-locations'),
	__('Wakuya', 'wp-ultimo-locations'),
	__('Watari', 'wp-ultimo-locations'),
	__('Watari-gun', 'wp-ultimo-locations'),
	__('Yamoto', 'wp-ultimo-locations'),
	__('Ōkawara', 'wp-ultimo-locations'),
	__('Ōsaki', 'wp-ultimo-locations'),
	__('Ōsaki Shi', 'wp-ultimo-locations'),
);
