<?php // phpcs:ignore - @generation-checksum JP-06-27
/**
 * State City List for 06 - JP.
 *
 * City count: 27
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 06 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Higashine', 'wp-ultimo-locations'),
	__('Higashine Shi', 'wp-ultimo-locations'),
	__('Kaminoyama', 'wp-ultimo-locations'),
	__('Kaminoyama-shi', 'wp-ultimo-locations'),
	__('Murayama', 'wp-ultimo-locations'),
	__('Murayama Shi', 'wp-ultimo-locations'),
	__('Nagai', 'wp-ultimo-locations'),
	__('Nagai-shi', 'wp-ultimo-locations'),
	__('Nanyō Shi', 'wp-ultimo-locations'),
	__('Obanazawa', 'wp-ultimo-locations'),
	__('Obanazawa Shi', 'wp-ultimo-locations'),
	__('Sagae', 'wp-ultimo-locations'),
	__('Sagae-shi', 'wp-ultimo-locations'),
	__('Sakata', 'wp-ultimo-locations'),
	__('Sakata Shi', 'wp-ultimo-locations'),
	__('Shinjō', 'wp-ultimo-locations'),
	__('Shinjō Shi', 'wp-ultimo-locations'),
	__('Takahata', 'wp-ultimo-locations'),
	__('Tendō', 'wp-ultimo-locations'),
	__('Tendō Shi', 'wp-ultimo-locations'),
	__('Tsuruoka', 'wp-ultimo-locations'),
	__('Tsuruoka Shi', 'wp-ultimo-locations'),
	__('Yamagata', 'wp-ultimo-locations'),
	__('Yamagata Shi', 'wp-ultimo-locations'),
	__('Yonezawa', 'wp-ultimo-locations'),
	__('Yonezawa Shi', 'wp-ultimo-locations'),
	__('Yuza', 'wp-ultimo-locations'),
);
