<?php // phpcs:ignore - @generation-checksum JP-09-33
/**
 * State City List for 09 - JP.
 *
 * City count: 33
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 09 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ashikaga', 'wp-ultimo-locations'),
	__('Fujioka', 'wp-ultimo-locations'),
	__('Imaichi', 'wp-ultimo-locations'),
	__('Kaminokawa', 'wp-ultimo-locations'),
	__('Kanuma', 'wp-ultimo-locations'),
	__('Kanuma-shi', 'wp-ultimo-locations'),
	__('Karasuyama', 'wp-ultimo-locations'),
	__('Kuroiso', 'wp-ultimo-locations'),
	__('Mashiko', 'wp-ultimo-locations'),
	__('Mibu', 'wp-ultimo-locations'),
	__('Mooka', 'wp-ultimo-locations'),
	__('Mooka-shi', 'wp-ultimo-locations'),
	__('Motegi', 'wp-ultimo-locations'),
	__('Nasukarasuyama', 'wp-ultimo-locations'),
	__('Nasukarasuyama-shi', 'wp-ultimo-locations'),
	__('Nasushiobara-shi', 'wp-ultimo-locations'),
	__('Nikko-shi', 'wp-ultimo-locations'),
	__('Nikkō', 'wp-ultimo-locations'),
	__('Oyama', 'wp-ultimo-locations'),
	__('Oyama-shi', 'wp-ultimo-locations'),
	__('Sakura-shi', 'wp-ultimo-locations'),
	__('Sano', 'wp-ultimo-locations'),
	__('Sano-shi', 'wp-ultimo-locations'),
	__('Shimotsuke-shi', 'wp-ultimo-locations'),
	__('Tanuma', 'wp-ultimo-locations'),
	__('Tochigi-shi', 'wp-ultimo-locations'),
	__('Ujiie', 'wp-ultimo-locations'),
	__('Utsunomiya', 'wp-ultimo-locations'),
	__('Utsunomiya-shi', 'wp-ultimo-locations'),
	__('Yaita', 'wp-ultimo-locations'),
	__('Yaita-shi', 'wp-ultimo-locations'),
	__('Ōtawara', 'wp-ultimo-locations'),
	__('Ōtawara-shi', 'wp-ultimo-locations'),
);
