<?php // phpcs:ignore - @generation-checksum JP-10-31
/**
 * State City List for 10 - JP.
 *
 * City count: 31
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 10 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Agatsuma-gun', 'wp-ultimo-locations'),
	__('Annaka', 'wp-ultimo-locations'),
	__('Annaka Shi', 'wp-ultimo-locations'),
	__('Fujioka', 'wp-ultimo-locations'),
	__('Fujioka Shi', 'wp-ultimo-locations'),
	__('Isesaki', 'wp-ultimo-locations'),
	__('Isesaki Shi', 'wp-ultimo-locations'),
	__('Kanekomachi', 'wp-ultimo-locations'),
	__('Kiryū', 'wp-ultimo-locations'),
	__('Kiryū Shi', 'wp-ultimo-locations'),
	__('Maebashi', 'wp-ultimo-locations'),
	__('Maebashi Shi', 'wp-ultimo-locations'),
	__('Midori', 'wp-ultimo-locations'),
	__('Midori Shi', 'wp-ultimo-locations'),
	__('Nakanojōmachi', 'wp-ultimo-locations'),
	__('Numata', 'wp-ultimo-locations'),
	__('Numata Shi', 'wp-ultimo-locations'),
	__('Sakai-nakajima', 'wp-ultimo-locations'),
	__('Shibukawa', 'wp-ultimo-locations'),
	__('Shibukawa-shi', 'wp-ultimo-locations'),
	__('Takasaki', 'wp-ultimo-locations'),
	__('Takasaki Shi', 'wp-ultimo-locations'),
	__('Tamamura', 'wp-ultimo-locations'),
	__('Tatebayashi', 'wp-ultimo-locations'),
	__('Tatebayashi-shi', 'wp-ultimo-locations'),
	__('Tomioka', 'wp-ultimo-locations'),
	__('Tomioka-shi', 'wp-ultimo-locations'),
	__('Yoshii', 'wp-ultimo-locations'),
	__('Ōmamachō-ōmama', 'wp-ultimo-locations'),
	__('Ōta', 'wp-ultimo-locations'),
	__('Ōta-shi', 'wp-ultimo-locations'),
);
