<?php // phpcs:ignore - @generation-checksum JP-14-40
/**
 * State City List for 14 - JP.
 *
 * City count: 40
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 14 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Atsugi', 'wp-ultimo-locations'),
	__('Atsugi Shi', 'wp-ultimo-locations'),
	__('Ayase Shi', 'wp-ultimo-locations'),
	__('Chigasaki', 'wp-ultimo-locations'),
	__('Chigasaki Shi', 'wp-ultimo-locations'),
	__('Ebina Shi', 'wp-ultimo-locations'),
	__('Fujisawa', 'wp-ultimo-locations'),
	__('Fujisawa Shi', 'wp-ultimo-locations'),
	__('Hadano', 'wp-ultimo-locations'),
	__('Hadano-shi', 'wp-ultimo-locations'),
	__('Hakone', 'wp-ultimo-locations'),
	__('Hayama', 'wp-ultimo-locations'),
	__('Hiratsuka', 'wp-ultimo-locations'),
	__('Hiratsuka Shi', 'wp-ultimo-locations'),
	__('Isehara', 'wp-ultimo-locations'),
	__('Isehara Shi', 'wp-ultimo-locations'),
	__('Kamakura', 'wp-ultimo-locations'),
	__('Kamakura Shi', 'wp-ultimo-locations'),
	__('Kawasaki', 'wp-ultimo-locations'),
	__('Kawasaki-shi', 'wp-ultimo-locations'),
	__('Minamiashigara', 'wp-ultimo-locations'),
	__('Minamiashigara Shi', 'wp-ultimo-locations'),
	__('Minamirinkan', 'wp-ultimo-locations'),
	__('Miura', 'wp-ultimo-locations'),
	__('Miura Shi', 'wp-ultimo-locations'),
	__('Ninomiya', 'wp-ultimo-locations'),
	__('Odawara', 'wp-ultimo-locations'),
	__('Odawara-shi', 'wp-ultimo-locations'),
	__('Sagamihara-shi', 'wp-ultimo-locations'),
	__('Yamakita', 'wp-ultimo-locations'),
	__('Yamato-shi', 'wp-ultimo-locations'),
	__('Yokohama', 'wp-ultimo-locations'),
	__('Yokohama Shi', 'wp-ultimo-locations'),
	__('Yokosuka', 'wp-ultimo-locations'),
	__('Yokosuka Shi', 'wp-ultimo-locations'),
	__('Yugawara', 'wp-ultimo-locations'),
	__('Zama', 'wp-ultimo-locations'),
	__('Zama Shi', 'wp-ultimo-locations'),
	__('Zushi Shi', 'wp-ultimo-locations'),
	__('Ōiso', 'wp-ultimo-locations'),
);
