<?php // phpcs:ignore - @generation-checksum JP-20-40
/**
 * State City List for 20 - JP.
 *
 * City count: 40
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 20 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Azumino-Shi', 'wp-ultimo-locations'),
	__('Chikuma Shi', 'wp-ultimo-locations'),
	__('Chino', 'wp-ultimo-locations'),
	__('Chino Shi', 'wp-ultimo-locations'),
	__('Hakuba', 'wp-ultimo-locations'),
	__('Hotaka', 'wp-ultimo-locations'),
	__('Iida', 'wp-ultimo-locations'),
	__('Iida-shi', 'wp-ultimo-locations'),
	__('Iiyama', 'wp-ultimo-locations'),
	__('Iiyama Shi', 'wp-ultimo-locations'),
	__('Ina', 'wp-ultimo-locations'),
	__('Ina-shi', 'wp-ultimo-locations'),
	__('Kamimaruko', 'wp-ultimo-locations'),
	__('Komagane', 'wp-ultimo-locations'),
	__('Komagane-shi', 'wp-ultimo-locations'),
	__('Komoro', 'wp-ultimo-locations'),
	__('Komoro Shi', 'wp-ultimo-locations'),
	__('Matsumoto', 'wp-ultimo-locations'),
	__('Matsumoto Shi', 'wp-ultimo-locations'),
	__('Nagano', 'wp-ultimo-locations'),
	__('Nagano Shi', 'wp-ultimo-locations'),
	__('Nakano Shi', 'wp-ultimo-locations'),
	__('Okaya', 'wp-ultimo-locations'),
	__('Okaya Shi', 'wp-ultimo-locations'),
	__('Saku', 'wp-ultimo-locations'),
	__('Saku Shi', 'wp-ultimo-locations'),
	__('Shiojiri', 'wp-ultimo-locations'),
	__('Shiojiri-shi', 'wp-ultimo-locations'),
	__('Suwa', 'wp-ultimo-locations'),
	__('Suwa Shi', 'wp-ultimo-locations'),
	__('Suzaka', 'wp-ultimo-locations'),
	__('Suzaka-shi', 'wp-ultimo-locations'),
	__('Tatsuno', 'wp-ultimo-locations'),
	__('Toyoshina', 'wp-ultimo-locations'),
	__('Tōmi', 'wp-ultimo-locations'),
	__('Tōmi Shi', 'wp-ultimo-locations'),
	__('Ueda', 'wp-ultimo-locations'),
	__('Ueda Shi', 'wp-ultimo-locations'),
	__('Ōmachi', 'wp-ultimo-locations'),
	__('Ōmachi-shi', 'wp-ultimo-locations'),
);
