<?php // phpcs:ignore - @generation-checksum JP-21-35
/**
 * State City List for 21 - JP.
 *
 * City count: 35
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 21 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ena-shi', 'wp-ultimo-locations'),
	__('Gero', 'wp-ultimo-locations'),
	__('Gero-shi', 'wp-ultimo-locations'),
	__('Gifu-shi', 'wp-ultimo-locations'),
	__('Gujō', 'wp-ultimo-locations'),
	__('Gujō-shi', 'wp-ultimo-locations'),
	__('Gōdo', 'wp-ultimo-locations'),
	__('Hashima', 'wp-ultimo-locations'),
	__('Hashima-shi', 'wp-ultimo-locations'),
	__('Hida', 'wp-ultimo-locations'),
	__('Hida Shi', 'wp-ultimo-locations'),
	__('Kaizu-shi', 'wp-ultimo-locations'),
	__('Kakamigahara-shi', 'wp-ultimo-locations'),
	__('Kani-shi', 'wp-ultimo-locations'),
	__('Kasamatsuchō', 'wp-ultimo-locations'),
	__('Mino', 'wp-ultimo-locations'),
	__('Mino-shi', 'wp-ultimo-locations'),
	__('Minokamo', 'wp-ultimo-locations'),
	__('Minokamo-shi', 'wp-ultimo-locations'),
	__('Mitake', 'wp-ultimo-locations'),
	__('Mizuho-shi', 'wp-ultimo-locations'),
	__('Mizunami', 'wp-ultimo-locations'),
	__('Mizunami-shi', 'wp-ultimo-locations'),
	__('Motosu-shi', 'wp-ultimo-locations'),
	__('Nakatsugawa', 'wp-ultimo-locations'),
	__('Nakatsugawa-shi', 'wp-ultimo-locations'),
	__('Seki-shi', 'wp-ultimo-locations'),
	__('Tajimi', 'wp-ultimo-locations'),
	__('Tajimi-shi', 'wp-ultimo-locations'),
	__('Takayama Shi', 'wp-ultimo-locations'),
	__('Tarui', 'wp-ultimo-locations'),
	__('Toki', 'wp-ultimo-locations'),
	__('Toki-shi', 'wp-ultimo-locations'),
	__('Yamagata-shi', 'wp-ultimo-locations'),
	__('Ōgaki-shi', 'wp-ultimo-locations'),
);
