<?php // phpcs:ignore - @generation-checksum JP-22-44
/**
 * State City List for 22 - JP.
 *
 * City count: 44
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 22 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Atami', 'wp-ultimo-locations'),
	__('Atami-shi', 'wp-ultimo-locations'),
	__('Fuji Shi', 'wp-ultimo-locations'),
	__('Fujieda Shi', 'wp-ultimo-locations'),
	__('Fujinomiya', 'wp-ultimo-locations'),
	__('Fujinomiya Shi', 'wp-ultimo-locations'),
	__('Fukuroi', 'wp-ultimo-locations'),
	__('Fukuroi-shi', 'wp-ultimo-locations'),
	__('Gotenba Shi', 'wp-ultimo-locations'),
	__('Hamakita', 'wp-ultimo-locations'),
	__('Hamamatsu', 'wp-ultimo-locations'),
	__('Hamamatsu-shi', 'wp-ultimo-locations'),
	__('Heda', 'wp-ultimo-locations'),
	__('Itō', 'wp-ultimo-locations'),
	__('Itō Shi', 'wp-ultimo-locations'),
	__('Iwata', 'wp-ultimo-locations'),
	__('Iwata-shi', 'wp-ultimo-locations'),
	__('Izu', 'wp-ultimo-locations'),
	__('Izu-shi', 'wp-ultimo-locations'),
	__('Izunokuni-shi', 'wp-ultimo-locations'),
	__('Kakegawa', 'wp-ultimo-locations'),
	__('Kakegawa Shi', 'wp-ultimo-locations'),
	__('Kanaya', 'wp-ultimo-locations'),
	__('Kikugawa-shi', 'wp-ultimo-locations'),
	__('Kosai', 'wp-ultimo-locations'),
	__('Kosai-shi', 'wp-ultimo-locations'),
	__('Makinohara Shi', 'wp-ultimo-locations'),
	__('Mishima', 'wp-ultimo-locations'),
	__('Mishima Shi', 'wp-ultimo-locations'),
	__('Mori', 'wp-ultimo-locations'),
	__('Numazu-shi', 'wp-ultimo-locations'),
	__('Omaezaki-shi', 'wp-ultimo-locations'),
	__('Sagara', 'wp-ultimo-locations'),
	__('Shimada', 'wp-ultimo-locations'),
	__('Shimada-shi', 'wp-ultimo-locations'),
	__('Shimoda', 'wp-ultimo-locations'),
	__('Shimoda-shi', 'wp-ultimo-locations'),
	__('Shizuoka', 'wp-ultimo-locations'),
	__('Shizuoka-shi', 'wp-ultimo-locations'),
	__('Susono', 'wp-ultimo-locations'),
	__('Susono Shi', 'wp-ultimo-locations'),
	__('Yaizu', 'wp-ultimo-locations'),
	__('Yaizu Shi', 'wp-ultimo-locations'),
	__('Ōyama', 'wp-ultimo-locations'),
);
