<?php // phpcs:ignore - @generation-checksum JP-26-24
/**
 * State City List for 26 - JP.
 *
 * City count: 24
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 26 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Arashiyama', 'wp-ultimo-locations'),
	__('Ayabe', 'wp-ultimo-locations'),
	__('Ayabe-shi', 'wp-ultimo-locations'),
	__('Fukuchiyama-shi', 'wp-ultimo-locations'),
	__('Jōyō Shi', 'wp-ultimo-locations'),
	__('Kameoka', 'wp-ultimo-locations'),
	__('Kameoka-shi', 'wp-ultimo-locations'),
	__('Kamigyō-ku', 'wp-ultimo-locations'),
	__('Kizugawa-shi', 'wp-ultimo-locations'),
	__('Kyoto', 'wp-ultimo-locations'),
	__('Kyōtanabe Shi', 'wp-ultimo-locations'),
	__('Kyōtango-shi', 'wp-ultimo-locations'),
	__('Maizuru', 'wp-ultimo-locations'),
	__('Maizuru-shi', 'wp-ultimo-locations'),
	__('Miyazu', 'wp-ultimo-locations'),
	__('Miyazu-shi', 'wp-ultimo-locations'),
	__('Mukō Shi', 'wp-ultimo-locations'),
	__('Nagaokakyō Shi', 'wp-ultimo-locations'),
	__('Nantan-shi', 'wp-ultimo-locations'),
	__('Tanabe', 'wp-ultimo-locations'),
	__('Uji', 'wp-ultimo-locations'),
	__('Uji Shi', 'wp-ultimo-locations'),
	__('Yawata', 'wp-ultimo-locations'),
	__('Yawata Shi', 'wp-ultimo-locations'),
);
