<?php // phpcs:ignore - @generation-checksum JP-31-5
/**
 * State City List for 31 - JP.
 *
 * City count: 5
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 31 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Kurayoshi-shi', 'wp-ultimo-locations'),
	__('Sakaiminato', 'wp-ultimo-locations'),
	__('Sakaiminato Shi', 'wp-ultimo-locations'),
	__('Tottori-shi', 'wp-ultimo-locations'),
	__('Yonago Shi', 'wp-ultimo-locations'),
);
