<?php // phpcs:ignore - @generation-checksum JP-32-16
/**
 * State City List for 32 - JP.
 *
 * City count: 16
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 32 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Gōtsu Shi', 'wp-ultimo-locations'),
	__('Gōtsuchō', 'wp-ultimo-locations'),
	__('Hamada', 'wp-ultimo-locations'),
	__('Hamada Shi', 'wp-ultimo-locations'),
	__('Hiratachō', 'wp-ultimo-locations'),
	__('Izumo', 'wp-ultimo-locations'),
	__('Izumo Shi', 'wp-ultimo-locations'),
	__('Masuda', 'wp-ultimo-locations'),
	__('Masuda Shi', 'wp-ultimo-locations'),
	__('Matsue', 'wp-ultimo-locations'),
	__('Matsue Shi', 'wp-ultimo-locations'),
	__('Unnan Shi', 'wp-ultimo-locations'),
	__('Yasugi Shi', 'wp-ultimo-locations'),
	__('Yasugichō', 'wp-ultimo-locations'),
	__('Ōda Shi', 'wp-ultimo-locations'),
	__('Ōdachō-ōda', 'wp-ultimo-locations'),
);
