<?php // phpcs:ignore - @generation-checksum JP-35-21
/**
 * State City List for 35 - JP.
 *
 * City count: 21
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 35 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Hagi', 'wp-ultimo-locations'),
	__('Hagi Shi', 'wp-ultimo-locations'),
	__('Hikari', 'wp-ultimo-locations'),
	__('Hikari Shi', 'wp-ultimo-locations'),
	__('Hofu Shi', 'wp-ultimo-locations'),
	__('Hōfu', 'wp-ultimo-locations'),
	__('Iwakuni Shi', 'wp-ultimo-locations'),
	__('Kudamatsu', 'wp-ultimo-locations'),
	__('Kudamatsu Shi', 'wp-ultimo-locations'),
	__('Mine Shi', 'wp-ultimo-locations'),
	__('Nagato', 'wp-ultimo-locations'),
	__('Nagato Shi', 'wp-ultimo-locations'),
	__('Ogōri-shimogō', 'wp-ultimo-locations'),
	__('Onoda', 'wp-ultimo-locations'),
	__('Sanyōonoda Shi', 'wp-ultimo-locations'),
	__('Shimonoseki Shi', 'wp-ultimo-locations'),
	__('Shūnan Shi', 'wp-ultimo-locations'),
	__('Tokuyama', 'wp-ultimo-locations'),
	__('Ube', 'wp-ultimo-locations'),
	__('Yamaguchi Shi', 'wp-ultimo-locations'),
	__('Yanai Shi', 'wp-ultimo-locations'),
);
