<?php // phpcs:ignore - @generation-checksum JP-41-16
/**
 * State City List for 41 - JP.
 *
 * City count: 16
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 41 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Imari Shi', 'wp-ultimo-locations'),
	__('Imarichō-kō', 'wp-ultimo-locations'),
	__('Kanzaki Shi', 'wp-ultimo-locations'),
	__('Karatsu', 'wp-ultimo-locations'),
	__('Karatsu Shi', 'wp-ultimo-locations'),
	__('Kashima', 'wp-ultimo-locations'),
	__('Kashima Shi', 'wp-ultimo-locations'),
	__('Miyaki-gun', 'wp-ultimo-locations'),
	__('Ogi-shi', 'wp-ultimo-locations'),
	__('Saga', 'wp-ultimo-locations'),
	__('Saga Shi', 'wp-ultimo-locations'),
	__('Takeo Shi', 'wp-ultimo-locations'),
	__('Takeochō-takeo', 'wp-ultimo-locations'),
	__('Taku Shi', 'wp-ultimo-locations'),
	__('Tosu Shi', 'wp-ultimo-locations'),
	__('Ureshino Shi', 'wp-ultimo-locations'),
);
