<?php // phpcs:ignore - @generation-checksum JP-44-26
/**
 * State City List for 44 - JP.
 *
 * City count: 26
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 44 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Beppu', 'wp-ultimo-locations'),
	__('Beppu Shi', 'wp-ultimo-locations'),
	__('Bungo-Takada-shi', 'wp-ultimo-locations'),
	__('Bungo-ōno Shi', 'wp-ultimo-locations'),
	__('Hiji', 'wp-ultimo-locations'),
	__('Hita', 'wp-ultimo-locations'),
	__('Hita Shi', 'wp-ultimo-locations'),
	__('Kitsuki', 'wp-ultimo-locations'),
	__('Kitsuki Shi', 'wp-ultimo-locations'),
	__('Kunisaki-shi', 'wp-ultimo-locations'),
	__('Nakatsu', 'wp-ultimo-locations'),
	__('Nakatsu Shi', 'wp-ultimo-locations'),
	__('Saiki', 'wp-ultimo-locations'),
	__('Saiki-shi', 'wp-ultimo-locations'),
	__('Takedamachi', 'wp-ultimo-locations'),
	__('Taketa-shi', 'wp-ultimo-locations'),
	__('Tsukawaki', 'wp-ultimo-locations'),
	__('Tsukumi-shi', 'wp-ultimo-locations'),
	__('Tsukumiura', 'wp-ultimo-locations'),
	__('Tsurusaki', 'wp-ultimo-locations'),
	__('Usa Shi', 'wp-ultimo-locations'),
	__('Usuki', 'wp-ultimo-locations'),
	__('Usuki Shi', 'wp-ultimo-locations'),
	__('Yufu-shi', 'wp-ultimo-locations'),
	__('Ōita', 'wp-ultimo-locations'),
	__('Ōita-shi', 'wp-ultimo-locations'),
);
