<?php // phpcs:ignore - @generation-checksum JP-45-17
/**
 * State City List for 45 - JP.
 *
 * City count: 17
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 45 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ebino-shi', 'wp-ultimo-locations'),
	__('Hyūga-shi', 'wp-ultimo-locations'),
	__('Kobayashi', 'wp-ultimo-locations'),
	__('Kobayashi Shi', 'wp-ultimo-locations'),
	__('Kushima', 'wp-ultimo-locations'),
	__('Kushima Shi', 'wp-ultimo-locations'),
	__('Miyakonojō', 'wp-ultimo-locations'),
	__('Miyakonojō Shi', 'wp-ultimo-locations'),
	__('Miyazaki', 'wp-ultimo-locations'),
	__('Miyazaki-shi', 'wp-ultimo-locations'),
	__('Nichinan', 'wp-ultimo-locations'),
	__('Nichinan Shi', 'wp-ultimo-locations'),
	__('Nobeoka', 'wp-ultimo-locations'),
	__('Nobeoka-shi', 'wp-ultimo-locations'),
	__('Saito-shi', 'wp-ultimo-locations'),
	__('Takanabe', 'wp-ultimo-locations'),
	__('Tsuma', 'wp-ultimo-locations'),
);
