<?php // phpcs:ignore - @generation-checksum JP-46-46
/**
 * State City List for 46 - JP.
 *
 * City count: 46
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 46 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aira Shi', 'wp-ultimo-locations'),
	__('Akune', 'wp-ultimo-locations'),
	__('Akune Shi', 'wp-ultimo-locations'),
	__('Amami', 'wp-ultimo-locations'),
	__('Amami Shi', 'wp-ultimo-locations'),
	__('Hamanoichi', 'wp-ultimo-locations'),
	__('Hioki', 'wp-ultimo-locations'),
	__('Hioki Shi', 'wp-ultimo-locations'),
	__('Ibusuki', 'wp-ultimo-locations'),
	__('Ibusuki Shi', 'wp-ultimo-locations'),
	__('Ichikikushikino Shi', 'wp-ultimo-locations'),
	__('Ijūin', 'wp-ultimo-locations'),
	__('Isa Shi', 'wp-ultimo-locations'),
	__('Izumi', 'wp-ultimo-locations'),
	__('Izumi Shi', 'wp-ultimo-locations'),
	__('Kagoshima', 'wp-ultimo-locations'),
	__('Kagoshima Shi', 'wp-ultimo-locations'),
	__('Kajiki', 'wp-ultimo-locations'),
	__('Kanoya', 'wp-ultimo-locations'),
	__('Kanoya Shi', 'wp-ultimo-locations'),
	__('Kaseda-shirakame', 'wp-ultimo-locations'),
	__('Kirishima Shi', 'wp-ultimo-locations'),
	__('Kokubu-matsuki', 'wp-ultimo-locations'),
	__('Koseda', 'wp-ultimo-locations'),
	__('Koshima', 'wp-ultimo-locations'),
	__('Kurio', 'wp-ultimo-locations'),
	__('Kushikino', 'wp-ultimo-locations'),
	__('Makurazaki', 'wp-ultimo-locations'),
	__('Makurazaki Shi', 'wp-ultimo-locations'),
	__('Minamikyushu Shi', 'wp-ultimo-locations'),
	__('Minamisatsuma Shi', 'wp-ultimo-locations'),
	__('Miyanoura', 'wp-ultimo-locations'),
	__('Nagata', 'wp-ultimo-locations'),
	__('Naze', 'wp-ultimo-locations'),
	__('Nishinoomote', 'wp-ultimo-locations'),
	__('Nishinoomote Shi', 'wp-ultimo-locations'),
	__('Satsumasendai', 'wp-ultimo-locations'),
	__('Satsumasendai Shi', 'wp-ultimo-locations'),
	__('Shibushi', 'wp-ultimo-locations'),
	__('Shibushi-shi', 'wp-ultimo-locations'),
	__('Soo Shi', 'wp-ultimo-locations'),
	__('Sueyoshichō-ninokata', 'wp-ultimo-locations'),
	__('Tarumizu', 'wp-ultimo-locations'),
	__('Tarumizu Shi', 'wp-ultimo-locations'),
	__('Yudomari', 'wp-ultimo-locations'),
	__('Ōkuchi-shinohara', 'wp-ultimo-locations'),
);
