<?php // phpcs:ignore - @generation-checksum JP-47-25
/**
 * State City List for 47 - JP.
 *
 * City count: 25
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 47 - JP.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Chatan', 'wp-ultimo-locations'),
	__('Ginowan Shi', 'wp-ultimo-locations'),
	__('Gushikawa', 'wp-ultimo-locations'),
	__('Hirara', 'wp-ultimo-locations'),
	__('Ishigaki', 'wp-ultimo-locations'),
	__('Ishigaki-shi', 'wp-ultimo-locations'),
	__('Ishikawa', 'wp-ultimo-locations'),
	__('Itoman', 'wp-ultimo-locations'),
	__('Itoman Shi', 'wp-ultimo-locations'),
	__('Katsuren-haebaru', 'wp-ultimo-locations'),
	__('Miyakojima Shi', 'wp-ultimo-locations'),
	__('Nago', 'wp-ultimo-locations'),
	__('Nago Shi', 'wp-ultimo-locations'),
	__('Naha', 'wp-ultimo-locations'),
	__('Naha Shi', 'wp-ultimo-locations'),
	__('Nakagami-gun', 'wp-ultimo-locations'),
	__('Nanjō', 'wp-ultimo-locations'),
	__('Nanjō Shi', 'wp-ultimo-locations'),
	__('Okinawa', 'wp-ultimo-locations'),
	__('Okinawa Shi', 'wp-ultimo-locations'),
	__('Tomigusuku', 'wp-ultimo-locations'),
	__('Tomigusuku-shi', 'wp-ultimo-locations'),
	__('Urasoe Shi', 'wp-ultimo-locations'),
	__('Uruma Shi', 'wp-ultimo-locations'),
	__('Yonakuni', 'wp-ultimo-locations'),
);
