<?php // phpcs:ignore - @generation-checksum CA-NT-7
/**
 * State City List for NT - CA.
 *
 * City count: 7
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for NT - CA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Behchokǫ̀', 'wp-ultimo-locations'),
	__('Fort McPherson', 'wp-ultimo-locations'),
	__('Fort Smith', 'wp-ultimo-locations'),
	__('Hay River', 'wp-ultimo-locations'),
	__('Inuvik', 'wp-ultimo-locations'),
	__('Norman Wells', 'wp-ultimo-locations'),
	__('Yellowknife', 'wp-ultimo-locations'),
);
