<?php // phpcs:ignore - @generation-checksum CA-YT-4
/**
 * State City List for YT - CA.
 *
 * City count: 4
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for YT - CA.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Dawson City', 'wp-ultimo-locations'),
	__('Haines Junction', 'wp-ultimo-locations'),
	__('Watson Lake', 'wp-ultimo-locations'),
	__('Whitehorse', 'wp-ultimo-locations'),
);
