<?php

// scoper-autoload.php @generated by PhpScoper

// Backup the autoloaded Composer files
if (isset($GLOBALS['__composer_autoload_files'])) {
    $existingComposerAutoloadFiles = $GLOBALS['__composer_autoload_files'];
}

$loader = require_once __DIR__.'/autoload.php';
// Ensure InstalledVersions is available
$installedVersionsPath = __DIR__.'/composer/InstalledVersions.php';
if (file_exists($installedVersionsPath)) require_once $installedVersionsPath;

// Restore the backup
if (isset($existingComposerAutoloadFiles)) {
    $GLOBALS['__composer_autoload_files'] = $existingComposerAutoloadFiles;
} else {
    unset($GLOBALS['__composer_autoload_files']);
}

// Class aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#class-aliases
if (!function_exists('humbug_phpscoper_expose_class')) {
    function humbug_phpscoper_expose_class(string $exposed, string $prefixed): void {
        if (!class_exists($exposed, false) && !interface_exists($exposed, false) && !trait_exists($exposed, false)) {
            spl_autoload_call($prefixed);
        }
    }
}
humbug_phpscoper_expose_class('CURLStringFile', 'WP_Ultimo\Dependencies\CURLStringFile');
humbug_phpscoper_expose_class('ReturnTypeWillChange', 'WP_Ultimo\Dependencies\ReturnTypeWillChange');
humbug_phpscoper_expose_class('JsonException', 'WP_Ultimo\Dependencies\JsonException');
humbug_phpscoper_expose_class('Attribute', 'WP_Ultimo\Dependencies\Attribute');
humbug_phpscoper_expose_class('UnhandledMatchError', 'WP_Ultimo\Dependencies\UnhandledMatchError');
humbug_phpscoper_expose_class('PhpToken', 'WP_Ultimo\Dependencies\PhpToken');
humbug_phpscoper_expose_class('Stringable', 'WP_Ultimo\Dependencies\Stringable');
humbug_phpscoper_expose_class('ValueError', 'WP_Ultimo\Dependencies\ValueError');

// Function aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#function-aliases
if (!function_exists('array_is_list')) { function array_is_list() { return \WP_Ultimo\Dependencies\array_is_list(...func_get_args()); } }
if (!function_exists('array_key_first')) { function array_key_first() { return \WP_Ultimo\Dependencies\array_key_first(...func_get_args()); } }
if (!function_exists('array_key_last')) { function array_key_last() { return \WP_Ultimo\Dependencies\array_key_last(...func_get_args()); } }
if (!function_exists('enum_exists')) { function enum_exists() { return \WP_Ultimo\Dependencies\enum_exists(...func_get_args()); } }
if (!function_exists('fdiv')) { function fdiv() { return \WP_Ultimo\Dependencies\fdiv(...func_get_args()); } }
if (!function_exists('get_debug_type')) { function get_debug_type() { return \WP_Ultimo\Dependencies\get_debug_type(...func_get_args()); } }
if (!function_exists('get_resource_id')) { function get_resource_id() { return \WP_Ultimo\Dependencies\get_resource_id(...func_get_args()); } }
if (!function_exists('getallheaders')) { function getallheaders() { return \WP_Ultimo\Dependencies\getallheaders(...func_get_args()); } }
if (!function_exists('hrtime')) { function hrtime() { return \WP_Ultimo\Dependencies\hrtime(...func_get_args()); } }
if (!function_exists('is_countable')) { function is_countable() { return \WP_Ultimo\Dependencies\is_countable(...func_get_args()); } }
if (!function_exists('mb_check_encoding')) { function mb_check_encoding() { return \WP_Ultimo\Dependencies\mb_check_encoding(...func_get_args()); } }
if (!function_exists('mb_chr')) { function mb_chr() { return \WP_Ultimo\Dependencies\mb_chr(...func_get_args()); } }
if (!function_exists('mb_convert_case')) { function mb_convert_case() { return \WP_Ultimo\Dependencies\mb_convert_case(...func_get_args()); } }
if (!function_exists('mb_convert_encoding')) { function mb_convert_encoding() { return \WP_Ultimo\Dependencies\mb_convert_encoding(...func_get_args()); } }
if (!function_exists('mb_convert_variables')) { function mb_convert_variables() { return \WP_Ultimo\Dependencies\mb_convert_variables(...func_get_args()); } }
if (!function_exists('mb_decode_mimeheader')) { function mb_decode_mimeheader() { return \WP_Ultimo\Dependencies\mb_decode_mimeheader(...func_get_args()); } }
if (!function_exists('mb_decode_numericentity')) { function mb_decode_numericentity() { return \WP_Ultimo\Dependencies\mb_decode_numericentity(...func_get_args()); } }
if (!function_exists('mb_detect_encoding')) { function mb_detect_encoding() { return \WP_Ultimo\Dependencies\mb_detect_encoding(...func_get_args()); } }
if (!function_exists('mb_detect_order')) { function mb_detect_order() { return \WP_Ultimo\Dependencies\mb_detect_order(...func_get_args()); } }
if (!function_exists('mb_encode_mimeheader')) { function mb_encode_mimeheader() { return \WP_Ultimo\Dependencies\mb_encode_mimeheader(...func_get_args()); } }
if (!function_exists('mb_encode_numericentity')) { function mb_encode_numericentity() { return \WP_Ultimo\Dependencies\mb_encode_numericentity(...func_get_args()); } }
if (!function_exists('mb_encoding_aliases')) { function mb_encoding_aliases() { return \WP_Ultimo\Dependencies\mb_encoding_aliases(...func_get_args()); } }
if (!function_exists('mb_get_info')) { function mb_get_info() { return \WP_Ultimo\Dependencies\mb_get_info(...func_get_args()); } }
if (!function_exists('mb_http_input')) { function mb_http_input() { return \WP_Ultimo\Dependencies\mb_http_input(...func_get_args()); } }
if (!function_exists('mb_http_output')) { function mb_http_output() { return \WP_Ultimo\Dependencies\mb_http_output(...func_get_args()); } }
if (!function_exists('mb_internal_encoding')) { function mb_internal_encoding() { return \WP_Ultimo\Dependencies\mb_internal_encoding(...func_get_args()); } }
if (!function_exists('mb_language')) { function mb_language() { return \WP_Ultimo\Dependencies\mb_language(...func_get_args()); } }
if (!function_exists('mb_list_encodings')) { function mb_list_encodings() { return \WP_Ultimo\Dependencies\mb_list_encodings(...func_get_args()); } }
if (!function_exists('mb_ord')) { function mb_ord() { return \WP_Ultimo\Dependencies\mb_ord(...func_get_args()); } }
if (!function_exists('mb_output_handler')) { function mb_output_handler() { return \WP_Ultimo\Dependencies\mb_output_handler(...func_get_args()); } }
if (!function_exists('mb_parse_str')) { function mb_parse_str() { return \WP_Ultimo\Dependencies\mb_parse_str(...func_get_args()); } }
if (!function_exists('mb_scrub')) { function mb_scrub() { return \WP_Ultimo\Dependencies\mb_scrub(...func_get_args()); } }
if (!function_exists('mb_str_split')) { function mb_str_split() { return \WP_Ultimo\Dependencies\mb_str_split(...func_get_args()); } }
if (!function_exists('mb_stripos')) { function mb_stripos() { return \WP_Ultimo\Dependencies\mb_stripos(...func_get_args()); } }
if (!function_exists('mb_stristr')) { function mb_stristr() { return \WP_Ultimo\Dependencies\mb_stristr(...func_get_args()); } }
if (!function_exists('mb_strlen')) { function mb_strlen() { return \WP_Ultimo\Dependencies\mb_strlen(...func_get_args()); } }
if (!function_exists('mb_strpos')) { function mb_strpos() { return \WP_Ultimo\Dependencies\mb_strpos(...func_get_args()); } }
if (!function_exists('mb_strrchr')) { function mb_strrchr() { return \WP_Ultimo\Dependencies\mb_strrchr(...func_get_args()); } }
if (!function_exists('mb_strrichr')) { function mb_strrichr() { return \WP_Ultimo\Dependencies\mb_strrichr(...func_get_args()); } }
if (!function_exists('mb_strripos')) { function mb_strripos() { return \WP_Ultimo\Dependencies\mb_strripos(...func_get_args()); } }
if (!function_exists('mb_strrpos')) { function mb_strrpos() { return \WP_Ultimo\Dependencies\mb_strrpos(...func_get_args()); } }
if (!function_exists('mb_strstr')) { function mb_strstr() { return \WP_Ultimo\Dependencies\mb_strstr(...func_get_args()); } }
if (!function_exists('mb_strtolower')) { function mb_strtolower() { return \WP_Ultimo\Dependencies\mb_strtolower(...func_get_args()); } }
if (!function_exists('mb_strtoupper')) { function mb_strtoupper() { return \WP_Ultimo\Dependencies\mb_strtoupper(...func_get_args()); } }
if (!function_exists('mb_strwidth')) { function mb_strwidth() { return \WP_Ultimo\Dependencies\mb_strwidth(...func_get_args()); } }
if (!function_exists('mb_substitute_character')) { function mb_substitute_character() { return \WP_Ultimo\Dependencies\mb_substitute_character(...func_get_args()); } }
if (!function_exists('mb_substr')) { function mb_substr() { return \WP_Ultimo\Dependencies\mb_substr(...func_get_args()); } }
if (!function_exists('mb_substr_count')) { function mb_substr_count() { return \WP_Ultimo\Dependencies\mb_substr_count(...func_get_args()); } }
if (!function_exists('preg_last_error_msg')) { function preg_last_error_msg() { return \WP_Ultimo\Dependencies\preg_last_error_msg(...func_get_args()); } }
if (!function_exists('str_contains')) { function str_contains() { return \WP_Ultimo\Dependencies\str_contains(...func_get_args()); } }
if (!function_exists('str_ends_with')) { function str_ends_with() { return \WP_Ultimo\Dependencies\str_ends_with(...func_get_args()); } }
if (!function_exists('str_starts_with')) { function str_starts_with() { return \WP_Ultimo\Dependencies\str_starts_with(...func_get_args()); } }

return $loader;
