<?php // phpcs:ignore - @generation-checksum NL-DR-76
/**
 * State City List for DR - NL.
 *
 * City count: 76
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for DR - NL.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aalden', 'wp-ultimo-locations'),
	__('Angelslo', 'wp-ultimo-locations'),
	__('Annen', 'wp-ultimo-locations'),
	__('Assen', 'wp-ultimo-locations'),
	__('Ballast', 'wp-ultimo-locations'),
	__('Barger-Oosterveld', 'wp-ultimo-locations'),
	__('Bargeres', 'wp-ultimo-locations'),
	__('Beilen', 'wp-ultimo-locations'),
	__('Borger', 'wp-ultimo-locations'),
	__('Coevorden', 'wp-ultimo-locations'),
	__('Dalen', 'wp-ultimo-locations'),
	__('De Loo', 'wp-ultimo-locations'),
	__('De Wijk', 'wp-ultimo-locations'),
	__('Diever', 'wp-ultimo-locations'),
	__('Dwingeloo', 'wp-ultimo-locations'),
	__('Eelde', 'wp-ultimo-locations'),
	__('Eext', 'wp-ultimo-locations'),
	__('Emmen', 'wp-ultimo-locations'),
	__('Emmer-Compascuum', 'wp-ultimo-locations'),
	__('Emmer-Erfscheidenveen', 'wp-ultimo-locations'),
	__('Emmerhout', 'wp-ultimo-locations'),
	__('Emmermeer', 'wp-ultimo-locations'),
	__('Emmerschans', 'wp-ultimo-locations'),
	__('Exloo', 'wp-ultimo-locations'),
	__('Gasselte', 'wp-ultimo-locations'),
	__('Gasselternijveen', 'wp-ultimo-locations'),
	__('Gemeente Aa en Hunze', 'wp-ultimo-locations'),
	__('Gemeente Assen', 'wp-ultimo-locations'),
	__('Gemeente Borger-Odoorn', 'wp-ultimo-locations'),
	__('Gemeente Coevorden', 'wp-ultimo-locations'),
	__('Gemeente De Wolden', 'wp-ultimo-locations'),
	__('Gemeente Emmen', 'wp-ultimo-locations'),
	__('Gemeente Hoogeveen', 'wp-ultimo-locations'),
	__('Gemeente Meppel', 'wp-ultimo-locations'),
	__('Gemeente Midden-Drenthe', 'wp-ultimo-locations'),
	__('Gemeente Noordenveld', 'wp-ultimo-locations'),
	__('Gemeente Tynaarlo', 'wp-ultimo-locations'),
	__('Gemeente Westerveld', 'wp-ultimo-locations'),
	__('Gieten', 'wp-ultimo-locations'),
	__('Havelte', 'wp-ultimo-locations'),
	__('Hoogeveen', 'wp-ultimo-locations'),
	__('Klazienaveen', 'wp-ultimo-locations'),
	__('Koekange', 'wp-ultimo-locations'),
	__('Krakeel', 'wp-ultimo-locations'),
	__('Marsdijk', 'wp-ultimo-locations'),
	__('Meppel', 'wp-ultimo-locations'),
	__('Nieuw-Buinen', 'wp-ultimo-locations'),
	__('Nieuw-Dordrecht', 'wp-ultimo-locations'),
	__('Nieuw-Roden', 'wp-ultimo-locations'),
	__('Noordbarge', 'wp-ultimo-locations'),
	__('Norg', 'wp-ultimo-locations'),
	__('Odoorn', 'wp-ultimo-locations'),
	__('Oosterhesselen', 'wp-ultimo-locations'),
	__('Paterswolde', 'wp-ultimo-locations'),
	__('Peelo', 'wp-ultimo-locations'),
	__('Peize', 'wp-ultimo-locations'),
	__('Roden', 'wp-ultimo-locations'),
	__('Rolde', 'wp-ultimo-locations'),
	__('Ruinen', 'wp-ultimo-locations'),
	__('Ruinerwold', 'wp-ultimo-locations'),
	__('Schoonebeek', 'wp-ultimo-locations'),
	__('Schoonoord', 'wp-ultimo-locations'),
	__('Sleen', 'wp-ultimo-locations'),
	__('Tweede Exloërmond', 'wp-ultimo-locations'),
	__('Tynaarlo', 'wp-ultimo-locations'),
	__('Uffelte', 'wp-ultimo-locations'),
	__('Valthe', 'wp-ultimo-locations'),
	__('Valthermond', 'wp-ultimo-locations'),
	__('Veenoord', 'wp-ultimo-locations'),
	__('Vledder', 'wp-ultimo-locations'),
	__('Vries', 'wp-ultimo-locations'),
	__('Weiteveen', 'wp-ultimo-locations'),
	__('Westerbork', 'wp-ultimo-locations'),
	__('Westlaren', 'wp-ultimo-locations'),
	__('Wolfsbos', 'wp-ultimo-locations'),
	__('Zuidlaren', 'wp-ultimo-locations'),
);
