<?php // phpcs:ignore - @generation-checksum NL-ZE-74
/**
 * State City List for ZE - NL.
 *
 * City count: 74
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ZE - NL.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aagtekerke', 'wp-ultimo-locations'),
	__('Aardenburg', 'wp-ultimo-locations'),
	__('Arnemuiden', 'wp-ultimo-locations'),
	__('Axel', 'wp-ultimo-locations'),
	__('Borssele', 'wp-ultimo-locations'),
	__('Breskens', 'wp-ultimo-locations'),
	__('Brouwershaven', 'wp-ultimo-locations'),
	__('Bruinisse', 'wp-ultimo-locations'),
	__('Colijnsplaat', 'wp-ultimo-locations'),
	__('Dauwendaele', 'wp-ultimo-locations'),
	__('Domburg', 'wp-ultimo-locations'),
	__('Gemeente Borsele', 'wp-ultimo-locations'),
	__('Gemeente Goes', 'wp-ultimo-locations'),
	__('Gemeente Hulst', 'wp-ultimo-locations'),
	__('Gemeente Kapelle', 'wp-ultimo-locations'),
	__('Gemeente Middelburg', 'wp-ultimo-locations'),
	__('Gemeente Noord-Beveland', 'wp-ultimo-locations'),
	__('Gemeente Reimerswaal', 'wp-ultimo-locations'),
	__('Gemeente Sluis', 'wp-ultimo-locations'),
	__('Gemeente Terneuzen', 'wp-ultimo-locations'),
	__('Gemeente Tholen', 'wp-ultimo-locations'),
	__('Gemeente Veere', 'wp-ultimo-locations'),
	__('Gemeente Vlissingen', 'wp-ultimo-locations'),
	__('Goes', 'wp-ultimo-locations'),
	__('Griffioen', 'wp-ultimo-locations'),
	__('Grijpskerke', 'wp-ultimo-locations'),
	__('Haamstede', 'wp-ultimo-locations'),
	__('Hulst', 'wp-ultimo-locations'),
	__('IJzendijke', 'wp-ultimo-locations'),
	__('Kamperland', 'wp-ultimo-locations'),
	__('Kapelle', 'wp-ultimo-locations'),
	__('Klarenbeek', 'wp-ultimo-locations'),
	__('Kloetinge', 'wp-ultimo-locations'),
	__('Koewacht', 'wp-ultimo-locations'),
	__('Koudekerke', 'wp-ultimo-locations'),
	__('Lammerenburg', 'wp-ultimo-locations'),
	__('Malta', 'wp-ultimo-locations'),
	__('Meliskerke', 'wp-ultimo-locations'),
	__('Middelburg', 'wp-ultimo-locations'),
	__('Nieuw- en Sint Joosland', 'wp-ultimo-locations'),
	__('Nieuwerkerk', 'wp-ultimo-locations'),
	__('Oostburg', 'wp-ultimo-locations'),
	__('Oosterland', 'wp-ultimo-locations'),
	__('Oostkapelle', 'wp-ultimo-locations'),
	__('Othene', 'wp-ultimo-locations'),
	__('Oud-Vossemeer', 'wp-ultimo-locations'),
	__('Poortvliet', 'wp-ultimo-locations'),
	__('Renesse', 'wp-ultimo-locations'),
	__('Sas van Gent', 'wp-ultimo-locations'),
	__('Scharendijke', 'wp-ultimo-locations'),
	__('Scherpenisse', 'wp-ultimo-locations'),
	__('Schoondijke', 'wp-ultimo-locations'),
	__('Schouwen-Duiveland', 'wp-ultimo-locations'),
	__('Serooskerke', 'wp-ultimo-locations'),
	__('Sint Laurens', 'wp-ultimo-locations'),
	__('Sint Philipsland', 'wp-ultimo-locations'),
	__('Sluis', 'wp-ultimo-locations'),
	__('Sluiskil', 'wp-ultimo-locations'),
	__('Stavenisse', 'wp-ultimo-locations'),
	__('Terneuzen', 'wp-ultimo-locations'),
	__('Tholen', 'wp-ultimo-locations'),
	__('Vlissingen', 'wp-ultimo-locations'),
	__('Waarde', 'wp-ultimo-locations'),
	__('Wemeldinge', 'wp-ultimo-locations'),
	__('West-Souburg', 'wp-ultimo-locations'),
	__('Westdorpe', 'wp-ultimo-locations'),
	__('Westerzicht', 'wp-ultimo-locations'),
	__('Westkapelle', 'wp-ultimo-locations'),
	__('Wissenkerke', 'wp-ultimo-locations'),
	__('Wolphaartsdijk', 'wp-ultimo-locations'),
	__('Yerseke', 'wp-ultimo-locations'),
	__('Zaamslag', 'wp-ultimo-locations'),
	__('Zierikzee', 'wp-ultimo-locations'),
	__('Zoutelande', 'wp-ultimo-locations'),
);
