<?php // phpcs:ignore - @generation-checksum RU-AD-30
/**
 * State City List for AD - RU.
 *
 * City count: 30
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AD - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abadzekhskaya', 'wp-ultimo-locations'),
	__('Adygeysk', 'wp-ultimo-locations'),
	__('Adygeysk Republican Urban Okrug', 'wp-ultimo-locations'),
	__('Beloye', 'wp-ultimo-locations'),
	__('Blechepsin', 'wp-ultimo-locations'),
	__('Dondukovskaya', 'wp-ultimo-locations'),
	__('Enem', 'wp-ultimo-locations'),
	__('Giaginskaya', 'wp-ultimo-locations'),
	__('Giaginskiy Rayon', 'wp-ultimo-locations'),
	__('Kamennomostskiy', 'wp-ultimo-locations'),
	__('Khanskaya', 'wp-ultimo-locations'),
	__('Khatukay', 'wp-ultimo-locations'),
	__('Khodz’', 'wp-ultimo-locations'),
	__('Koshekhabl’', 'wp-ultimo-locations'),
	__('Koshekhabl’skiy Rayon', 'wp-ultimo-locations'),
	__('Krasnogvardeyskiy Rayon', 'wp-ultimo-locations'),
	__('Krasnogvardeyskoye', 'wp-ultimo-locations'),
	__('Kuzhorskaya', 'wp-ultimo-locations'),
	__('Maykop', 'wp-ultimo-locations'),
	__('Maykop Republican Urban Okrug', 'wp-ultimo-locations'),
	__('Maykopskiy Rayon', 'wp-ultimo-locations'),
	__('Natyrbovo', 'wp-ultimo-locations'),
	__('Ponezhukay', 'wp-ultimo-locations'),
	__('Shovgenovskiy', 'wp-ultimo-locations'),
	__('Shovgenovskiy Rayon', 'wp-ultimo-locations'),
	__('Takhtamukay', 'wp-ultimo-locations'),
	__('Takhtamukayskiy Rayon', 'wp-ultimo-locations'),
	__('Teuchezhskiy Rayon', 'wp-ultimo-locations'),
	__('Tlyustenkhabl’', 'wp-ultimo-locations'),
	__('Yablonovskiy', 'wp-ultimo-locations'),
);
