<?php // phpcs:ignore - @generation-checksum RU-AMU-58
/**
 * State City List for AMU - RU.
 *
 * City count: 58
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AMU - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Arkhara', 'wp-ultimo-locations'),
	__('Arkharinskiy Rayon', 'wp-ultimo-locations'),
	__('Belogorsk', 'wp-ultimo-locations'),
	__('Belogorskiy Rayon', 'wp-ultimo-locations'),
	__('Blagoveshchensk', 'wp-ultimo-locations'),
	__('Blagoveshchenskiy Rayon', 'wp-ultimo-locations'),
	__('Bureya', 'wp-ultimo-locations'),
	__('Bureyskiy Rayon', 'wp-ultimo-locations'),
	__('Ekimchan', 'wp-ultimo-locations'),
	__('Gorod Blagoveshchensk', 'wp-ultimo-locations'),
	__('Gorod Raychikhinsk', 'wp-ultimo-locations'),
	__('Ivanovskiy Rayon', 'wp-ultimo-locations'),
	__('Konstantinovka', 'wp-ultimo-locations'),
	__('Konstantinovskiy Rayon', 'wp-ultimo-locations'),
	__('Magdagachi', 'wp-ultimo-locations'),
	__('Magdagachinskiy Rayon', 'wp-ultimo-locations'),
	__('Mazanovskiy Rayon', 'wp-ultimo-locations'),
	__('Mikhaylovskiy Rayon', 'wp-ultimo-locations'),
	__('Never', 'wp-ultimo-locations'),
	__('Novobureyskiy', 'wp-ultimo-locations'),
	__('Novoraychikhinsk', 'wp-ultimo-locations'),
	__('Oktyabr’skiy Rayon', 'wp-ultimo-locations'),
	__('Ovsyanka', 'wp-ultimo-locations'),
	__('Poyarkovo', 'wp-ultimo-locations'),
	__('Raychikhinsk', 'wp-ultimo-locations'),
	__('Romnenskiy Rayon', 'wp-ultimo-locations'),
	__('Romny', 'wp-ultimo-locations'),
	__('Selemdzhinskiy Rayon', 'wp-ultimo-locations'),
	__('Seryshevo', 'wp-ultimo-locations'),
	__('Seryshevskiy Rayon', 'wp-ultimo-locations'),
	__('Shimanovsk', 'wp-ultimo-locations'),
	__('Shimanovskiy Rayon', 'wp-ultimo-locations'),
	__('Shirokiy', 'wp-ultimo-locations'),
	__('Sivaki', 'wp-ultimo-locations'),
	__('Skovorodino', 'wp-ultimo-locations'),
	__('Skovorodinskiy Rayon', 'wp-ultimo-locations'),
	__('Solovjevsk', 'wp-ultimo-locations'),
	__('Srednebelaya', 'wp-ultimo-locations'),
	__('Svobodnenskiy Rayon', 'wp-ultimo-locations'),
	__('Svobodnyy', 'wp-ultimo-locations'),
	__('Takhtamygda', 'wp-ultimo-locations'),
	__('Talakan', 'wp-ultimo-locations'),
	__('Taldan', 'wp-ultimo-locations'),
	__('Tambovka', 'wp-ultimo-locations'),
	__('Tambovskiy Rayon', 'wp-ultimo-locations'),
	__('Tokur', 'wp-ultimo-locations'),
	__('Tsiolkovskiy', 'wp-ultimo-locations'),
	__('Tygda', 'wp-ultimo-locations'),
	__('Tynda', 'wp-ultimo-locations'),
	__('Tyndinskiy Rayon', 'wp-ultimo-locations'),
	__('Urusha', 'wp-ultimo-locations'),
	__('Ushumun', 'wp-ultimo-locations'),
	__('Yekaterinoslavka', 'wp-ultimo-locations'),
	__('Yerofey Pavlovich', 'wp-ultimo-locations'),
	__('Zavitinsk', 'wp-ultimo-locations'),
	__('Zavitinskiy Rayon', 'wp-ultimo-locations'),
	__('Zeya', 'wp-ultimo-locations'),
	__('Zeyskiy Rayon', 'wp-ultimo-locations'),
);
