<?php // phpcs:ignore - @generation-checksum RU-CU-49
/**
 * State City List for CU - RU.
 *
 * City count: 49
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for CU - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alatyrskiy Rayon', 'wp-ultimo-locations'),
	__('Alatyr’', 'wp-ultimo-locations'),
	__('Alikovo', 'wp-ultimo-locations'),
	__('Alikovskiy Rayon', 'wp-ultimo-locations'),
	__('Atlashevo', 'wp-ultimo-locations'),
	__('Batyrevo', 'wp-ultimo-locations'),
	__('Batyrevskiy Rayon', 'wp-ultimo-locations'),
	__('Buinsk', 'wp-ultimo-locations'),
	__('Cheboksarskiy Rayon', 'wp-ultimo-locations'),
	__('Cheboksary', 'wp-ultimo-locations'),
	__('Ibresi', 'wp-ultimo-locations'),
	__('Ibresinskiy Rayon', 'wp-ultimo-locations'),
	__('Ishley', 'wp-ultimo-locations'),
	__('Kanash', 'wp-ultimo-locations'),
	__('Kanashskiy Rayon', 'wp-ultimo-locations'),
	__('Kirya', 'wp-ultimo-locations'),
	__("Komsomol'skoye", 'wp-ultimo-locations'),
	__('Komsomol’skiy Rayon', 'wp-ultimo-locations'),
	__('Kozlovka', 'wp-ultimo-locations'),
	__('Kozlovskiy Rayon', 'wp-ultimo-locations'),
	__('Krasnoarmeyskiy Rayon', 'wp-ultimo-locations'),
	__('Krasnoarmeyskoye', 'wp-ultimo-locations'),
	__('Krasnochetayskiy Rayon', 'wp-ultimo-locations'),
	__('Krasnyye Chetai', 'wp-ultimo-locations'),
	__('Kugesi', 'wp-ultimo-locations'),
	__('Mariinskiy Posad', 'wp-ultimo-locations'),
	__('Mariinsko-Posadskiy Rayon', 'wp-ultimo-locations'),
	__('Morgaushi', 'wp-ultimo-locations'),
	__('Morgaushskiy Rayon', 'wp-ultimo-locations'),
	__('Novocheboksarsk', 'wp-ultimo-locations'),
	__('Novyye Lapsary', 'wp-ultimo-locations'),
	__('Poretskiy Rayon', 'wp-ultimo-locations'),
	__('Poretskoye', 'wp-ultimo-locations'),
	__('Shemursha', 'wp-ultimo-locations'),
	__('Shemurshinskiy Rayon', 'wp-ultimo-locations'),
	__('Shikhazany', 'wp-ultimo-locations'),
	__('Shumerlinskiy Rayon', 'wp-ultimo-locations'),
	__('Shumerlya', 'wp-ultimo-locations'),
	__('Tsivil’sk', 'wp-ultimo-locations'),
	__('Tsivil’skiy Rayon', 'wp-ultimo-locations'),
	__('Urmarskiy Rayon', 'wp-ultimo-locations'),
	__('Urmary', 'wp-ultimo-locations'),
	__('Vurnarskiy Rayon', 'wp-ultimo-locations'),
	__('Vurnary', 'wp-ultimo-locations'),
	__('Yadrin', 'wp-ultimo-locations'),
	__('Yadrinskiy Rayon', 'wp-ultimo-locations'),
	__('Yal’chikskiy Rayon', 'wp-ultimo-locations'),
	__('Yantikovo', 'wp-ultimo-locations'),
	__('Yantikovskiy Rayon', 'wp-ultimo-locations'),
);
