<?php // phpcs:ignore - @generation-checksum RU-KB-64
/**
 * State City List for KB - RU.
 *
 * City count: 64
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KB - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aleksandrovskaya', 'wp-ultimo-locations'),
	__('Altud', 'wp-ultimo-locations'),
	__('Argudan', 'wp-ultimo-locations'),
	__('Aushiger', 'wp-ultimo-locations'),
	__('Babugent', 'wp-ultimo-locations'),
	__('Baksan', 'wp-ultimo-locations'),
	__('Baksanenok', 'wp-ultimo-locations'),
	__('Baksanskiy Rayon', 'wp-ultimo-locations'),
	__('Belaya Rechka', 'wp-ultimo-locations'),
	__('Bylym', 'wp-ultimo-locations'),
	__('Chegem', 'wp-ultimo-locations'),
	__('Chegem Vtoroy', 'wp-ultimo-locations'),
	__('Cherekskiy Rayon', 'wp-ultimo-locations'),
	__('Deyskoye', 'wp-ultimo-locations'),
	__('Dugulubgey', 'wp-ultimo-locations'),
	__('El’brus', 'wp-ultimo-locations'),
	__('El’brusskiy Rayon', 'wp-ultimo-locations'),
	__('Germenchik', 'wp-ultimo-locations'),
	__('Gundelen', 'wp-ultimo-locations'),
	__('Islamey', 'wp-ultimo-locations'),
	__('Kakhun', 'wp-ultimo-locations'),
	__('Kamenka', 'wp-ultimo-locations'),
	__('Kamennomostskoye', 'wp-ultimo-locations'),
	__('Karagach', 'wp-ultimo-locations'),
	__('Kashkhatau', 'wp-ultimo-locations'),
	__('Kenzhe', 'wp-ultimo-locations'),
	__('Kishpek', 'wp-ultimo-locations'),
	__('Kotlyarevskaya', 'wp-ultimo-locations'),
	__('Kuba-Taba', 'wp-ultimo-locations'),
	__('Kyzburun Pervyy', 'wp-ultimo-locations'),
	__('Lechinkay', 'wp-ultimo-locations'),
	__('Leskenskiy rayon', 'wp-ultimo-locations'),
	__('Malka', 'wp-ultimo-locations'),
	__('Mayskiy Rayon', 'wp-ultimo-locations'),
	__('Nal’chik', 'wp-ultimo-locations'),
	__('Nartan', 'wp-ultimo-locations'),
	__('Nartkala', 'wp-ultimo-locations'),
	__('Nizhniy Cherek', 'wp-ultimo-locations'),
	__('Nizhniy Kurkuzhin', 'wp-ultimo-locations'),
	__('Planovskoye', 'wp-ultimo-locations'),
	__('Primalkinskoye', 'wp-ultimo-locations'),
	__('Prokhladnenskiy Rayon', 'wp-ultimo-locations'),
	__('Prokhladnyy', 'wp-ultimo-locations'),
	__('Psygansu', 'wp-ultimo-locations'),
	__('Sarmakovo', 'wp-ultimo-locations'),
	__('Shalushka', 'wp-ultimo-locations'),
	__('Soldatskaya', 'wp-ultimo-locations'),
	__('Staryy Cherek', 'wp-ultimo-locations'),
	__('Staryy Urukh', 'wp-ultimo-locations'),
	__('Terek', 'wp-ultimo-locations'),
	__('Terskiy Rayon', 'wp-ultimo-locations'),
	__('Terskol', 'wp-ultimo-locations'),
	__('Tyrnyauz', 'wp-ultimo-locations'),
	__('Urukh', 'wp-ultimo-locations'),
	__('Urvanskiy Rayon', 'wp-ultimo-locations'),
	__('Urvan’', 'wp-ultimo-locations'),
	__('Verkhniy Kurkuzhin', 'wp-ultimo-locations'),
	__('Verkhnyaya Balkariya', 'wp-ultimo-locations'),
	__('Vol’nyy Aul', 'wp-ultimo-locations'),
	__('Zalukokoazhe', 'wp-ultimo-locations'),
	__('Zayukovo', 'wp-ultimo-locations'),
	__('Zhankhoteko', 'wp-ultimo-locations'),
	__('Zhemtala', 'wp-ultimo-locations'),
	__('Zol’skiy Rayon', 'wp-ultimo-locations'),
);
