<?php // phpcs:ignore - @generation-checksum RU-KEM-72
/**
 * State City List for KEM - RU.
 *
 * City count: 72
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for KEM - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abagur', 'wp-ultimo-locations'),
	__('Anzhero-Sudzhensk', 'wp-ultimo-locations'),
	__('Artyshta', 'wp-ultimo-locations'),
	__('Bachatskiy', 'wp-ultimo-locations'),
	__('Barzas', 'wp-ultimo-locations'),
	__('Belogorsk', 'wp-ultimo-locations'),
	__('Belovo', 'wp-ultimo-locations'),
	__('Berëzovskiy', 'wp-ultimo-locations'),
	__('Borovoy', 'wp-ultimo-locations'),
	__('Chistogorskiy', 'wp-ultimo-locations'),
	__('Gramoteino', 'wp-ultimo-locations'),
	__('Gur’yevsk', 'wp-ultimo-locations'),
	__('Inskoy', 'wp-ultimo-locations'),
	__('Itatskiy', 'wp-ultimo-locations'),
	__('Izhmorskiy', 'wp-ultimo-locations'),
	__('Kaltan', 'wp-ultimo-locations'),
	__('Karagayla', 'wp-ultimo-locations'),
	__('Kaz', 'wp-ultimo-locations'),
	__('Kedrovka', 'wp-ultimo-locations'),
	__('Kemerovo', 'wp-ultimo-locations'),
	__('Kiselëvsk', 'wp-ultimo-locations'),
	__('Krapivinskiy', 'wp-ultimo-locations'),
	__('Krasnobrodskiy', 'wp-ultimo-locations'),
	__('Krasnogorskiy', 'wp-ultimo-locations'),
	__('Krasnoye', 'wp-ultimo-locations'),
	__('Kuzedeyevo', 'wp-ultimo-locations'),
	__('Leninsk-Kuznetskiy Rayon', 'wp-ultimo-locations'),
	__('Leninsk-Kuznetsky', 'wp-ultimo-locations'),
	__('Listvyagi', 'wp-ultimo-locations'),
	__('Mariinsk', 'wp-ultimo-locations'),
	__('Mezhdurechensk', 'wp-ultimo-locations'),
	__('Mundybash', 'wp-ultimo-locations'),
	__('Myski', 'wp-ultimo-locations'),
	__('Nikitinskiy', 'wp-ultimo-locations'),
	__('Novokuznetsk', 'wp-ultimo-locations'),
	__('Novokuznetskiy Rayon', 'wp-ultimo-locations'),
	__('Novopesterevo', 'wp-ultimo-locations'),
	__('Osinniki', 'wp-ultimo-locations'),
	__('Pioner', 'wp-ultimo-locations'),
	__('Plotnikovo', 'wp-ultimo-locations'),
	__('Polysayevo', 'wp-ultimo-locations'),
	__('Pritomskiy', 'wp-ultimo-locations'),
	__('Prokop’yevsk', 'wp-ultimo-locations'),
	__('Prokop’yevskiy Rayon', 'wp-ultimo-locations'),
	__('Promyshlennaya', 'wp-ultimo-locations'),
	__('Promyshlennovskiy', 'wp-ultimo-locations'),
	__('Rudnichnyy', 'wp-ultimo-locations'),
	__('Salair', 'wp-ultimo-locations'),
	__('Sheregesh', 'wp-ultimo-locations'),
	__('Sosnovka', 'wp-ultimo-locations'),
	__('Spassk', 'wp-ultimo-locations'),
	__('Starobachaty', 'wp-ultimo-locations'),
	__('Staropesterevo', 'wp-ultimo-locations'),
	__('Suslovo', 'wp-ultimo-locations'),
	__('Tashtagol', 'wp-ultimo-locations'),
	__('Tashtagol’skiy Rayon', 'wp-ultimo-locations'),
	__('Tayga', 'wp-ultimo-locations'),
	__('Tayzhina', 'wp-ultimo-locations'),
	__('Temirtau', 'wp-ultimo-locations'),
	__('Tisul’', 'wp-ultimo-locations'),
	__('Topki', 'wp-ultimo-locations'),
	__('Trudarmeyskiy', 'wp-ultimo-locations'),
	__('Tyazhinskiy', 'wp-ultimo-locations'),
	__('Ursk', 'wp-ultimo-locations'),
	__('Verkh-Chebula', 'wp-ultimo-locations'),
	__('Yagunovo', 'wp-ultimo-locations'),
	__('Yagunovskiy', 'wp-ultimo-locations'),
	__('Yashkino', 'wp-ultimo-locations'),
	__('Yaya', 'wp-ultimo-locations'),
	__('Yurga', 'wp-ultimo-locations'),
	__('Yurginskiy Rayon', 'wp-ultimo-locations'),
	__('Zelenogorskiy', 'wp-ultimo-locations'),
);
