<?php // phpcs:ignore - @generation-checksum RU-MO-48
/**
 * State City List for MO - RU.
 *
 * City count: 48
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MO - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ardatov', 'wp-ultimo-locations'),
	__('Ardatovskiy Rayon', 'wp-ultimo-locations'),
	__('Atemar', 'wp-ultimo-locations'),
	__('Atyashevo', 'wp-ultimo-locations'),
	__('Atyashevskiy Rayon', 'wp-ultimo-locations'),
	__('Atyur’yevskiy Rayon', 'wp-ultimo-locations'),
	__('Barashevo', 'wp-ultimo-locations'),
	__('Bol’shebereznikovskiy Rayon', 'wp-ultimo-locations'),
	__('Chamzinka', 'wp-ultimo-locations'),
	__('Chamzinskiy Rayon', 'wp-ultimo-locations'),
	__('Insar', 'wp-ultimo-locations'),
	__('Insarskiy Rayon', 'wp-ultimo-locations'),
	__('Kadoshkino', 'wp-ultimo-locations'),
	__('Kemlya', 'wp-ultimo-locations'),
	__('Kochkurovo', 'wp-ultimo-locations'),
	__('Kochkurovskiy Rayon', 'wp-ultimo-locations'),
	__('Kovylkino', 'wp-ultimo-locations'),
	__('Krasnoslobodsk', 'wp-ultimo-locations'),
	__('Krasnoslobodskiy Rayon', 'wp-ultimo-locations'),
	__('Lepley', 'wp-ultimo-locations'),
	__('Lukhovka', 'wp-ultimo-locations'),
	__('Lyambirskiy Rayon', 'wp-ultimo-locations'),
	__('Lyambir’', 'wp-ultimo-locations'),
	__('Nikolayevka', 'wp-ultimo-locations'),
	__('Partsa', 'wp-ultimo-locations'),
	__('Romodanovo', 'wp-ultimo-locations'),
	__('Romodanovskiy Rayon', 'wp-ultimo-locations'),
	__('Ruzayevka', 'wp-ultimo-locations'),
	__('Ruzayevskiy Rayon', 'wp-ultimo-locations'),
	__('Saransk', 'wp-ultimo-locations'),
	__('Shiringushi', 'wp-ultimo-locations'),
	__('Sosnovka', 'wp-ultimo-locations'),
	__('Staroshaygovskiy Rayon', 'wp-ultimo-locations'),
	__('Tatarskaya Pishlya', 'wp-ultimo-locations'),
	__('Temnikov', 'wp-ultimo-locations'),
	__('Temnikovskiy Rayon', 'wp-ultimo-locations'),
	__('Ten’gushevo', 'wp-ultimo-locations'),
	__('Ten’gushevskiy Rayon', 'wp-ultimo-locations'),
	__('Torbeyevo', 'wp-ultimo-locations'),
	__('Turgenevo', 'wp-ultimo-locations'),
	__('Udarnyy', 'wp-ultimo-locations'),
	__('Umet', 'wp-ultimo-locations'),
	__('Vysha', 'wp-ultimo-locations'),
	__('Yavas', 'wp-ultimo-locations'),
	__('Yel’nikovskiy Rayon', 'wp-ultimo-locations'),
	__('Zubova Polyana', 'wp-ultimo-locations'),
	__('Zubovo-Polyanskiy Rayon', 'wp-ultimo-locations'),
	__('Zykovo', 'wp-ultimo-locations'),
);
