<?php // phpcs:ignore - @generation-checksum RU-MOW-92
/**
 * State City List for MOW - RU.
 *
 * City count: 92
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MOW - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Altuf’yevskiy', 'wp-ultimo-locations'),
	__('Amin’yevo', 'wp-ultimo-locations'),
	__('Annino', 'wp-ultimo-locations'),
	__('Babushkin', 'wp-ultimo-locations'),
	__('Bibirevo', 'wp-ultimo-locations'),
	__('Biryulëvo', 'wp-ultimo-locations'),
	__('Bogorodskoye', 'wp-ultimo-locations'),
	__('Brateyevo', 'wp-ultimo-locations'),
	__('Chertanovo Yuzhnoye', 'wp-ultimo-locations'),
	__('Cherëmushki', 'wp-ultimo-locations'),
	__('Davydkovo', 'wp-ultimo-locations'),
	__('Golovinskiy', 'wp-ultimo-locations'),
	__('Gol’yanovo', 'wp-ultimo-locations'),
	__('Ivanovskoye', 'wp-ultimo-locations'),
	__('Kapotnya', 'wp-ultimo-locations'),
	__('Kokoshkino', 'wp-ultimo-locations'),
	__('Kolomenskoye', 'wp-ultimo-locations'),
	__('Kotlovka', 'wp-ultimo-locations'),
	__('Kozeyevo', 'wp-ultimo-locations'),
	__('Krasnaya Pahra', 'wp-ultimo-locations'),
	__('Kur’yanovo', 'wp-ultimo-locations'),
	__('Kuz’minki', 'wp-ultimo-locations'),
	__('LMS', 'wp-ultimo-locations'),
	__('Lefortovo', 'wp-ultimo-locations'),
	__('Leonovo', 'wp-ultimo-locations'),
	__('Lianozovo', 'wp-ultimo-locations'),
	__('Likhobory', 'wp-ultimo-locations'),
	__('Luzhniki', 'wp-ultimo-locations'),
	__('Lyublino', 'wp-ultimo-locations'),
	__('Mar’ino', 'wp-ultimo-locations'),
	__('Matveyevskoye', 'wp-ultimo-locations'),
	__('Metrogorodok', 'wp-ultimo-locations'),
	__('Mikhalkovo', 'wp-ultimo-locations'),
	__('Moscow', 'wp-ultimo-locations'),
	__('Moskovskiy', 'wp-ultimo-locations'),
	__('Nagornyy', 'wp-ultimo-locations'),
	__('Nekrasovka', 'wp-ultimo-locations'),
	__('Nikol’skoye', 'wp-ultimo-locations'),
	__('Nikulino', 'wp-ultimo-locations'),
	__('Novo-Peredelkino', 'wp-ultimo-locations'),
	__('Novogireyevo', 'wp-ultimo-locations'),
	__('Novokhovrino', 'wp-ultimo-locations'),
	__('Novokuz’minki', 'wp-ultimo-locations'),
	__('Novovladykino', 'wp-ultimo-locations'),
	__('Novyye Cherëmushki', 'wp-ultimo-locations'),
	__('Novyye Kuz’minki', 'wp-ultimo-locations'),
	__('Ochakovo-Matveyevskoye', 'wp-ultimo-locations'),
	__('Orekhovo-Borisovo', 'wp-ultimo-locations'),
	__('Orekhovo-Borisovo Severnoye', 'wp-ultimo-locations'),
	__('Ostankinskiy', 'wp-ultimo-locations'),
	__('Otradnoye', 'wp-ultimo-locations'),
	__('Pokrovskoye-Streshnëvo', 'wp-ultimo-locations'),
	__('Presnenskiy', 'wp-ultimo-locations'),
	__('Ramenki', 'wp-ultimo-locations'),
	__('Rostokino', 'wp-ultimo-locations'),
	__('Rublëvo', 'wp-ultimo-locations'),
	__('Ryazanskiy', 'wp-ultimo-locations'),
	__('Setun’', 'wp-ultimo-locations'),
	__('Severnyy', 'wp-ultimo-locations'),
	__('Shcherbinka', 'wp-ultimo-locations'),
	__('Shchukino', 'wp-ultimo-locations'),
	__('Slobodka', 'wp-ultimo-locations'),
	__('Sokol', 'wp-ultimo-locations'),
	__('Sokol’niki', 'wp-ultimo-locations'),
	__('Solntsevo', 'wp-ultimo-locations'),
	__('Strogino', 'wp-ultimo-locations'),
	__('Sviblovo', 'wp-ultimo-locations'),
	__('Taganskiy', 'wp-ultimo-locations'),
	__('Tekstil’shchiki', 'wp-ultimo-locations'),
	__('Tolstopal’tsevo', 'wp-ultimo-locations'),
	__('Troitsk', 'wp-ultimo-locations'),
	__('Troparëvo', 'wp-ultimo-locations'),
	__('Tsaritsyno', 'wp-ultimo-locations'),
	__('Tsentral’nyy Administrativnyy Okrug', 'wp-ultimo-locations'),
	__('Tyoply Stan', 'wp-ultimo-locations'),
	__('Vagonoremont', 'wp-ultimo-locations'),
	__('Vatutinki', 'wp-ultimo-locations'),
	__('Vatutino', 'wp-ultimo-locations'),
	__('Veshnyaki', 'wp-ultimo-locations'),
	__('Vnukovo', 'wp-ultimo-locations'),
	__('Vorob’yovo', 'wp-ultimo-locations'),
	__('Vostochnoe Degunino', 'wp-ultimo-locations'),
	__('Vostochnyy', 'wp-ultimo-locations'),
	__('Vykhino-Zhulebino', 'wp-ultimo-locations'),
	__('Yaroslavskiy', 'wp-ultimo-locations'),
	__('Yasenevo', 'wp-ultimo-locations'),
	__('Zagor’ye', 'wp-ultimo-locations'),
	__('Zamoskvorech’ye', 'wp-ultimo-locations'),
	__('Zelenograd', 'wp-ultimo-locations'),
	__('Zhulebino', 'wp-ultimo-locations'),
	__('Zyablikovo', 'wp-ultimo-locations'),
	__('Zyuzino', 'wp-ultimo-locations'),
);
