<?php // phpcs:ignore - @generation-checksum RU-MUR-42
/**
 * State City List for MUR - RU.
 *
 * City count: 42
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for MUR - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abram Mys', 'wp-ultimo-locations'),
	__('Afrikanda', 'wp-ultimo-locations'),
	__('Alakurtti', 'wp-ultimo-locations'),
	__('Apatity', 'wp-ultimo-locations'),
	__('Gadzhiyevo', 'wp-ultimo-locations'),
	__('Kandalaksha', 'wp-ultimo-locations'),
	__('Kandalakshskiy rayon', 'wp-ultimo-locations'),
	__('Kirovsk', 'wp-ultimo-locations'),
	__('Kola', 'wp-ultimo-locations'),
	__('Kol’skiy Rayon', 'wp-ultimo-locations'),
	__('Kovdor', 'wp-ultimo-locations'),
	__('Kovdorskiy Rayon', 'wp-ultimo-locations'),
	__('Lovozero', 'wp-ultimo-locations'),
	__('Lovozerskiy Rayon', 'wp-ultimo-locations'),
	__('Molochnyy', 'wp-ultimo-locations'),
	__('Monchegorsk', 'wp-ultimo-locations'),
	__('Murmansk', 'wp-ultimo-locations'),
	__('Murmashi', 'wp-ultimo-locations'),
	__('Nikel', 'wp-ultimo-locations'),
	__('Olenegorsk', 'wp-ultimo-locations'),
	__('Ostrovnoy', 'wp-ultimo-locations'),
	__('Pechenga', 'wp-ultimo-locations'),
	__('Pechengskiy Rayon', 'wp-ultimo-locations'),
	__('Polyarnyy', 'wp-ultimo-locations'),
	__('Polyarnyye Zori', 'wp-ultimo-locations'),
	__('Poyakonda', 'wp-ultimo-locations'),
	__('Revda', 'wp-ultimo-locations'),
	__('Roslyakovo', 'wp-ultimo-locations'),
	__('Safonovo', 'wp-ultimo-locations'),
	__('Severomorsk', 'wp-ultimo-locations'),
	__('Severomorsk-3', 'wp-ultimo-locations'),
	__('Shonguy', 'wp-ultimo-locations'),
	__('Snezhnogorsk', 'wp-ultimo-locations'),
	__('Teribërka', 'wp-ultimo-locations'),
	__('Terskiy Rayon', 'wp-ultimo-locations'),
	__('Umba', 'wp-ultimo-locations'),
	__('Verkhnetulomskiy', 'wp-ultimo-locations'),
	__('Vidyayevo', 'wp-ultimo-locations'),
	__('Vysokiy', 'wp-ultimo-locations'),
	__('Zaozërsk', 'wp-ultimo-locations'),
	__('Zapolyarnyy', 'wp-ultimo-locations'),
	__('Zelenoborskiy', 'wp-ultimo-locations'),
);
