<?php // phpcs:ignore - @generation-checksum RU-SPE-58
/**
 * State City List for SPE - RU.
 *
 * City count: 58
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SPE - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Admiralteisky', 'wp-ultimo-locations'),
	__('Aleksandrovskaya', 'wp-ultimo-locations'),
	__('Avtovo', 'wp-ultimo-locations'),
	__('Beloostrov', 'wp-ultimo-locations'),
	__('Centralniy', 'wp-ultimo-locations'),
	__('Dachnoye', 'wp-ultimo-locations'),
	__('Frunzenskiy Rayon', 'wp-ultimo-locations'),
	__('Gorelovo', 'wp-ultimo-locations'),
	__('Grazhdanka', 'wp-ultimo-locations'),
	__('Kolomyagi', 'wp-ultimo-locations'),
	__('Kolpino', 'wp-ultimo-locations'),
	__('Komarovo', 'wp-ultimo-locations'),
	__('Komendantsky aerodrom', 'wp-ultimo-locations'),
	__('Krasnogvargeisky', 'wp-ultimo-locations'),
	__('Krasnoye Selo', 'wp-ultimo-locations'),
	__('Kronshtadt', 'wp-ultimo-locations'),
	__('Kupchino', 'wp-ultimo-locations'),
	__('Kurortnyy Rayon', 'wp-ultimo-locations'),
	__('Kushelevka', 'wp-ultimo-locations'),
	__('Lakhtinskiy', 'wp-ultimo-locations'),
	__('Levashovo', 'wp-ultimo-locations'),
	__('Lisiy Nos', 'wp-ultimo-locations'),
	__('Lomonosov', 'wp-ultimo-locations'),
	__('Metallostroy', 'wp-ultimo-locations'),
	__('Molodezhnoye', 'wp-ultimo-locations'),
	__('Novaya Derevnya', 'wp-ultimo-locations'),
	__('Obukhovo', 'wp-ultimo-locations'),
	__('Ol’gino', 'wp-ultimo-locations'),
	__('Ozerki', 'wp-ultimo-locations'),
	__('Pargolovo', 'wp-ultimo-locations'),
	__('Pavlovsk', 'wp-ultimo-locations'),
	__('Pesochnyy', 'wp-ultimo-locations'),
	__('Peterhof', 'wp-ultimo-locations'),
	__('Petro-Slavyanka', 'wp-ultimo-locations'),
	__('Petrodvorets', 'wp-ultimo-locations'),
	__('Petrogradka', 'wp-ultimo-locations'),
	__('Pontonnyy', 'wp-ultimo-locations'),
	__('Primorskiy Rayon', 'wp-ultimo-locations'),
	__('Pushkin', 'wp-ultimo-locations'),
	__('Razliv', 'wp-ultimo-locations'),
	__('Repino', 'wp-ultimo-locations'),
	__('Saint Petersburg', 'wp-ultimo-locations'),
	__('Sapërnyy', 'wp-ultimo-locations'),
	__('Sestroretsk', 'wp-ultimo-locations'),
	__('Shushary', 'wp-ultimo-locations'),
	__('Shuvalovo', 'wp-ultimo-locations'),
	__('Solnechnoye', 'wp-ultimo-locations'),
	__('Sosnovaya Polyana', 'wp-ultimo-locations'),
	__('Sosnovka', 'wp-ultimo-locations'),
	__('Staraya Derevnya', 'wp-ultimo-locations'),
	__("Strel'na", 'wp-ultimo-locations'),
	__('Tarkhovka', 'wp-ultimo-locations'),
	__('Tyarlevo', 'wp-ultimo-locations'),
	__('Uritsk', 'wp-ultimo-locations'),
	__('Ust’-Izhora', 'wp-ultimo-locations'),
	__('Vasileostrovskiy Rayon', 'wp-ultimo-locations'),
	__("Vasyl'evsky Ostrov", 'wp-ultimo-locations'),
	__('Zelenogorsk', 'wp-ultimo-locations'),
);
