<?php // phpcs:ignore - @generation-checksum RU-TY-21
/**
 * State City List for TY - RU.
 *
 * City count: 21
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TY - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ak-Dovurak', 'wp-ultimo-locations'),
	__('Balgazyn', 'wp-ultimo-locations'),
	__('Bay-Khaak', 'wp-ultimo-locations'),
	__('Chadan', 'wp-ultimo-locations'),
	__('Erzin', 'wp-ultimo-locations'),
	__('Kaa-Khem', 'wp-ultimo-locations'),
	__('Khandagayty', 'wp-ultimo-locations'),
	__('Khovu-Aksy', 'wp-ultimo-locations'),
	__('Kungurtug', 'wp-ultimo-locations'),
	__('Kyzyl', 'wp-ultimo-locations'),
	__('Kyzyl-Khaya', 'wp-ultimo-locations'),
	__('Kyzyl-Mazhalyk', 'wp-ultimo-locations'),
	__('Mugur-Aksy', 'wp-ultimo-locations'),
	__('Samagaltay', 'wp-ultimo-locations'),
	__('Saryg-Sep', 'wp-ultimo-locations'),
	__('Shagonar', 'wp-ultimo-locations'),
	__('Sukpak', 'wp-ultimo-locations'),
	__('Sut-Khol’', 'wp-ultimo-locations'),
	__('Teeli', 'wp-ultimo-locations'),
	__('Toora-Khem', 'wp-ultimo-locations'),
	__('Turan', 'wp-ultimo-locations'),
);
