<?php // phpcs:ignore - @generation-checksum RU-VGG-82
/**
 * State City List for VGG - RU.
 *
 * City count: 82
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for VGG - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alimov-Lyubimovsky', 'wp-ultimo-locations'),
	__('Amochayevsky', 'wp-ultimo-locations'),
	__('Antipovka', 'wp-ultimo-locations'),
	__('Archedino-Chernushinsky', 'wp-ultimo-locations'),
	__('Archedinskaya', 'wp-ultimo-locations'),
	__('Beluzhino-Koldairov', 'wp-ultimo-locations'),
	__('Bereslavka', 'wp-ultimo-locations'),
	__('Bobrovsky 2-y', 'wp-ultimo-locations'),
	__('Burnatsky', 'wp-ultimo-locations'),
	__('Buyerak-Popovsky', 'wp-ultimo-locations'),
	__('Bykovo, Volgograd Oblast', 'wp-ultimo-locations'),
	__('Chernyshkovsky', 'wp-ultimo-locations'),
	__('Chiganaki 1-ye', 'wp-ultimo-locations'),
	__('Chiganaki 2-ye', 'wp-ultimo-locations'),
	__('Danilovka, Volgograd Oblast', 'wp-ultimo-locations'),
	__('Dubovka', 'wp-ultimo-locations'),
	__('Elton', 'wp-ultimo-locations'),
	__('Fastov', 'wp-ultimo-locations'),
	__('Frolovo', 'wp-ultimo-locations'),
	__('Glubokovsky', 'wp-ultimo-locations'),
	__('Gorbatovsky', 'wp-ultimo-locations'),
	__('Gornaya Polyana', 'wp-ultimo-locations'),
	__('Gorodishche, Volgograd Oblast', 'wp-ultimo-locations'),
	__('Ilovlya', 'wp-ultimo-locations'),
	__('Kalach-na-Donu', 'wp-ultimo-locations'),
	__('Kamyshin', 'wp-ultimo-locations'),
	__('Karpovsky', 'wp-ultimo-locations'),
	__('Kletskaya', 'wp-ultimo-locations'),
	__('Kolotsky', 'wp-ultimo-locations'),
	__('Kotelnikovo', 'wp-ultimo-locations'),
	__('Kotovo', 'wp-ultimo-locations'),
	__('Krasnoslobodsk', 'wp-ultimo-locations'),
	__('Krasny Yar, Volgograd Oblast', 'wp-ultimo-locations'),
	__('Kumylzhenskaya', 'wp-ultimo-locations'),
	__('Leninsk', 'wp-ultimo-locations'),
	__('Log', 'wp-ultimo-locations'),
	__('Medveditsky', 'wp-ultimo-locations'),
	__('Mikhaylovka', 'wp-ultimo-locations'),
	__('Mikhaylovka Urban Okrug', 'wp-ultimo-locations'),
	__('Mitkin', 'wp-ultimo-locations'),
	__('Nekhayevskaya', 'wp-ultimo-locations'),
	__('Nikolayevsk', 'wp-ultimo-locations'),
	__('Nizhny Chir', 'wp-ultimo-locations'),
	__('Novoanninsky', 'wp-ultimo-locations'),
	__('Novonikolayevsky, Volgograd Oblast', 'wp-ultimo-locations'),
	__('Novonikolskoe', 'wp-ultimo-locations'),
	__('Novy Rogachik', 'wp-ultimo-locations'),
	__('Oktyabrsky', 'wp-ultimo-locations'),
	__('Olkhovka, Volgograd Oblast', 'wp-ultimo-locations'),
	__('Otruba', 'wp-ultimo-locations'),
	__('Pallasovka', 'wp-ultimo-locations'),
	__('Petrov Val', 'wp-ultimo-locations'),
	__('Poltavsky', 'wp-ultimo-locations'),
	__('Popovsky', 'wp-ultimo-locations'),
	__('Preobrazhenskaya, Volgograd Oblast', 'wp-ultimo-locations'),
	__('Primorsk', 'wp-ultimo-locations'),
	__('Repino', 'wp-ultimo-locations'),
	__('Rogachev', 'wp-ultimo-locations'),
	__('Rubyozhny', 'wp-ultimo-locations'),
	__('Rudnya, Volgograd Oblast', 'wp-ultimo-locations'),
	__('Russko-Osinovsky', 'wp-ultimo-locations'),
	__('Samoylovsky', 'wp-ultimo-locations'),
	__('Satarovsky', 'wp-ultimo-locations'),
	__('Savinka', 'wp-ultimo-locations'),
	__('Sebrovo', 'wp-ultimo-locations'),
	__('Serafimovich', 'wp-ultimo-locations'),
	__('Shirokov', 'wp-ultimo-locations'),
	__('Slashchyovskaya', 'wp-ultimo-locations'),
	__('Sovetsky District', 'wp-ultimo-locations'),
	__('Srednyaya Akhtuba', 'wp-ultimo-locations'),
	__('Staraya Poltavka', 'wp-ultimo-locations'),
	__('Surovikino', 'wp-ultimo-locations'),
	__('Svetly Yar', 'wp-ultimo-locations'),
	__('Tochilkin', 'wp-ultimo-locations'),
	__('Uryupinsk', 'wp-ultimo-locations'),
	__('Vodstroy', 'wp-ultimo-locations'),
	__('Volgograd', 'wp-ultimo-locations'),
	__('Volzhsky', 'wp-ultimo-locations'),
	__('Voroshilovskiy District, Volgograd', 'wp-ultimo-locations'),
	__('Yelan', 'wp-ultimo-locations'),
	__('Zaplavnoye', 'wp-ultimo-locations'),
	__('Zhirnovsk', 'wp-ultimo-locations'),
);
