<?php // phpcs:ignore - @generation-checksum RU-YEV-18
/**
 * State City List for YEV - RU.
 *
 * City count: 18
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for YEV - RU.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Amurzet', 'wp-ultimo-locations'),
	__('Babstovo', 'wp-ultimo-locations'),
	__('Bira', 'wp-ultimo-locations'),
	__('Birakan', 'wp-ultimo-locations'),
	__('Birobidzhan', 'wp-ultimo-locations'),
	__('Birobidzhanskiy Rayon', 'wp-ultimo-locations'),
	__('Izvestkovyy', 'wp-ultimo-locations'),
	__('Khingansk', 'wp-ultimo-locations'),
	__('Kul’dur', 'wp-ultimo-locations'),
	__('Leninskiy Rayon', 'wp-ultimo-locations'),
	__('Leninskoye', 'wp-ultimo-locations'),
	__('Londoko', 'wp-ultimo-locations'),
	__('Obluchenskiy Rayon', 'wp-ultimo-locations'),
	__('Oktyabr’skiy Rayon', 'wp-ultimo-locations'),
	__('Priamurskiy', 'wp-ultimo-locations'),
	__('Smidovich', 'wp-ultimo-locations'),
	__('Smidovichskiy Rayon', 'wp-ultimo-locations'),
	__('Volochayevka Vtoraya', 'wp-ultimo-locations'),
);
