<?php // phpcs:ignore - @generation-checksum NE-2-6
/**
 * State City List for 2 - NE.
 *
 * City count: 6
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 2 - NE.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Diffa', 'wp-ultimo-locations'),
	__('Département de Diffa', 'wp-ultimo-locations'),
	__('Département de Maïné-Soroa', 'wp-ultimo-locations'),
	__('Département de Nguigmi', 'wp-ultimo-locations'),
	__('Maïné Soroa', 'wp-ultimo-locations'),
	__('Nguigmi', 'wp-ultimo-locations'),
);
