<?php // phpcs:ignore - @generation-checksum FR-123-8894
/**
 * Country Class for France (FR).
 *
 * State/province count: 123
 * City count: 8894
 * City count per state/province:
 * - 20R: 51 cities
 * - ARA: 1231 cities
 * - NAQ: 968 cities
 * - HDF: 921 cities
 * - GES: 887 cities
 * - OCC: 828 cities
 * - IDF: 694 cities
 * - BRE: 666 cities
 * - PDL: 660 cities
 * - PAC: 535 cities
 * - NOR: 526 cities
 * - CVL: 476 cities
 * - BFC: 451 cities
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

namespace WP_Ultimo\Country;

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Country Class for France (FR).
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 *
 * @property-read string $code
 * @property-read string $currency
 * @property-read int $phone_code
 */
class Country_FR extends Country {

	use \WP_Ultimo\Traits\Singleton;

	/**
	 * General country attributes.
	 *
	 * This might be useful, might be not.
	 * In case of doubt, keep it.
	 *
	 * @since 2.0.11
	 * @var array
	 */
	protected $attributes = [
		'country_code' => 'FR',
		'currency'     => 'EUR',
		'phone_code'   => 33,
	];

	/**
	 * The type of nomenclature used to refer to the country sub-divisions.
	 *
	 * @since 2.0.11
	 * @var string
	 */
	protected $state_type = 'region';

	/**
	 * Return the country name.
	 *
	 * @since 2.0.11
	 * @return string
	 */
	public function get_name() {

		return __('France', 'multisite-ultimate');
	}

	/**
	 * Returns the list of states for FR.
	 *
	 * @since 2.0.11
	 * @return array The list of state/provinces for the country.
	 */
	protected function states() {

		return [
			'10'  => __('Aube', 'multisite-ultimate'),
			'11'  => __('Aude', 'multisite-ultimate'),
			'12'  => __('Aveyron', 'multisite-ultimate'),
			'13'  => __('Bouches-du-Rhône', 'multisite-ultimate'),
			'14'  => __('Calvados', 'multisite-ultimate'),
			'15'  => __('Cantal', 'multisite-ultimate'),
			'16'  => __('Charente', 'multisite-ultimate'),
			'17'  => __('Charente-Maritime', 'multisite-ultimate'),
			'18'  => __('Cher', 'multisite-ultimate'),
			'19'  => __('Corrèze', 'multisite-ultimate'),
			'21'  => __("Côte-d'Or", 'multisite-ultimate'),
			'22'  => __("Côtes-d'Armor", 'multisite-ultimate'),
			'23'  => __('Creuse', 'multisite-ultimate'),
			'24'  => __('Dordogne', 'multisite-ultimate'),
			'25'  => __('Doubs', 'multisite-ultimate'),
			'26'  => __('Drôme', 'multisite-ultimate'),
			'27'  => __('Eure', 'multisite-ultimate'),
			'28'  => __('Eure-et-Loir', 'multisite-ultimate'),
			'29'  => __('Finistère', 'multisite-ultimate'),
			'30'  => __('Gard', 'multisite-ultimate'),
			'31'  => __('Haute-Garonne', 'multisite-ultimate'),
			'32'  => __('Gers', 'multisite-ultimate'),
			'33'  => __('Gironde', 'multisite-ultimate'),
			'34'  => __('Hérault', 'multisite-ultimate'),
			'35'  => __('Ille-et-Vilaine', 'multisite-ultimate'),
			'36'  => __('Indre', 'multisite-ultimate'),
			'37'  => __('Indre-et-Loire', 'multisite-ultimate'),
			'38'  => __('Isère', 'multisite-ultimate'),
			'39'  => __('Jura', 'multisite-ultimate'),
			'40'  => __('Landes', 'multisite-ultimate'),
			'41'  => __('Loir-et-Cher', 'multisite-ultimate'),
			'42'  => __('Loire', 'multisite-ultimate'),
			'43'  => __('Haute-Loire', 'multisite-ultimate'),
			'44'  => __('Loire-Atlantique', 'multisite-ultimate'),
			'45'  => __('Loiret', 'multisite-ultimate'),
			'46'  => __('Lot', 'multisite-ultimate'),
			'47'  => __('Lot-et-Garonne', 'multisite-ultimate'),
			'48'  => __('Lozère', 'multisite-ultimate'),
			'49'  => __('Maine-et-Loire', 'multisite-ultimate'),
			'50'  => __('Manche', 'multisite-ultimate'),
			'51'  => __('Marne', 'multisite-ultimate'),
			'52'  => __('Haute-Marne', 'multisite-ultimate'),
			'53'  => __('Mayenne', 'multisite-ultimate'),
			'54'  => __('Meurthe-et-Moselle', 'multisite-ultimate'),
			'55'  => __('Meuse', 'multisite-ultimate'),
			'56'  => __('Morbihan', 'multisite-ultimate'),
			'57'  => __('Moselle', 'multisite-ultimate'),
			'58'  => __('Nièvre', 'multisite-ultimate'),
			'59'  => __('Nord', 'multisite-ultimate'),
			'60'  => __('Oise', 'multisite-ultimate'),
			'61'  => __('Orne', 'multisite-ultimate'),
			'62'  => __('Pas-de-Calais', 'multisite-ultimate'),
			'63'  => __('Puy-de-Dôme', 'multisite-ultimate'),
			'64'  => __('Pyrénées-Atlantiques', 'multisite-ultimate'),
			'65'  => __('Hautes-Pyrénées', 'multisite-ultimate'),
			'66'  => __('Pyrénées-Orientales', 'multisite-ultimate'),
			'67'  => __('Bas-Rhin', 'multisite-ultimate'),
			'68'  => __('Haut-Rhin', 'multisite-ultimate'),
			'69'  => __('Rhône', 'multisite-ultimate'),
			'70'  => __('Haute-Saône', 'multisite-ultimate'),
			'71'  => __('Saône-et-Loire', 'multisite-ultimate'),
			'72'  => __('Sarthe', 'multisite-ultimate'),
			'73'  => __('Savoie', 'multisite-ultimate'),
			'74'  => __('Haute-Savoie', 'multisite-ultimate'),
			'76'  => __('Seine-Maritime', 'multisite-ultimate'),
			'77'  => __('Seine-et-Marne', 'multisite-ultimate'),
			'78'  => __('Yvelines', 'multisite-ultimate'),
			'79'  => __('Deux-Sèvres', 'multisite-ultimate'),
			'80'  => __('Somme', 'multisite-ultimate'),
			'81'  => __('Tarn', 'multisite-ultimate'),
			'82'  => __('Tarn-et-Garonne', 'multisite-ultimate'),
			'83'  => __('Var', 'multisite-ultimate'),
			'84'  => __('Vaucluse', 'multisite-ultimate'),
			'85'  => __('Vendée', 'multisite-ultimate'),
			'86'  => __('Vienne', 'multisite-ultimate'),
			'87'  => __('Haute-Vienne', 'multisite-ultimate'),
			'88'  => __('Vosges', 'multisite-ultimate'),
			'89'  => __('Yonne', 'multisite-ultimate'),
			'90'  => __('Territoire de Belfort', 'multisite-ultimate'),
			'91'  => __('Essonne', 'multisite-ultimate'),
			'92'  => __('Hauts-de-Seine', 'multisite-ultimate'),
			'93'  => __('Seine-Saint-Denis', 'multisite-ultimate'),
			'94'  => __('Val-de-Marne', 'multisite-ultimate'),
			'95'  => __("Val-d'Oise", 'multisite-ultimate'),
			'971' => __('Guadeloupe', 'multisite-ultimate'),
			'972' => __('Martinique', 'multisite-ultimate'),
			'973' => __('French Guiana', 'multisite-ultimate'),
			'974' => __('La Réunion', 'multisite-ultimate'),
			'976' => __('Mayotte', 'multisite-ultimate'),
			'01'  => __('Ain', 'multisite-ultimate'),
			'02'  => __('Aisne', 'multisite-ultimate'),
			'03'  => __('Allier', 'multisite-ultimate'),
			'06'  => __('Alpes-Maritimes', 'multisite-ultimate'),
			'04'  => __('Alpes-de-Haute-Provence', 'multisite-ultimate'),
			'6AE' => __('Alsace', 'multisite-ultimate'),
			'08'  => __('Ardennes', 'multisite-ultimate'),
			'07'  => __('Ardèche', 'multisite-ultimate'),
			'09'  => __('Ariège', 'multisite-ultimate'),
			'ARA' => __('Auvergne-Rhône-Alpes', 'multisite-ultimate'),
			'BFC' => __('Bourgogne-Franche-Comté', 'multisite-ultimate'),
			'BRE' => __('Bretagne', 'multisite-ultimate'),
			'CVL' => __('Centre-Val de Loire', 'multisite-ultimate'),
			'CP'  => __('Clipperton', 'multisite-ultimate'),
			'20R' => __('Corse', 'multisite-ultimate'),
			'2A'  => __('Corse-du-Sud', 'multisite-ultimate'),
			'PF'  => __('French Polynesia', 'multisite-ultimate'),
			'TF'  => __('French Southern and Antarctic Lands', 'multisite-ultimate'),
			'GES' => __('Grand-Est', 'multisite-ultimate'),
			'2B'  => __('Haute-Corse', 'multisite-ultimate'),
			'05'  => __('Hautes-Alpes', 'multisite-ultimate'),
			'HDF' => __('Hauts-de-France', 'multisite-ultimate'),
			'69M' => __('Métropole de Lyon', 'multisite-ultimate'),
			'NOR' => __('Normandie', 'multisite-ultimate'),
			'NAQ' => __('Nouvelle-Aquitaine', 'multisite-ultimate'),
			'OCC' => __('Occitanie', 'multisite-ultimate'),
			'75C' => __('Paris', 'multisite-ultimate'),
			'PDL' => __('Pays-de-la-Loire', 'multisite-ultimate'),
			'PAC' => __('Provence-Alpes-Côte-d’Azur', 'multisite-ultimate'),
			'PM'  => __('Saint Pierre and Miquelon', 'multisite-ultimate'),
			'BL'  => __('Saint-Barthélemy', 'multisite-ultimate'),
			'MF'  => __('Saint-Martin', 'multisite-ultimate'),
			'WF'  => __('Wallis and Futuna', 'multisite-ultimate'),
			'IDF' => __('Île-de-France', 'multisite-ultimate'),
		];
	}
}
