<?php // phpcs:ignore - @generation-checksum TR-81-1347
/**
 * Country Class for Turkey (TR).
 *
 * State/province count: 81
 * City count: 1347
 * City count per state/province:
 * - 77: 12 cities
 * - 73: 38 cities
 * - 72: 23 cities
 * - 66: 15 cities
 * - 65: 15 cities
 * - 64: 12 cities
 * - 63: 31 cities
 * - 62: 11 cities
 * - 61: 19 cities
 * - 60: 12 cities
 * - 59: 16 cities
 * - 58: 19 cities
 * - 56: 22 cities
 * - 55: 18 cities
 * - 54: 17 cities
 * - 53: 11 cities
 * - 52: 21 cities
 * - 50: 10 cities
 * - 48: 26 cities
 * - 47: 64 cities
 * - 46: 14 cities
 * - 45: 19 cities
 * - 44: 14 cities
 * - 43: 13 cities
 * - 42: 38 cities
 * - 41: 25 cities
 * - 38: 18 cities
 * - 37: 20 cities
 * - 35: 43 cities
 * - 34: 40 cities
 * - 33: 18 cities
 * - 32: 15 cities
 * - 31: 40 cities
 * - 28: 17 cities
 * - 27: 15 cities
 * - 26: 18 cities
 * - 25: 22 cities
 * - 24: 10 cities
 * - 23: 13 cities
 * - 22: 10 cities
 * - 21: 28 cities
 * - 20: 24 cities
 * - 19: 15 cities
 * - 18: 12 cities
 * - 17: 18 cities
 * - 16: 39 cities
 * - 15: 14 cities
 * - 11: 11 cities
 * - 10: 21 cities
 * - 09: 25 cities
 * - 81: 8 cities
 * - 08: 10 cities
 * - 80: 7 cities
 * - 79: 4 cities
 * - 78: 7 cities
 * - 76: 3 cities
 * - 75: 6 cities
 * - 74: 4 cities
 * - 07: 37 cities
 * - 71: 9 cities
 * - 70: 7 cities
 * - 69: 4 cities
 * - 68: 9 cities
 * - 67: 8 cities
 * - 06: 30 cities
 * - 57: 9 cities
 * - 51: 6 cities
 * - 49: 7 cities
 * - 40: 7 cities
 * - 39: 9 cities
 * - 36: 8 cities
 * - 03: 20 cities
 * - 30: 6 cities
 * - 29: 9 cities
 * - 02: 11 cities
 * - 14: 9 cities
 * - 13: 9 cities
 * - 12: 9 cities
 * - 01: 17 cities
 * - 05: 9 cities
 * - 04: 8 cities
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

namespace WP_Ultimo\Country;

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * Country Class for Turkey (TR).
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 *
 * @property-read string $code
 * @property-read string $currency
 * @property-read int $phone_code
 */
class Country_TR extends Country {

	use \WP_Ultimo\Traits\Singleton;

	/**
	 * General country attributes.
	 *
	 * This might be useful, might be not.
	 * In case of doubt, keep it.
	 *
	 * @since 2.0.11
	 * @var array
	 */
	protected $attributes = [
		'country_code' => 'TR',
		'currency'     => 'TRY',
		'phone_code'   => 90,
	];

	/**
	 * The type of nomenclature used to refer to the country sub-divisions.
	 *
	 * @since 2.0.11
	 * @var string
	 */
	protected $state_type = 'unknown';

	/**
	 * Return the country name.
	 *
	 * @since 2.0.11
	 * @return string
	 */
	public function get_name() {

		return __('Turkey', 'multisite-ultimate');
	}

	/**
	 * Returns the list of states for TR.
	 *
	 * @since 2.0.11
	 * @return array The list of state/provinces for the country.
	 */
	protected function states() {

		return [
			'10' => __('Balıkesir', 'multisite-ultimate'),
			'11' => __('Bilecik', 'multisite-ultimate'),
			'12' => __('Bingöl', 'multisite-ultimate'),
			'13' => __('Bitlis', 'multisite-ultimate'),
			'14' => __('Bolu', 'multisite-ultimate'),
			'15' => __('Burdur', 'multisite-ultimate'),
			'16' => __('Bursa', 'multisite-ultimate'),
			'17' => __('Çanakkale', 'multisite-ultimate'),
			'18' => __('Çankırı', 'multisite-ultimate'),
			'19' => __('Çorum', 'multisite-ultimate'),
			'20' => __('Denizli', 'multisite-ultimate'),
			'21' => __('Diyarbakır', 'multisite-ultimate'),
			'22' => __('Edirne', 'multisite-ultimate'),
			'23' => __('Elazığ', 'multisite-ultimate'),
			'24' => __('Erzincan', 'multisite-ultimate'),
			'25' => __('Erzurum', 'multisite-ultimate'),
			'26' => __('Eskişehir', 'multisite-ultimate'),
			'27' => __('Gaziantep', 'multisite-ultimate'),
			'28' => __('Giresun', 'multisite-ultimate'),
			'29' => __('Gümüşhane', 'multisite-ultimate'),
			'30' => __('Hakkâri', 'multisite-ultimate'),
			'31' => __('Hatay', 'multisite-ultimate'),
			'32' => __('Isparta', 'multisite-ultimate'),
			'33' => __('Mersin', 'multisite-ultimate'),
			'34' => __('Istanbul', 'multisite-ultimate'),
			'35' => __('İzmir', 'multisite-ultimate'),
			'36' => __('Kars', 'multisite-ultimate'),
			'37' => __('Kastamonu', 'multisite-ultimate'),
			'38' => __('Kayseri', 'multisite-ultimate'),
			'39' => __('Kırklareli', 'multisite-ultimate'),
			'40' => __('Kırşehir', 'multisite-ultimate'),
			'41' => __('Kocaeli', 'multisite-ultimate'),
			'42' => __('Konya', 'multisite-ultimate'),
			'43' => __('Kütahya', 'multisite-ultimate'),
			'44' => __('Malatya', 'multisite-ultimate'),
			'45' => __('Manisa', 'multisite-ultimate'),
			'46' => __('Kahramanmaraş', 'multisite-ultimate'),
			'47' => __('Mardin', 'multisite-ultimate'),
			'48' => __('Muğla', 'multisite-ultimate'),
			'49' => __('Muş', 'multisite-ultimate'),
			'50' => __('Nevşehir', 'multisite-ultimate'),
			'51' => __('Niğde', 'multisite-ultimate'),
			'52' => __('Ordu', 'multisite-ultimate'),
			'53' => __('Rize', 'multisite-ultimate'),
			'54' => __('Sakarya', 'multisite-ultimate'),
			'55' => __('Samsun', 'multisite-ultimate'),
			'56' => __('Siirt', 'multisite-ultimate'),
			'57' => __('Sinop', 'multisite-ultimate'),
			'58' => __('Sivas', 'multisite-ultimate'),
			'59' => __('Tekirdağ', 'multisite-ultimate'),
			'60' => __('Tokat', 'multisite-ultimate'),
			'61' => __('Trabzon', 'multisite-ultimate'),
			'62' => __('Tunceli', 'multisite-ultimate'),
			'63' => __('Şanlıurfa', 'multisite-ultimate'),
			'64' => __('Uşak', 'multisite-ultimate'),
			'65' => __('Van', 'multisite-ultimate'),
			'66' => __('Yozgat', 'multisite-ultimate'),
			'67' => __('Zonguldak', 'multisite-ultimate'),
			'68' => __('Aksaray', 'multisite-ultimate'),
			'69' => __('Bayburt', 'multisite-ultimate'),
			'70' => __('Karaman', 'multisite-ultimate'),
			'71' => __('Kırıkkale', 'multisite-ultimate'),
			'72' => __('Batman', 'multisite-ultimate'),
			'73' => __('Şırnak', 'multisite-ultimate'),
			'74' => __('Bartın', 'multisite-ultimate'),
			'75' => __('Ardahan', 'multisite-ultimate'),
			'76' => __('Iğdır', 'multisite-ultimate'),
			'77' => __('Yalova', 'multisite-ultimate'),
			'78' => __('Karabük', 'multisite-ultimate'),
			'79' => __('Kilis', 'multisite-ultimate'),
			'80' => __('Osmaniye', 'multisite-ultimate'),
			'81' => __('Düzce', 'multisite-ultimate'),
			'01' => __('Adana', 'multisite-ultimate'),
			'02' => __('Adıyaman', 'multisite-ultimate'),
			'03' => __('Afyonkarahisar', 'multisite-ultimate'),
			'05' => __('Amasya', 'multisite-ultimate'),
			'06' => __('Ankara', 'multisite-ultimate'),
			'07' => __('Antalya', 'multisite-ultimate'),
			'08' => __('Artvin', 'multisite-ultimate'),
			'09' => __('Aydın', 'multisite-ultimate'),
			'04' => __('Ağrı', 'multisite-ultimate'),
		];
	}
}
