<?php // phpcs:ignore - @generation-checksum TR-03-20
/**
 * State City List for 03 - TR.
 *
 * City count: 20
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 03 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Afyonkarahisar', 'wp-ultimo-locations'),
	__('Bayat', 'wp-ultimo-locations'),
	__('Başmakçı', 'wp-ultimo-locations'),
	__('Bolvadin', 'wp-ultimo-locations'),
	__('Dazkırı', 'wp-ultimo-locations'),
	__('Dinar', 'wp-ultimo-locations'),
	__('Emirdağ', 'wp-ultimo-locations'),
	__('Evciler', 'wp-ultimo-locations'),
	__('Hocalar', 'wp-ultimo-locations'),
	__('Işıklar', 'wp-ultimo-locations'),
	__('Kızılören', 'wp-ultimo-locations'),
	__('Merkez', 'wp-ultimo-locations'),
	__('Sandıklı', 'wp-ultimo-locations'),
	__('Sinanpaşa', 'wp-ultimo-locations'),
	__('Sultandağı', 'wp-ultimo-locations'),
	__('Çay', 'wp-ultimo-locations'),
	__('Çobanlar İlçesi', 'wp-ultimo-locations'),
	__('İhsaniye', 'wp-ultimo-locations'),
	__('İscehisar', 'wp-ultimo-locations'),
	__('Şuhut', 'wp-ultimo-locations'),
);
