<?php // phpcs:ignore - @generation-checksum TR-09-25
/**
 * State City List for 09 - TR.
 *
 * City count: 25
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 09 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Acarlar', 'wp-ultimo-locations'),
	__('Atça', 'wp-ultimo-locations'),
	__('Aydın', 'wp-ultimo-locations'),
	__('Bozdoğan', 'wp-ultimo-locations'),
	__('Buharkent', 'wp-ultimo-locations'),
	__('Dalama', 'wp-ultimo-locations'),
	__('Davutlar', 'wp-ultimo-locations'),
	__('Didim', 'wp-ultimo-locations'),
	__('Efeler', 'wp-ultimo-locations'),
	__('Germencik', 'wp-ultimo-locations'),
	__('Karacasu', 'wp-ultimo-locations'),
	__('Karpuzlu', 'wp-ultimo-locations'),
	__('Koçarlı', 'wp-ultimo-locations'),
	__('Kuyucak', 'wp-ultimo-locations'),
	__('Kuşadası', 'wp-ultimo-locations'),
	__('Köşk', 'wp-ultimo-locations'),
	__('Nazilli', 'wp-ultimo-locations'),
	__('Sarıkemer', 'wp-ultimo-locations'),
	__('Sultanhisar', 'wp-ultimo-locations'),
	__('Söke', 'wp-ultimo-locations'),
	__('Tepecik', 'wp-ultimo-locations'),
	__('Yenipazar', 'wp-ultimo-locations'),
	__('Çine', 'wp-ultimo-locations'),
	__('İncirliova', 'wp-ultimo-locations'),
	__('İsabeyli', 'wp-ultimo-locations'),
);
