<?php // phpcs:ignore - @generation-checksum TR-12-9
/**
 * State City List for 12 - TR.
 *
 * City count: 9
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 12 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Adaklı İlçesi', 'wp-ultimo-locations'),
	__('Bingöl', 'wp-ultimo-locations'),
	__('Genç', 'wp-ultimo-locations'),
	__('Karlıova', 'wp-ultimo-locations'),
	__('Kiğı İlçesi', 'wp-ultimo-locations'),
	__('Merkez', 'wp-ultimo-locations'),
	__('Solhan', 'wp-ultimo-locations'),
	__('Yayladere', 'wp-ultimo-locations'),
	__('Yedisu', 'wp-ultimo-locations'),
);
