<?php // phpcs:ignore - @generation-checksum TR-13-9
/**
 * State City List for 13 - TR.
 *
 * City count: 9
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 13 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Adilcevaz', 'wp-ultimo-locations'),
	__('Ahlat', 'wp-ultimo-locations'),
	__('Beğendik', 'wp-ultimo-locations'),
	__('Bitlis', 'wp-ultimo-locations'),
	__('Güroymak', 'wp-ultimo-locations'),
	__('Hizan', 'wp-ultimo-locations'),
	__('Merkez', 'wp-ultimo-locations'),
	__('Mutki', 'wp-ultimo-locations'),
	__('Tatvan', 'wp-ultimo-locations'),
);
