<?php // phpcs:ignore - @generation-checksum TR-14-9
/**
 * State City List for 14 - TR.
 *
 * City count: 9
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 14 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bolu', 'wp-ultimo-locations'),
	__('Dörtdivan', 'wp-ultimo-locations'),
	__('Gerede', 'wp-ultimo-locations'),
	__('Göynük', 'wp-ultimo-locations'),
	__('Kıbrıscık', 'wp-ultimo-locations'),
	__('Mengen', 'wp-ultimo-locations'),
	__('Mudurnu', 'wp-ultimo-locations'),
	__('Seben', 'wp-ultimo-locations'),
	__('Yeniçağa', 'wp-ultimo-locations'),
);
