<?php // phpcs:ignore - @generation-checksum TR-16-39
/**
 * State City List for 16 - TR.
 *
 * City count: 39
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 16 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alanyurt', 'wp-ultimo-locations'),
	__('Balarim', 'wp-ultimo-locations'),
	__('Boyalıca', 'wp-ultimo-locations'),
	__('Bursa', 'wp-ultimo-locations'),
	__('Büyükorhan İlçesi', 'wp-ultimo-locations'),
	__('Cerrah', 'wp-ultimo-locations'),
	__('Demirtaş', 'wp-ultimo-locations'),
	__('Elbeyli', 'wp-ultimo-locations'),
	__('Gemlik', 'wp-ultimo-locations'),
	__('Gürsu', 'wp-ultimo-locations'),
	__('Hamzabey', 'wp-ultimo-locations'),
	__('Harmancık İlçesi', 'wp-ultimo-locations'),
	__('Karacabey', 'wp-ultimo-locations'),
	__('Karıncalı', 'wp-ultimo-locations'),
	__('Keles', 'wp-ultimo-locations'),
	__('Kestel', 'wp-ultimo-locations'),
	__('Kirazlı', 'wp-ultimo-locations'),
	__('Kurşunlu', 'wp-ultimo-locations'),
	__('Küçükkumla', 'wp-ultimo-locations'),
	__('Mudanya', 'wp-ultimo-locations'),
	__('Mustafakemalpaşa', 'wp-ultimo-locations'),
	__('Narlıca', 'wp-ultimo-locations'),
	__('Nilüfer', 'wp-ultimo-locations'),
	__('Orhaneli', 'wp-ultimo-locations'),
	__('Orhangazi', 'wp-ultimo-locations'),
	__('Osmangazi', 'wp-ultimo-locations'),
	__('Sölöz', 'wp-ultimo-locations'),
	__('Tacir', 'wp-ultimo-locations'),
	__('Tahtaköprü', 'wp-ultimo-locations'),
	__('Tatkavaklı', 'wp-ultimo-locations'),
	__('Umurbey', 'wp-ultimo-locations'),
	__('Yenice', 'wp-ultimo-locations'),
	__('Yeniköy', 'wp-ultimo-locations'),
	__('Yenişehir', 'wp-ultimo-locations'),
	__('Yıldırım İlçesi', 'wp-ultimo-locations'),
	__('Çakırca', 'wp-ultimo-locations'),
	__('Çakırlı', 'wp-ultimo-locations'),
	__('İnegol', 'wp-ultimo-locations'),
	__('İznik', 'wp-ultimo-locations'),
);
