<?php // phpcs:ignore - @generation-checksum TR-17-18
/**
 * State City List for 17 - TR.
 *
 * City count: 18
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 17 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ayvacık', 'wp-ultimo-locations'),
	__('Bayramiç İlçesi', 'wp-ultimo-locations'),
	__('Behram', 'wp-ultimo-locations'),
	__('Biga', 'wp-ultimo-locations'),
	__('Bozcaada', 'wp-ultimo-locations'),
	__('Eceabat', 'wp-ultimo-locations'),
	__('Ezine', 'wp-ultimo-locations'),
	__('Gelibolu', 'wp-ultimo-locations'),
	__('Geyikli', 'wp-ultimo-locations'),
	__('Gökçeada', 'wp-ultimo-locations'),
	__('Hamdibey', 'wp-ultimo-locations'),
	__('Kalkım', 'wp-ultimo-locations'),
	__('Lapseki', 'wp-ultimo-locations'),
	__('Lâpseki İlçesi', 'wp-ultimo-locations'),
	__('Merkez', 'wp-ultimo-locations'),
	__('Yenice', 'wp-ultimo-locations'),
	__('Çan', 'wp-ultimo-locations'),
	__('Çanakkale', 'wp-ultimo-locations'),
);
