<?php // phpcs:ignore - @generation-checksum TR-18-12
/**
 * State City List for 18 - TR.
 *
 * City count: 12
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 18 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Atkaracalar', 'wp-ultimo-locations'),
	__('Bayramören', 'wp-ultimo-locations'),
	__('Eldivan', 'wp-ultimo-locations'),
	__('Ilgaz', 'wp-ultimo-locations'),
	__('Khanjarah', 'wp-ultimo-locations'),
	__('Korgun', 'wp-ultimo-locations'),
	__('Kurşunlu', 'wp-ultimo-locations'),
	__('Kızılırmak', 'wp-ultimo-locations'),
	__('Orta', 'wp-ultimo-locations'),
	__('Yapraklı', 'wp-ultimo-locations'),
	__('Çerkeş', 'wp-ultimo-locations'),
	__('Şabanözü', 'wp-ultimo-locations'),
);
