<?php // phpcs:ignore - @generation-checksum TR-19-15
/**
 * State City List for 19 - TR.
 *
 * City count: 15
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 19 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alaca', 'wp-ultimo-locations'),
	__('Bayat', 'wp-ultimo-locations'),
	__('Boğazkale İlçesi', 'wp-ultimo-locations'),
	__('Dodurga', 'wp-ultimo-locations'),
	__('Kargı İlçesi', 'wp-ultimo-locations'),
	__('Laçin', 'wp-ultimo-locations'),
	__('Mecitözü', 'wp-ultimo-locations'),
	__('Merkez', 'wp-ultimo-locations'),
	__('Ortaköy', 'wp-ultimo-locations'),
	__('Osmancık', 'wp-ultimo-locations'),
	__('Oğuzlar İlçesi', 'wp-ultimo-locations'),
	__('Sungurlu', 'wp-ultimo-locations'),
	__('Uğurludağ', 'wp-ultimo-locations'),
	__('Çorum', 'wp-ultimo-locations'),
	__('İskilip', 'wp-ultimo-locations'),
);
