<?php // phpcs:ignore - @generation-checksum TR-21-28
/**
 * State City List for 21 - TR.
 *
 * City count: 28
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 21 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alacakaya İlçesi', 'wp-ultimo-locations'),
	__('Altınkum', 'wp-ultimo-locations'),
	__('Ambar', 'wp-ultimo-locations'),
	__('Aralık', 'wp-ultimo-locations'),
	__('Bağlar', 'wp-ultimo-locations'),
	__('Bismil', 'wp-ultimo-locations'),
	__('Dicle', 'wp-ultimo-locations'),
	__('Diyarbakır', 'wp-ultimo-locations'),
	__('Ergani', 'wp-ultimo-locations'),
	__('Eğil', 'wp-ultimo-locations'),
	__('Hani', 'wp-ultimo-locations'),
	__('Hazro', 'wp-ultimo-locations'),
	__('Kayapınar', 'wp-ultimo-locations'),
	__('Kazancı', 'wp-ultimo-locations'),
	__('Kerh', 'wp-ultimo-locations'),
	__('Kocaköy', 'wp-ultimo-locations'),
	__('Kulp', 'wp-ultimo-locations'),
	__('Köseli', 'wp-ultimo-locations'),
	__('Lice', 'wp-ultimo-locations'),
	__('Salat', 'wp-ultimo-locations'),
	__('Silvan', 'wp-ultimo-locations'),
	__('Sinanköy', 'wp-ultimo-locations'),
	__('Sur', 'wp-ultimo-locations'),
	__('Yaprakbaşı', 'wp-ultimo-locations'),
	__('Yenişehir', 'wp-ultimo-locations'),
	__('Çermik', 'wp-ultimo-locations'),
	__('Çüngüş', 'wp-ultimo-locations'),
	__('Çınar İlçesi', 'wp-ultimo-locations'),
);
