<?php // phpcs:ignore - @generation-checksum TR-22-10
/**
 * State City List for 22 - TR.
 *
 * City count: 10
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 22 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Edirne', 'wp-ultimo-locations'),
	__('Enez', 'wp-ultimo-locations'),
	__('Havsa', 'wp-ultimo-locations'),
	__('Keşan', 'wp-ultimo-locations'),
	__('Küplü', 'wp-ultimo-locations'),
	__('Lâlapaşa', 'wp-ultimo-locations'),
	__('Meriç', 'wp-ultimo-locations'),
	__('Süloğlu İlçesi', 'wp-ultimo-locations'),
	__('Uzunköprü', 'wp-ultimo-locations'),
	__('İpsala', 'wp-ultimo-locations'),
);
