<?php // phpcs:ignore - @generation-checksum TR-24-10
/**
 * State City List for 24 - TR.
 *
 * City count: 10
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 24 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Cimin', 'wp-ultimo-locations'),
	__('Erzincan', 'wp-ultimo-locations'),
	__('Kemah', 'wp-ultimo-locations'),
	__('Kemaliye', 'wp-ultimo-locations'),
	__('Otlukbeli', 'wp-ultimo-locations'),
	__('Refahiye', 'wp-ultimo-locations'),
	__('Tercan', 'wp-ultimo-locations'),
	__('Çayırlı İlçesi', 'wp-ultimo-locations'),
	__('Üzümlü İlçesi', 'wp-ultimo-locations'),
	__('İliç İlçesi', 'wp-ultimo-locations'),
);
