<?php // phpcs:ignore - @generation-checksum TR-28-17
/**
 * State City List for 28 - TR.
 *
 * City count: 17
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 28 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alucra İlçesi', 'wp-ultimo-locations'),
	__('Bulancak', 'wp-ultimo-locations'),
	__('Dereli', 'wp-ultimo-locations'),
	__('Doğankent', 'wp-ultimo-locations'),
	__('Espiye', 'wp-ultimo-locations'),
	__('Eynesil', 'wp-ultimo-locations'),
	__('Giresun', 'wp-ultimo-locations'),
	__('Görele', 'wp-ultimo-locations'),
	__('Güce İlçesi', 'wp-ultimo-locations'),
	__('Keşap', 'wp-ultimo-locations'),
	__('Merkez', 'wp-ultimo-locations'),
	__('Piraziz', 'wp-ultimo-locations'),
	__('Tirebolu', 'wp-ultimo-locations'),
	__('Yağlıdere İlçesi', 'wp-ultimo-locations'),
	__('Çamoluk İlçesi', 'wp-ultimo-locations'),
	__('Çanakçı', 'wp-ultimo-locations'),
	__('Şebin Karahisar', 'wp-ultimo-locations'),
);
