<?php // phpcs:ignore - @generation-checksum TR-29-9
/**
 * State City List for 29 - TR.
 *
 * City count: 9
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 29 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Evren', 'wp-ultimo-locations'),
	__('Gumushkhane', 'wp-ultimo-locations'),
	__('Kelkit', 'wp-ultimo-locations'),
	__('Köse', 'wp-ultimo-locations'),
	__('Kürtün', 'wp-ultimo-locations'),
	__('Merkez', 'wp-ultimo-locations'),
	__('Torul', 'wp-ultimo-locations'),
	__('Yağlıdere', 'wp-ultimo-locations'),
	__('Şiran', 'wp-ultimo-locations'),
);
