<?php // phpcs:ignore - @generation-checksum TR-30-6
/**
 * State City List for 30 - TR.
 *
 * City count: 6
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 30 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Hakkâri', 'wp-ultimo-locations'),
	__('Karsani', 'wp-ultimo-locations'),
	__('Yüksekova', 'wp-ultimo-locations'),
	__('Çukurca', 'wp-ultimo-locations'),
	__('Şemdinli', 'wp-ultimo-locations'),
	__('Şemdinni İlçesi', 'wp-ultimo-locations'),
);
