<?php // phpcs:ignore - @generation-checksum TR-31-40
/**
 * State City List for 31 - TR.
 *
 * City count: 40
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 31 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Altınözü', 'wp-ultimo-locations'),
	__('Anayazı', 'wp-ultimo-locations'),
	__('Antakya', 'wp-ultimo-locations'),
	__('Arsuz', 'wp-ultimo-locations'),
	__('Açıkdere', 'wp-ultimo-locations'),
	__('Aşağı Karafakılı', 'wp-ultimo-locations'),
	__('Aşağıokçular', 'wp-ultimo-locations'),
	__('Balıklıdere', 'wp-ultimo-locations'),
	__('Belen', 'wp-ultimo-locations'),
	__('Boynuyoğun', 'wp-ultimo-locations'),
	__('Büyük Dalyan', 'wp-ultimo-locations'),
	__('Büyükçat', 'wp-ultimo-locations'),
	__('Defne', 'wp-ultimo-locations'),
	__('Denizciler', 'wp-ultimo-locations'),
	__('Dursunlu', 'wp-ultimo-locations'),
	__('Dörtyol', 'wp-ultimo-locations'),
	__('Erzin', 'wp-ultimo-locations'),
	__('Gümüşgöze', 'wp-ultimo-locations'),
	__('Günyazı', 'wp-ultimo-locations'),
	__('Hacıpaşa', 'wp-ultimo-locations'),
	__('Hassa', 'wp-ultimo-locations'),
	__('Karasüleymanlı', 'wp-ultimo-locations'),
	__('Kastal', 'wp-ultimo-locations'),
	__('Kumlu İlçesi', 'wp-ultimo-locations'),
	__('Kuzeytepe', 'wp-ultimo-locations'),
	__('Kırıkhan', 'wp-ultimo-locations'),
	__('Kızkalesi', 'wp-ultimo-locations'),
	__('Kışlak', 'wp-ultimo-locations'),
	__('Mahmutlar', 'wp-ultimo-locations'),
	__('Payas', 'wp-ultimo-locations'),
	__('Reyhanlı', 'wp-ultimo-locations'),
	__('Samankaya', 'wp-ultimo-locations'),
	__('Serinyol', 'wp-ultimo-locations'),
	__('Tepehan', 'wp-ultimo-locations'),
	__('Toygarlı', 'wp-ultimo-locations'),
	__('Uzunbağ', 'wp-ultimo-locations'),
	__('Uzunkavak', 'wp-ultimo-locations'),
	__('Yayladağı', 'wp-ultimo-locations'),
	__('Çırtıman', 'wp-ultimo-locations'),
	__('İskenderun', 'wp-ultimo-locations'),
);
