<?php // phpcs:ignore - @generation-checksum TR-33-18
/**
 * State City List for 33 - TR.
 *
 * City count: 18
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 33 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akdeniz', 'wp-ultimo-locations'),
	__('Akdere', 'wp-ultimo-locations'),
	__('Anamur', 'wp-ultimo-locations'),
	__('Aydıncık', 'wp-ultimo-locations'),
	__('Bozyazı', 'wp-ultimo-locations'),
	__('Elvanlı', 'wp-ultimo-locations'),
	__('Erdemli', 'wp-ultimo-locations'),
	__('Gülnar', 'wp-ultimo-locations'),
	__('Kocahasanlı', 'wp-ultimo-locations'),
	__('Mersin', 'wp-ultimo-locations'),
	__('Mezitli İlçesi', 'wp-ultimo-locations'),
	__('Mut', 'wp-ultimo-locations'),
	__('Pınarbaşı', 'wp-ultimo-locations'),
	__('Silifke', 'wp-ultimo-locations'),
	__('Tarsus', 'wp-ultimo-locations'),
	__('Toroslar', 'wp-ultimo-locations'),
	__('Yenişehir', 'wp-ultimo-locations'),
	__('Çamlıyayla İlçesi', 'wp-ultimo-locations'),
);
