<?php // phpcs:ignore - @generation-checksum TR-35-43
/**
 * State City List for 35 - TR.
 *
 * City count: 43
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 35 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alaçatı', 'wp-ultimo-locations'),
	__('Aliağa', 'wp-ultimo-locations'),
	__('Bademli', 'wp-ultimo-locations'),
	__('Balçova', 'wp-ultimo-locations'),
	__('Bayraklı', 'wp-ultimo-locations'),
	__('Bayındır', 'wp-ultimo-locations'),
	__('Belevi', 'wp-ultimo-locations'),
	__('Bergama', 'wp-ultimo-locations'),
	__('Beydağ', 'wp-ultimo-locations'),
	__('Bornova', 'wp-ultimo-locations'),
	__('Buca', 'wp-ultimo-locations'),
	__('Dikili', 'wp-ultimo-locations'),
	__('Foça', 'wp-ultimo-locations'),
	__('Gaziemir', 'wp-ultimo-locations'),
	__('Gökçen', 'wp-ultimo-locations'),
	__('Güzelbahçe', 'wp-ultimo-locations'),
	__('Karabağlar', 'wp-ultimo-locations'),
	__('Karaburun', 'wp-ultimo-locations'),
	__('Karşıyaka İlçesi', 'wp-ultimo-locations'),
	__('Kaymakçı', 'wp-ultimo-locations'),
	__('Kemalpaşa', 'wp-ultimo-locations'),
	__('Kiraz', 'wp-ultimo-locations'),
	__('Konak', 'wp-ultimo-locations'),
	__('Konaklı', 'wp-ultimo-locations'),
	__('Kınık', 'wp-ultimo-locations'),
	__('Menderes', 'wp-ultimo-locations'),
	__('Menemen', 'wp-ultimo-locations'),
	__('Narlıdere', 'wp-ultimo-locations'),
	__('Seferihisar', 'wp-ultimo-locations'),
	__('Selçuk', 'wp-ultimo-locations'),
	__('Tire', 'wp-ultimo-locations'),
	__('Torbalı', 'wp-ultimo-locations'),
	__('Urla', 'wp-ultimo-locations'),
	__('Yenifoça', 'wp-ultimo-locations'),
	__('Yenişakran', 'wp-ultimo-locations'),
	__('Zeytindağ', 'wp-ultimo-locations'),
	__('Çandarlı', 'wp-ultimo-locations'),
	__('Çaylı', 'wp-ultimo-locations'),
	__('Çeşme', 'wp-ultimo-locations'),
	__('Çiğli', 'wp-ultimo-locations'),
	__('Ödemiş', 'wp-ultimo-locations'),
	__('Özdere', 'wp-ultimo-locations'),
	__('İzmir', 'wp-ultimo-locations'),
);
