<?php // phpcs:ignore - @generation-checksum TR-37-20
/**
 * State City List for 37 - TR.
 *
 * City count: 20
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 37 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Abana', 'wp-ultimo-locations'),
	__('Araç', 'wp-ultimo-locations'),
	__('Azdavay', 'wp-ultimo-locations'),
	__('Ağlı İlçesi', 'wp-ultimo-locations'),
	__('Bozkurt', 'wp-ultimo-locations'),
	__('Cide', 'wp-ultimo-locations'),
	__('Daday', 'wp-ultimo-locations'),
	__('Devrekani', 'wp-ultimo-locations'),
	__('Doğanyurt', 'wp-ultimo-locations'),
	__('Hanönü', 'wp-ultimo-locations'),
	__('Kastamonu', 'wp-ultimo-locations'),
	__('Küre', 'wp-ultimo-locations'),
	__('Pınarbaşı', 'wp-ultimo-locations'),
	__('Seydiler', 'wp-ultimo-locations'),
	__('Taşköprü', 'wp-ultimo-locations'),
	__('Tosya', 'wp-ultimo-locations'),
	__('Çatalzeytin İlçesi', 'wp-ultimo-locations'),
	__('İhsangazi', 'wp-ultimo-locations'),
	__('İnebolu', 'wp-ultimo-locations'),
	__('Şenpazar İlçesi', 'wp-ultimo-locations'),
);
