<?php // phpcs:ignore - @generation-checksum TR-40-7
/**
 * State City List for 40 - TR.
 *
 * City count: 7
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 40 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akpınar', 'wp-ultimo-locations'),
	__('Akçakent İlçesi', 'wp-ultimo-locations'),
	__('Boztepe İlçesi', 'wp-ultimo-locations'),
	__('Kaman', 'wp-ultimo-locations'),
	__('Kırşehir', 'wp-ultimo-locations'),
	__('Mucur', 'wp-ultimo-locations'),
	__('Çiçekdağı', 'wp-ultimo-locations'),
);
