<?php // phpcs:ignore - @generation-checksum TR-41-25
/**
 * State City List for 41 - TR.
 *
 * City count: 25
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 41 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bahçecik', 'wp-ultimo-locations'),
	__('Balçık', 'wp-ultimo-locations'),
	__('Başiskele', 'wp-ultimo-locations'),
	__('Darıca', 'wp-ultimo-locations'),
	__('Derince', 'wp-ultimo-locations'),
	__('Dilovası', 'wp-ultimo-locations'),
	__('Gebze', 'wp-ultimo-locations'),
	__('Gölcük', 'wp-ultimo-locations'),
	__('Halıdere', 'wp-ultimo-locations'),
	__('Kandıra', 'wp-ultimo-locations'),
	__('Karamürsel', 'wp-ultimo-locations'),
	__('Kartepe', 'wp-ultimo-locations'),
	__('Karşıyaka', 'wp-ultimo-locations'),
	__('Kefken', 'wp-ultimo-locations'),
	__('Kullar', 'wp-ultimo-locations'),
	__('Körfez', 'wp-ultimo-locations'),
	__('Köseköy', 'wp-ultimo-locations'),
	__('Tavşancıl', 'wp-ultimo-locations'),
	__('Tavşanlı', 'wp-ultimo-locations'),
	__('Ulaşlı', 'wp-ultimo-locations'),
	__('Yalakdere', 'wp-ultimo-locations'),
	__('Yuvacık', 'wp-ultimo-locations'),
	__('Çayırova', 'wp-ultimo-locations'),
	__('İhsaniye', 'wp-ultimo-locations'),
	__('İzmit', 'wp-ultimo-locations'),
);
