<?php // phpcs:ignore - @generation-checksum TR-42-38
/**
 * State City List for 42 - TR.
 *
 * City count: 38
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 42 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ahırlı İlçesi', 'wp-ultimo-locations'),
	__('Akören İlçesi', 'wp-ultimo-locations'),
	__('Akşehir', 'wp-ultimo-locations'),
	__('Altınekin', 'wp-ultimo-locations'),
	__('Beyşehir', 'wp-ultimo-locations'),
	__('Bozkır', 'wp-ultimo-locations'),
	__('Cihanbeyli', 'wp-ultimo-locations'),
	__('Cihanbeyli District', 'wp-ultimo-locations'),
	__('Derbent', 'wp-ultimo-locations'),
	__('Derebucak', 'wp-ultimo-locations'),
	__('Doğanhisar', 'wp-ultimo-locations'),
	__('Emirgazi', 'wp-ultimo-locations'),
	__('Ereğli', 'wp-ultimo-locations'),
	__('Güneysınır İlçesi', 'wp-ultimo-locations'),
	__('Hadim', 'wp-ultimo-locations'),
	__('Halkapınar', 'wp-ultimo-locations'),
	__('Hüyük', 'wp-ultimo-locations'),
	__('Ilgın', 'wp-ultimo-locations'),
	__('Kadınhanı', 'wp-ultimo-locations'),
	__('Karapınar', 'wp-ultimo-locations'),
	__('Karatay', 'wp-ultimo-locations'),
	__('Konya', 'wp-ultimo-locations'),
	__('Kulu', 'wp-ultimo-locations'),
	__('Kuyulusebil', 'wp-ultimo-locations'),
	__('Meram İlçesi', 'wp-ultimo-locations'),
	__('Ovakavağı', 'wp-ultimo-locations'),
	__('Sarayönü', 'wp-ultimo-locations'),
	__('Selcuklu', 'wp-ultimo-locations'),
	__('Seydişehir', 'wp-ultimo-locations'),
	__('Taşkent', 'wp-ultimo-locations'),
	__('Tuzlukçu', 'wp-ultimo-locations'),
	__('Yalıhüyük', 'wp-ultimo-locations'),
	__('Yarma', 'wp-ultimo-locations'),
	__('Yeniceoba', 'wp-ultimo-locations'),
	__('Yunak', 'wp-ultimo-locations'),
	__('Çatalhöyük', 'wp-ultimo-locations'),
	__('Çeltik İlçesi', 'wp-ultimo-locations'),
	__('Çumra', 'wp-ultimo-locations'),
);
