<?php // phpcs:ignore - @generation-checksum TR-43-13
/**
 * State City List for 43 - TR.
 *
 * City count: 13
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 43 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Altıntaş İlçesi', 'wp-ultimo-locations'),
	__('Aslanapa', 'wp-ultimo-locations'),
	__('Domaniç', 'wp-ultimo-locations'),
	__('Dumlupınar', 'wp-ultimo-locations'),
	__('Emet', 'wp-ultimo-locations'),
	__('Gediz', 'wp-ultimo-locations'),
	__('Hisarcık İlçesi', 'wp-ultimo-locations'),
	__('Kütahya', 'wp-ultimo-locations'),
	__('Pazarlar', 'wp-ultimo-locations'),
	__('Simav', 'wp-ultimo-locations'),
	__('Tavşanlı', 'wp-ultimo-locations'),
	__('Çavdarhisar İlçesi', 'wp-ultimo-locations'),
	__('Şaphane', 'wp-ultimo-locations'),
);
