<?php // phpcs:ignore - @generation-checksum TR-48-26
/**
 * State City List for 48 - TR.
 *
 * City count: 26
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 48 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Bayır', 'wp-ultimo-locations'),
	__('Bodrum', 'wp-ultimo-locations'),
	__('Bozarmut', 'wp-ultimo-locations'),
	__('Dalaman', 'wp-ultimo-locations'),
	__('Dalyan', 'wp-ultimo-locations'),
	__('Datça', 'wp-ultimo-locations'),
	__('Fethiye', 'wp-ultimo-locations'),
	__('Göcek', 'wp-ultimo-locations'),
	__('Güvercinlik', 'wp-ultimo-locations'),
	__('Kargı', 'wp-ultimo-locations'),
	__('Kavaklıdere', 'wp-ultimo-locations'),
	__('Köyceğiz İlçesi', 'wp-ultimo-locations'),
	__('Marmaris', 'wp-ultimo-locations'),
	__('Menteşe', 'wp-ultimo-locations'),
	__('Milas', 'wp-ultimo-locations'),
	__('Muğla', 'wp-ultimo-locations'),
	__('Ortaca', 'wp-ultimo-locations'),
	__('Sarigerme', 'wp-ultimo-locations'),
	__('Seydikemer', 'wp-ultimo-locations'),
	__('Turgut', 'wp-ultimo-locations'),
	__('Turgutreis', 'wp-ultimo-locations'),
	__('Ula', 'wp-ultimo-locations'),
	__('Yalıkavak', 'wp-ultimo-locations'),
	__('Yaniklar', 'wp-ultimo-locations'),
	__('Yatağan', 'wp-ultimo-locations'),
	__('Ölüdeniz', 'wp-ultimo-locations'),
);
