<?php // phpcs:ignore - @generation-checksum TR-55-18
/**
 * State City List for 55 - TR.
 *
 * City count: 18
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 55 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alaçam İlçesi', 'wp-ultimo-locations'),
	__('Asarcık', 'wp-ultimo-locations'),
	__('Atakum', 'wp-ultimo-locations'),
	__('Ayvacık', 'wp-ultimo-locations'),
	__('Bafra', 'wp-ultimo-locations'),
	__('Canik', 'wp-ultimo-locations'),
	__('Havza', 'wp-ultimo-locations'),
	__('Kavak', 'wp-ultimo-locations'),
	__('Ladik', 'wp-ultimo-locations'),
	__('Ondokuzmayıs İlçesi', 'wp-ultimo-locations'),
	__('Salıpazarı İlçesi', 'wp-ultimo-locations'),
	__('Samsun', 'wp-ultimo-locations'),
	__('Tekkeköy', 'wp-ultimo-locations'),
	__('Terme', 'wp-ultimo-locations'),
	__('Vezirköprü', 'wp-ultimo-locations'),
	__('Yakakent', 'wp-ultimo-locations'),
	__('Çarşamba', 'wp-ultimo-locations'),
	__('İlkadım', 'wp-ultimo-locations'),
);
