<?php // phpcs:ignore - @generation-checksum TR-59-16
/**
 * State City List for 59 - TR.
 *
 * City count: 16
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 59 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ergene', 'wp-ultimo-locations'),
	__('Hayrabolu', 'wp-ultimo-locations'),
	__('Kapaklı', 'wp-ultimo-locations'),
	__('Kumbağ', 'wp-ultimo-locations'),
	__('Malkara', 'wp-ultimo-locations'),
	__('Marmara Ereğlisi', 'wp-ultimo-locations'),
	__('Marmaracık', 'wp-ultimo-locations'),
	__('Muratlı İlçesi', 'wp-ultimo-locations'),
	__('Saray', 'wp-ultimo-locations'),
	__('Sultanköy', 'wp-ultimo-locations'),
	__('Süleymanpaşa', 'wp-ultimo-locations'),
	__('Tekirdağ', 'wp-ultimo-locations'),
	__('Velimeşe', 'wp-ultimo-locations'),
	__('Çerkezköy', 'wp-ultimo-locations'),
	__('Çorlu', 'wp-ultimo-locations'),
	__('Şarköy İlçesi', 'wp-ultimo-locations'),
);
