<?php // phpcs:ignore - @generation-checksum TR-61-19
/**
 * State City List for 61 - TR.
 *
 * City count: 19
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 61 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akçaabat', 'wp-ultimo-locations'),
	__('Araklı', 'wp-ultimo-locations'),
	__('Arsin', 'wp-ultimo-locations'),
	__('Beşikdüzü', 'wp-ultimo-locations'),
	__('Dernekpazarı', 'wp-ultimo-locations'),
	__('Düzköy', 'wp-ultimo-locations'),
	__('Hayrat', 'wp-ultimo-locations'),
	__('Köprübaşı', 'wp-ultimo-locations'),
	__('Maçka', 'wp-ultimo-locations'),
	__('Of', 'wp-ultimo-locations'),
	__('Ortahisar', 'wp-ultimo-locations'),
	__('Sürmene', 'wp-ultimo-locations'),
	__('Tonya', 'wp-ultimo-locations'),
	__('Trabzon', 'wp-ultimo-locations'),
	__('Vakfıkebir', 'wp-ultimo-locations'),
	__('Yomra', 'wp-ultimo-locations'),
	__('Çarşıbaşı', 'wp-ultimo-locations'),
	__('Çaykara', 'wp-ultimo-locations'),
	__('Şalpazarı', 'wp-ultimo-locations'),
);
