<?php // phpcs:ignore - @generation-checksum TR-63-31
/**
 * State City List for 63 - TR.
 *
 * City count: 31
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 63 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Akdiken', 'wp-ultimo-locations'),
	__('Akçakale', 'wp-ultimo-locations'),
	__('Aşağı Beğdeş', 'wp-ultimo-locations'),
	__('Birecik', 'wp-ultimo-locations'),
	__('Bozova', 'wp-ultimo-locations'),
	__('Bulutlu', 'wp-ultimo-locations'),
	__('Ceylanpınar', 'wp-ultimo-locations'),
	__('Dorumali', 'wp-ultimo-locations'),
	__('Eyyübiye', 'wp-ultimo-locations'),
	__('Güneren', 'wp-ultimo-locations'),
	__('Halfeti', 'wp-ultimo-locations'),
	__('Haliliye', 'wp-ultimo-locations'),
	__('Hanköy', 'wp-ultimo-locations'),
	__('Harran', 'wp-ultimo-locations'),
	__('Hilvan', 'wp-ultimo-locations'),
	__('Işıklar', 'wp-ultimo-locations'),
	__('Karaköprü', 'wp-ultimo-locations'),
	__('Koyunluca', 'wp-ultimo-locations'),
	__('Küçükkendirci', 'wp-ultimo-locations'),
	__('Mağaralı', 'wp-ultimo-locations'),
	__('Meydankapı', 'wp-ultimo-locations'),
	__('Minare', 'wp-ultimo-locations'),
	__('Muratlı', 'wp-ultimo-locations'),
	__('Pekmezli', 'wp-ultimo-locations'),
	__('Seksenören', 'wp-ultimo-locations'),
	__('Siverek', 'wp-ultimo-locations'),
	__('Suruç', 'wp-ultimo-locations'),
	__('Viranşehir', 'wp-ultimo-locations'),
	__('Yukarı Taşyalak', 'wp-ultimo-locations'),
	__('Öncül', 'wp-ultimo-locations'),
	__('Şanlıurfa', 'wp-ultimo-locations'),
);
