<?php // phpcs:ignore - @generation-checksum TR-67-8
/**
 * State City List for 67 - TR.
 *
 * City count: 8
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 67 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Alaplı', 'wp-ultimo-locations'),
	__('Devrek', 'wp-ultimo-locations'),
	__('Ereğli', 'wp-ultimo-locations'),
	__('Gökçebey İlçesi', 'wp-ultimo-locations'),
	__('Kilimli', 'wp-ultimo-locations'),
	__('Kozlu', 'wp-ultimo-locations'),
	__('Zonguldak', 'wp-ultimo-locations'),
	__('Çaycuma', 'wp-ultimo-locations'),
);
