<?php // phpcs:ignore - @generation-checksum TR-72-23
/**
 * State City List for 72 - TR.
 *
 * City count: 23
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 72 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Aviski', 'wp-ultimo-locations'),
	__('Aydınkonak', 'wp-ultimo-locations'),
	__('Balpınar', 'wp-ultimo-locations'),
	__('Batman', 'wp-ultimo-locations'),
	__('Beşiri', 'wp-ultimo-locations'),
	__('Beşpınar', 'wp-ultimo-locations'),
	__('Binatlı', 'wp-ultimo-locations'),
	__('Demiryol', 'wp-ultimo-locations'),
	__('Doğankavak', 'wp-ultimo-locations'),
	__('Erköklü', 'wp-ultimo-locations'),
	__('Gercüş İlçesi', 'wp-ultimo-locations'),
	__('Gerdzhyush', 'wp-ultimo-locations'),
	__('Hasankeyf', 'wp-ultimo-locations'),
	__('Hisar', 'wp-ultimo-locations'),
	__('Kayapınar', 'wp-ultimo-locations'),
	__('Kozluk İlçesi', 'wp-ultimo-locations'),
	__('Merkez', 'wp-ultimo-locations'),
	__('Oymataş', 'wp-ultimo-locations'),
	__('Sason', 'wp-ultimo-locations'),
	__('Yeniköy', 'wp-ultimo-locations'),
	__('Yenipınar', 'wp-ultimo-locations'),
	__('Yolağzı', 'wp-ultimo-locations'),
	__('Çevrimova', 'wp-ultimo-locations'),
);
