<?php // phpcs:ignore - @generation-checksum TR-74-4
/**
 * State City List for 74 - TR.
 *
 * City count: 4
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 74 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Amasra', 'wp-ultimo-locations'),
	__('Bartın', 'wp-ultimo-locations'),
	__('Kurucaşile', 'wp-ultimo-locations'),
	__('Ulus İlçesi', 'wp-ultimo-locations'),
);
