<?php // phpcs:ignore - @generation-checksum TR-75-6
/**
 * State City List for 75 - TR.
 *
 * City count: 6
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 75 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Ardahan', 'wp-ultimo-locations'),
	__('Damal', 'wp-ultimo-locations'),
	__('Göle', 'wp-ultimo-locations'),
	__('Hanak', 'wp-ultimo-locations'),
	__('Posof', 'wp-ultimo-locations'),
	__('Çıldır İlçesi', 'wp-ultimo-locations'),
);
