<?php // phpcs:ignore - @generation-checksum TR-79-4
/**
 * State City List for 79 - TR.
 *
 * City count: 4
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 79 - TR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Elbeyli', 'wp-ultimo-locations'),
	__('Kilis', 'wp-ultimo-locations'),
	__('Musabeyli', 'wp-ultimo-locations'),
	__('Polateli İlçesi', 'wp-ultimo-locations'),
);
