<?php // phpcs:ignore - @generation-checksum FR-20R-51
/**
 * State City List for 20R - FR.
 *
 * City count: 51
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for 20R - FR.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Afa', 'wp-ultimo-locations'),
	__('Ajaccio', 'wp-ultimo-locations'),
	__('Alata', 'wp-ultimo-locations'),
	__('Albitreccia', 'wp-ultimo-locations'),
	__('Aléria', 'wp-ultimo-locations'),
	__('Appietto', 'wp-ultimo-locations'),
	__('Bastia', 'wp-ultimo-locations'),
	__('Biguglia', 'wp-ultimo-locations'),
	__('Bonifacio', 'wp-ultimo-locations'),
	__('Borgo', 'wp-ultimo-locations'),
	__('Brando', 'wp-ultimo-locations'),
	__('Calenzana', 'wp-ultimo-locations'),
	__('Calvi', 'wp-ultimo-locations'),
	__('Cargèse', 'wp-ultimo-locations'),
	__('Cauro', 'wp-ultimo-locations'),
	__('Cervione', 'wp-ultimo-locations'),
	__('Corte', 'wp-ultimo-locations'),
	__('Cuttoli-Corticchiato', 'wp-ultimo-locations'),
	__('Département de la Corse-du-Sud', 'wp-ultimo-locations'),
	__('Département de la Haute-Corse', 'wp-ultimo-locations'),
	__('Figari', 'wp-ultimo-locations'),
	__('Furiani', 'wp-ultimo-locations'),
	__('Ghisonaccia', 'wp-ultimo-locations'),
	__('Grosseto-Prugna', 'wp-ultimo-locations'),
	__("L'Île-Rousse", 'wp-ultimo-locations'),
	__('Linguizzetta', 'wp-ultimo-locations'),
	__('Lucciana', 'wp-ultimo-locations'),
	__('Lumio', 'wp-ultimo-locations'),
	__('Monticello', 'wp-ultimo-locations'),
	__('Morosaglia', 'wp-ultimo-locations'),
	__('Oletta', 'wp-ultimo-locations'),
	__('Olmeto', 'wp-ultimo-locations'),
	__('Penta-di-Casinca', 'wp-ultimo-locations'),
	__('Peri', 'wp-ultimo-locations'),
	__('Pietranera', 'wp-ultimo-locations'),
	__('Pietrosella', 'wp-ultimo-locations'),
	__('Porto-Vecchio', 'wp-ultimo-locations'),
	__('Propriano', 'wp-ultimo-locations'),
	__('Prunelli-di-Fiumorbo', 'wp-ultimo-locations'),
	__('Saint-Florent', 'wp-ultimo-locations'),
	__('San-Martino-di-Lota', 'wp-ultimo-locations'),
	__('San-Nicolao', 'wp-ultimo-locations'),
	__('Santa-Lucia-di-Moriani', 'wp-ultimo-locations'),
	__('Santa-Maria-di-Lota', 'wp-ultimo-locations'),
	__('Sari-Solenzara', 'wp-ultimo-locations'),
	__('Sarrola', 'wp-ultimo-locations'),
	__('Sartène', 'wp-ultimo-locations'),
	__('Sisco', 'wp-ultimo-locations'),
	__('Ventiseri', 'wp-ultimo-locations'),
	__('Vescovato', 'wp-ultimo-locations'),
	__('Zonza', 'wp-ultimo-locations'),
);
