<?php // phpcs:ignore - @generation-checksum CN-AH-37
/**
 * State City List for AH - CN.
 *
 * City count: 37
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for AH - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Anqing', 'wp-ultimo-locations'),
	__('Anqing Shi', 'wp-ultimo-locations'),
	__('Bengbu', 'wp-ultimo-locations'),
	__('Bozhou', 'wp-ultimo-locations'),
	__('Chaohu', 'wp-ultimo-locations'),
	__('Chizhou', 'wp-ultimo-locations'),
	__('Chizhou Shi', 'wp-ultimo-locations'),
	__('Chuzhou', 'wp-ultimo-locations'),
	__('Chuzhou Shi', 'wp-ultimo-locations'),
	__('Datong', 'wp-ultimo-locations'),
	__('Fuyang', 'wp-ultimo-locations'),
	__('Fuyang Shi', 'wp-ultimo-locations'),
	__('Gushu', 'wp-ultimo-locations'),
	__('Hefei', 'wp-ultimo-locations'),
	__('Hefei Shi', 'wp-ultimo-locations'),
	__('Huaibei', 'wp-ultimo-locations'),
	__('Huainan', 'wp-ultimo-locations'),
	__('Huainan Shi', 'wp-ultimo-locations'),
	__('Huaiyuan Chengguanzhen', 'wp-ultimo-locations'),
	__('Huangshan', 'wp-ultimo-locations'),
	__('Huangshan Shi', 'wp-ultimo-locations'),
	__('Huoqiu Chengguanzhen', 'wp-ultimo-locations'),
	__('Jieshou', 'wp-ultimo-locations'),
	__('Lucheng', 'wp-ultimo-locations'),
	__('Lu’an', 'wp-ultimo-locations'),
	__('Mengcheng Chengguanzhen', 'wp-ultimo-locations'),
	__('Mingguang', 'wp-ultimo-locations'),
	__('Suixi', 'wp-ultimo-locations'),
	__('Suzhou', 'wp-ultimo-locations'),
	__('Suzhou Shi', 'wp-ultimo-locations'),
	__('Tangzhai', 'wp-ultimo-locations'),
	__('Wucheng', 'wp-ultimo-locations'),
	__('Wuhu', 'wp-ultimo-locations'),
	__('Wusong', 'wp-ultimo-locations'),
	__('Wuyang', 'wp-ultimo-locations'),
	__('Xuanzhou', 'wp-ultimo-locations'),
	__('Yingshang Chengguanzhen', 'wp-ultimo-locations'),
);
