<?php // phpcs:ignore - @generation-checksum CN-BJ-8
/**
 * State City List for BJ - CN.
 *
 * City count: 8
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for BJ - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Beijing', 'wp-ultimo-locations'),
	__('Changping', 'wp-ultimo-locations'),
	__('Daxing', 'wp-ultimo-locations'),
	__('Fangshan', 'wp-ultimo-locations'),
	__('Liangxiang', 'wp-ultimo-locations'),
	__('Mentougou', 'wp-ultimo-locations'),
	__('Shunyi', 'wp-ultimo-locations'),
	__('Tongzhou', 'wp-ultimo-locations'),
);
