<?php // phpcs:ignore - @generation-checksum CN-HI-14
/**
 * State City List for HI - CN.
 *
 * City count: 14
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HI - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Basuo', 'wp-ultimo-locations'),
	__('Chongshan', 'wp-ultimo-locations'),
	__('Dadonghai', 'wp-ultimo-locations'),
	__('Haikou', 'wp-ultimo-locations'),
	__('Jinjiang', 'wp-ultimo-locations'),
	__('Lincheng', 'wp-ultimo-locations'),
	__('Nada', 'wp-ultimo-locations'),
	__('Qionghai', 'wp-ultimo-locations'),
	__('Qiongshan', 'wp-ultimo-locations'),
	__('Sansha', 'wp-ultimo-locations'),
	__('Sanya', 'wp-ultimo-locations'),
	__('Wanning', 'wp-ultimo-locations'),
	__('Wenchang', 'wp-ultimo-locations'),
	__('Xiuying', 'wp-ultimo-locations'),
);
