<?php // phpcs:ignore - @generation-checksum CN-HL-71
/**
 * State City List for HL - CN.
 *
 * City count: 71
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for HL - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Acheng', 'wp-ultimo-locations'),
	__('Anda', 'wp-ultimo-locations'),
	__('Baiquan', 'wp-ultimo-locations'),
	__('Bamiantong', 'wp-ultimo-locations'),
	__('Baoqing', 'wp-ultimo-locations'),
	__('Baoshan', 'wp-ultimo-locations'),
	__('Bayan', 'wp-ultimo-locations'),
	__('Bei’an', 'wp-ultimo-locations'),
	__('Binzhou', 'wp-ultimo-locations'),
	__('Boli', 'wp-ultimo-locations'),
	__('Chaihe', 'wp-ultimo-locations'),
	__('Chengzihe', 'wp-ultimo-locations'),
	__('Daqing', 'wp-ultimo-locations'),
	__('Dongning', 'wp-ultimo-locations'),
	__('Dongxing', 'wp-ultimo-locations'),
	__('Fendou', 'wp-ultimo-locations'),
	__('Fengxiang', 'wp-ultimo-locations'),
	__('Fujin', 'wp-ultimo-locations'),
	__('Fuli', 'wp-ultimo-locations'),
	__('Fuyu', 'wp-ultimo-locations'),
	__('Fuyuan', 'wp-ultimo-locations'),
	__('Gannan', 'wp-ultimo-locations'),
	__('Hailin', 'wp-ultimo-locations'),
	__('Hailun', 'wp-ultimo-locations'),
	__('Harbin', 'wp-ultimo-locations'),
	__('Hegang', 'wp-ultimo-locations'),
	__('Heihe', 'wp-ultimo-locations'),
	__('Honggang', 'wp-ultimo-locations'),
	__('Huanan', 'wp-ultimo-locations'),
	__('Hulan', 'wp-ultimo-locations'),
	__('Hulan Ergi', 'wp-ultimo-locations'),
	__('Jiamusi', 'wp-ultimo-locations'),
	__('Jidong', 'wp-ultimo-locations'),
	__('Jixi', 'wp-ultimo-locations'),
	__('Langxiang', 'wp-ultimo-locations'),
	__('Lanxi', 'wp-ultimo-locations'),
	__('Lianhe', 'wp-ultimo-locations'),
	__('Lingdong', 'wp-ultimo-locations'),
	__('Linkou', 'wp-ultimo-locations'),
	__('Longfeng', 'wp-ultimo-locations'),
	__('Longjiang', 'wp-ultimo-locations'),
	__('Mingshui', 'wp-ultimo-locations'),
	__('Mishan', 'wp-ultimo-locations'),
	__('Mudanjiang', 'wp-ultimo-locations'),
	__('Nehe', 'wp-ultimo-locations'),
	__('Nenjiang', 'wp-ultimo-locations'),
	__('Nianzishan', 'wp-ultimo-locations'),
	__('Ning’an', 'wp-ultimo-locations'),
	__('Qinggang', 'wp-ultimo-locations'),
	__('Qiqihar', 'wp-ultimo-locations'),
	__('Shangzhi', 'wp-ultimo-locations'),
	__('Shanhecun', 'wp-ultimo-locations'),
	__('Shuangcheng', 'wp-ultimo-locations'),
	__('Shuangyashan', 'wp-ultimo-locations'),
	__('Suifenhe', 'wp-ultimo-locations'),
	__('Suihua', 'wp-ultimo-locations'),
	__('Suileng', 'wp-ultimo-locations'),
	__('Tahe', 'wp-ultimo-locations'),
	__('Taihecun', 'wp-ultimo-locations'),
	__('Taikang', 'wp-ultimo-locations'),
	__('Tailai', 'wp-ultimo-locations'),
	__('Tieli', 'wp-ultimo-locations'),
	__('Wangkui', 'wp-ultimo-locations'),
	__('Wuchang', 'wp-ultimo-locations'),
	__('Xinqing', 'wp-ultimo-locations'),
	__('Yichun', 'wp-ultimo-locations'),
	__('Yilan', 'wp-ultimo-locations'),
	__('Youhao', 'wp-ultimo-locations'),
	__('Zhaodong', 'wp-ultimo-locations'),
	__('Zhaoyuan', 'wp-ultimo-locations'),
	__('Zhaozhou', 'wp-ultimo-locations'),
);
