<?php // phpcs:ignore - @generation-checksum CN-JX-16
/**
 * State City List for JX - CN.
 *
 * City count: 16
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for JX - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Changleng', 'wp-ultimo-locations'),
	__('Fenyi', 'wp-ultimo-locations'),
	__('Ganzhou', 'wp-ultimo-locations'),
	__('Ganzhou Shi', 'wp-ultimo-locations'),
	__('Guixi', 'wp-ultimo-locations'),
	__('Jianguang', 'wp-ultimo-locations'),
	__('Jingdezhen', 'wp-ultimo-locations'),
	__('Jingdezhen Shi', 'wp-ultimo-locations'),
	__('Jiujiang', 'wp-ultimo-locations'),
	__('Ji’an', 'wp-ultimo-locations'),
	__('Nanchang', 'wp-ultimo-locations'),
	__('Pingxiang', 'wp-ultimo-locations'),
	__('Poyang', 'wp-ultimo-locations'),
	__('Shangrao', 'wp-ultimo-locations'),
	__('Xinyu', 'wp-ultimo-locations'),
	__('Yichun', 'wp-ultimo-locations'),
);
