<?php // phpcs:ignore - @generation-checksum CN-SH-4
/**
 * State City List for SH - CN.
 *
 * City count: 4
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for SH - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Shanghai', 'wp-ultimo-locations'),
	__('Songjiang', 'wp-ultimo-locations'),
	__('Zhabei', 'wp-ultimo-locations'),
	__('Zhujiajiao', 'wp-ultimo-locations'),
);
