<?php // phpcs:ignore - @generation-checksum CN-TJ-69
/**
 * State City List for TJ - CN.
 *
 * City count: 69
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TJ - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Badaogu', 'wp-ultimo'),
	__('Baijian', 'wp-ultimo'),
	__('Bamencheng', 'wp-ultimo'),
	__('Bangjun', 'wp-ultimo'),
	__('Beicang', 'wp-ultimo'),
	__('Beihuaidian', 'wp-ultimo'),
	__('Beilizigu', 'wp-ultimo'),
	__('Biaokou', 'wp-ultimo'),
	__('Binhai New Area', 'wp-ultimo'),
	__('Caijiapu', 'wp-ultimo'),
	__('Caodian', 'wp-ultimo'),
	__('Chabaihu', 'wp-ultimo'),
	__('Changtun', 'wp-ultimo'),
	__('Chengtougu', 'wp-ultimo'),
	__('Chitu', 'wp-ultimo'),
	__('Cuijiamatou', 'wp-ultimo'),
	__('Dadunqiu', 'wp-ultimo'),
	__('Dakoutun', 'wp-ultimo'),
	__('Dashentang', 'wp-ultimo'),
	__('Dawangtai', 'wp-ultimo'),
	__('Daxinzhuang', 'wp-ultimo'),
	__('Dazhongzhuang', 'wp-ultimo'),
	__('Dongditou', 'wp-ultimo'),
	__('Dongshigu', 'wp-ultimo'),
	__('Erwangzhuang', 'wp-ultimo'),
	__('Fanzhuang', 'wp-ultimo'),
	__('Fengtai (Ninghe)', 'wp-ultimo'),
	__('Fuzhuang', 'wp-ultimo'),
	__('Gaojingzhuang', 'wp-ultimo'),
	__('Hanjiashu', 'wp-ultimo'),
	__('Hebeitun', 'wp-ultimo'),
	__('Hexiwu', 'wp-ultimo'),
	__('Huangcaotuo', 'wp-ultimo'),
	__('Huantuo', 'wp-ultimo'),
	__('Huogezhuang', 'wp-ultimo'),
	__('Jiangwakou', 'wp-ultimo'),
	__('Lianzhuang', 'wp-ultimo'),
	__('Lintingkou', 'wp-ultimo'),
	__('Liujiading', 'wp-ultimo'),
	__('Liukuaizhuang', 'wp-ultimo'),
	__('Liuzikou', 'wp-ultimo'),
	__('Luotuofangzi', 'wp-ultimo'),
	__('Meichang', 'wp-ultimo'),
	__('Mengquan', 'wp-ultimo'),
	__('Panzhuang', 'wp-ultimo'),
	__('Qingguang', 'wp-ultimo'),
	__('Sangzi', 'wp-ultimo'),
	__('Shangcang', 'wp-ultimo'),
	__('Shimianzhuang', 'wp-ultimo'),
	__('Shuangjiang', 'wp-ultimo'),
	__('Sigaozhuang', 'wp-ultimo'),
	__('Tianjin', 'wp-ultimo'),
	__('Touying', 'wp-ultimo'),
	__('Wangqinzhuang', 'wp-ultimo'),
	__('Weiwangzhuang', 'wp-ultimo'),
	__('Xiawuqi', 'wp-ultimo'),
	__('Xiditou', 'wp-ultimo'),
	__('Xinkaikou', 'wp-ultimo'),
	__('Xitazhuang', 'wp-ultimo'),
	__('Yangjinzhuang', 'wp-ultimo'),
	__('Yangliuqing', 'wp-ultimo'),
	__('Yinliu', 'wp-ultimo'),
	__('Yixingfu', 'wp-ultimo'),
	__('Youguzhuang', 'wp-ultimo'),
	__('Yuelongzhuang', 'wp-ultimo'),
	__('Yuguzhuang', 'wp-ultimo'),
	__('Zaojiacheng', 'wp-ultimo'),
	__('Zhangjiawo', 'wp-ultimo'),
	__('Zhaoguli', 'wp-ultimo'),
);
