<?php // phpcs:ignore - @generation-checksum CN-TW-52
/**
 * State City List for TW - CN.
 *
 * City count: 52
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for TW - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Baoying', 'wp-ultimo-locations'),
	__('Changshu City', 'wp-ultimo-locations'),
	__('Changzhou', 'wp-ultimo-locations'),
	__('Chengxiang', 'wp-ultimo-locations'),
	__('Dazhong', 'wp-ultimo-locations'),
	__('Dongkan', 'wp-ultimo-locations'),
	__('Dongtai', 'wp-ultimo-locations'),
	__('Fengxian', 'wp-ultimo-locations'),
	__('Gaogou', 'wp-ultimo-locations'),
	__('Gaoyou', 'wp-ultimo-locations'),
	__('Guiren', 'wp-ultimo-locations'),
	__('Haizhou', 'wp-ultimo-locations'),
	__('Hede', 'wp-ultimo-locations'),
	__("Huai'an", 'wp-ultimo-locations'),
	__('Huai’an Shi', 'wp-ultimo-locations'),
	__('Huilong', 'wp-ultimo-locations'),
	__('Hutang', 'wp-ultimo-locations'),
	__('Jiangyan', 'wp-ultimo-locations'),
	__('Jiangyin', 'wp-ultimo-locations'),
	__('Jingjiang', 'wp-ultimo-locations'),
	__('Jinsha', 'wp-ultimo-locations'),
	__('Juegang', 'wp-ultimo-locations'),
	__('Kunshan', 'wp-ultimo-locations'),
	__('Lianyungang Shi', 'wp-ultimo-locations'),
	__('Licheng', 'wp-ultimo-locations'),
	__('Mudu', 'wp-ultimo-locations'),
	__('Nanjing', 'wp-ultimo-locations'),
	__('Nantong', 'wp-ultimo-locations'),
	__('Pizhou', 'wp-ultimo-locations'),
	__('Qinnan', 'wp-ultimo-locations'),
	__('Rucheng', 'wp-ultimo-locations'),
	__('Sanmao', 'wp-ultimo-locations'),
	__('Songling', 'wp-ultimo-locations'),
	__('Suicheng', 'wp-ultimo-locations'),
	__('Suzhou', 'wp-ultimo-locations'),
	__('Taixing', 'wp-ultimo-locations'),
	__('Taizhou', 'wp-ultimo-locations'),
	__('Tongshan', 'wp-ultimo-locations'),
	__('Wuxi', 'wp-ultimo-locations'),
	__('Xiannü', 'wp-ultimo-locations'),
	__('Xiaolingwei', 'wp-ultimo-locations'),
	__('Xinghua', 'wp-ultimo-locations'),
	__('Xinpu', 'wp-ultimo-locations'),
	__('Yancheng', 'wp-ultimo-locations'),
	__('Yangzhou', 'wp-ultimo-locations'),
	__('Yicheng', 'wp-ultimo-locations'),
	__('Yushan', 'wp-ultimo-locations'),
	__('Zhangjiagang', 'wp-ultimo-locations'),
	__('Zhenjiang', 'wp-ultimo-locations'),
	__('Zhenzhou', 'wp-ultimo-locations'),
	__('Zhongxing', 'wp-ultimo-locations'),
	__('Zhouzhuang', 'wp-ultimo-locations'),
);
