<?php // phpcs:ignore - @generation-checksum CN-XZ-13
/**
 * State City List for XZ - CN.
 *
 * City count: 13
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for XZ - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Burang', 'wp-ultimo-locations'),
	__('Dêqên', 'wp-ultimo-locations'),
	__('Jiangzi', 'wp-ultimo-locations'),
	__('Lhasa', 'wp-ultimo-locations'),
	__('Nagqu', 'wp-ultimo-locations'),
	__('Nagqu Diqu', 'wp-ultimo-locations'),
	__('Ngari Diqu', 'wp-ultimo-locations'),
	__('Nyingchi Prefecture', 'wp-ultimo-locations'),
	__('Qamdo', 'wp-ultimo-locations'),
	__('Qamdo Shi', 'wp-ultimo-locations'),
	__('Rikaze', 'wp-ultimo-locations'),
	__('Saga', 'wp-ultimo-locations'),
	__('Shannan Diqu', 'wp-ultimo-locations'),
);
