<?php // phpcs:ignore - @generation-checksum CN-ZJ-41
/**
 * State City List for ZJ - CN.
 *
 * City count: 41
 *
 * @package WP_Ultimo\Country
 * @since 2.0.11
 */

// Exit if accessed directly
defined('ABSPATH') || exit;

/**
 * State City List for ZJ - CN.
 *
 * IMPORTANT:
 * This file is generated by build scripts, do not
 * change it directly or your changes will be LOST!
 *
 * @since 2.0.11
 */
return array(
	__('Deqing', 'wp-ultimo-locations'),
	__('Dongyang', 'wp-ultimo-locations'),
	__('Fenghua', 'wp-ultimo-locations'),
	__('Fuyang', 'wp-ultimo-locations'),
	__('Guli', 'wp-ultimo-locations'),
	__('Haining', 'wp-ultimo-locations'),
	__('Hangzhou', 'wp-ultimo-locations'),
	__('Huangyan', 'wp-ultimo-locations'),
	__('Huzhou', 'wp-ultimo-locations'),
	__('Jiaojiang', 'wp-ultimo-locations'),
	__('Jiashan', 'wp-ultimo-locations'),
	__('Jiaxing', 'wp-ultimo-locations'),
	__('Jiaxing Shi', 'wp-ultimo-locations'),
	__('Jinhua', 'wp-ultimo-locations'),
	__('Jinxiang', 'wp-ultimo-locations'),
	__('Kunyang', 'wp-ultimo-locations'),
	__('Lanxi', 'wp-ultimo-locations'),
	__('Lianghu', 'wp-ultimo-locations'),
	__('Linhai', 'wp-ultimo-locations'),
	__('Linping', 'wp-ultimo-locations'),
	__('Lishui', 'wp-ultimo-locations'),
	__('Luqiao', 'wp-ultimo-locations'),
	__('Ningbo', 'wp-ultimo-locations'),
	__('Ninghai', 'wp-ultimo-locations'),
	__('Puyang', 'wp-ultimo-locations'),
	__('Quzhou', 'wp-ultimo-locations'),
	__('Shangyu', 'wp-ultimo-locations'),
	__('Shaoxing', 'wp-ultimo-locations'),
	__('Shenjiamen', 'wp-ultimo-locations'),
	__('Taizhou', 'wp-ultimo-locations'),
	__('Wenling', 'wp-ultimo-locations'),
	__('Wenzhou', 'wp-ultimo-locations'),
	__('Wuzhen', 'wp-ultimo-locations'),
	__('Xianju', 'wp-ultimo-locations'),
	__('Xiaoshan', 'wp-ultimo-locations'),
	__('Yiwu', 'wp-ultimo-locations'),
	__('Yuyao', 'wp-ultimo-locations'),
	__('Zhaobaoshan', 'wp-ultimo-locations'),
	__('Zhicheng', 'wp-ultimo-locations'),
	__('Zhoushan', 'wp-ultimo-locations'),
	__('Zhuji', 'wp-ultimo-locations'),
);
